#
# These commands add the CocoComboArchive to active-metadata-store and a new governance engine for clinical trials
# to engine-host.  They use IntelliJ's HTTP Client.
#
@baseURL=https://localhost:9443
@adminUserId=garygeeke

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "{{adminUserId}}",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}

###
# ---------------------------------------------
# Metadata Access Store: active-metadata-store
#
##

###
# @name Load open metadata archive file
# Load a file that contains open metadata types and instances.
POST {{baseURL}}/open-metadata/server-operations/servers/active-metadata-store/instance/open-metadata-archives/file
Authorization: Bearer {{token}}
Content-Type: text/plain

content-packs/CocoComboArchive.omarchive


###
# -------------------------
# Engine Host: engine-host
#

###
# Add the ClinicalTrials at CocoPharmaceuticals engine to engine-host
POST {{baseURL}}/open-metadata/admin-services/servers/engine-host/engine
Authorization: Bearer {{token}}
Content-Type: application/json

{
      "class": "EngineConfig",
      "engineId": "113c35dc-ea92-40ce-aef2-daf9e08c1b05",
      "engineQualifiedName": "ClinicalTrials@CocoPharmaceuticals",
      "engineUserId": "generalnpa"
}


###
# Add the AssetQuality at CocoPharmaceuticals engine to engine-host
POST {{baseURL}}/open-metadata/admin-services/servers/engine-host/engine
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class": "EngineConfig",
  "engineId": "76257f18-293f-4e7c-b79f-8b7e5fa44552",
  "engineQualifiedName": "AssetQuality@CocoPharmaceuticals",
  "engineUserId": "generalnpa"
}


###
# Restart the engine-host server on the OMAG Server Platform.
POST {{baseURL}}/open-metadata/platform-services/server-platform/servers/engine-host/instance
Authorization: Bearer {{token}}


###