#
# These commands rebuild the sample configuration documents for simple-metadata-server, active-metadata-server,
# view-server, engine-host and integration-daemon.  They use IntelliJ's HTTP Client.
#
@baseURL=https://localhost:9443
@adminUserId=garygeeke
@auditLogTopic=logging

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "{{adminUserId}}",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}

###
# ---------------------------------------------
# Metadata Access Store: simple-metadata-store
#

###
# @name Add PostgreSQL audit log destination
# Add the database audit log destination to the server's configuration document.  The list of severities that are sent to this destination are passed on the request body.  An empty list means all severities.
# The server may have multiple audit log destinations configured.  Typically each destination has a different subset of the severities configured.
POST {{baseURL}}/open-metadata/admin-services/servers/simple-metadata-store/audit-log-destinations/postgres
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "supportedSeverities" : ["Error", "Exception", "Activity", "Action", "Decision"],
  "databaseURL": "~{repositoryDatabaseURL}~?currentSchema=audit_logs",
  "databaseSchema": "audit_logs",
  "secretsStore": "~{egeriaServersSecretsStore}~",
  "secretsCollectionName": "~{repositorySecretCollectionName}~"
}

###
# ---------------------------------------------
# Metadata Access Store: active-metadata-store
#

###
# @name Add PostgreSQL audit log destination
# Add the database audit log destination to the server's configuration document.  The list of severities that are sent to this destination are passed on the request body.  An empty list means all severities.
# The server may have multiple audit log destinations configured.  Typically each destination has a different subset of the severities configured.
POST {{baseURL}}/open-metadata/admin-services/servers/active-metadata-store/audit-log-destinations/postgres
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "supportedSeverities" : ["Error", "Exception", "Activity", "Action", "Decision"],
  "databaseURL": "~{repositoryDatabaseURL}~?currentSchema=audit_logs",
  "databaseSchema": "audit_logs",
  "secretsStore": "~{egeriaServersSecretsStore}~",
  "secretsCollectionName": "~{repositorySecretCollectionName}~"
}

###
# -------------------------
# View Server: view-server
#
###
# @name Add PostgreSQL audit log destination
# Add the database audit log destination to the server's configuration document.  The list of severities that are sent to this destination are passed on the request body.  An empty list means all severities.
# The server may have multiple audit log destinations configured.  Typically each destination has a different subset of the severities configured.
POST {{baseURL}}/open-metadata/admin-services/servers/view-server/audit-log-destinations/postgres
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "supportedSeverities" : ["Error", "Exception", "Activity", "Action", "Decision"],
  "databaseURL": "~{repositoryDatabaseURL}~?currentSchema=audit_logs",
  "databaseSchema": "audit_logs",
  "secretsStore": "~{egeriaServersSecretsStore}~",
  "secretsCollectionName": "~{repositorySecretCollectionName}~"
}


###
# -------------------------
# Engine Host: engine-host
#
###
# @name Add PostgreSQL audit log destination
# Add the database audit log destination to the server's configuration document.  The list of severities that are sent to this destination are passed on the request body.  An empty list means all severities.
# The server may have multiple audit log destinations configured.  Typically each destination has a different subset of the severities configured.
POST {{baseURL}}/open-metadata/admin-services/servers/engine-host/audit-log-destinations/postgres
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "supportedSeverities" : ["Error", "Exception", "Activity", "Action", "Decision"],
  "databaseURL": "~{repositoryDatabaseURL}~?currentSchema=audit_logs",
  "databaseSchema": "audit_logs",
  "secretsStore": "~{egeriaServersSecretsStore}~",
  "secretsCollectionName": "~{repositorySecretCollectionName}~"
}


###
# ---------------------------------------
# Integration Daemon: integration-daemon
#
###
# @name Add PostgreSQL audit log destination
# Add the database audit log destination to the server's configuration document.  The list of severities that are sent to this destination are passed on the request body.  An empty list means all severities.
# The server may have multiple audit log destinations configured.  Typically each destination has a different subset of the severities configured.
POST {{baseURL}}/open-metadata/admin-services/servers/integration-daemon/audit-log-destinations/postgres
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "supportedSeverities" : ["Error", "Exception", "Activity", "Action", "Decision"],
  "databaseURL": "~{postgreSQLDatabaseURL}~?currentSchema=audit_logs",
  "databaseSchema": "audit_logs",
  "secretsStore": "~{egeriaServersSecretsStore}~",
  "secretsCollectionName": "~{postgreSQLServerCollectionName}~"
}


###