#
# These commands connect simple-metadata-store and active-metadata-store together in a cohort called "sinpleCohort".
# They use IntelliJ's HTTP Client.
#
@baseURL=https://localhost:9443
@adminUserId=garygeeke
@cohort=sampleCohort

# ---------------------------------------------
# Metadata Access Store: simple-metadata-store
#
###
# The Cohort uses Apache Kafka and so simple-metadata-store needs information about your kafka.
POST {{baseURL}}/open-metadata/admin-services/servers/simple-metadata-store/event-bus
Content-Type: application/json

{
    "producer": {
        "bootstrap.servers": "~{kafkaEndpoint}~"
    },
    "consumer":{
        "bootstrap.servers": "~{kafkaEndpoint}~"
    }
}

###
# @name Set local metadata collection id for simple-metadata-store
# Fix the metadata collection id
POST {{baseURL}}/open-metadata/admin-services/servers/simple-metadata-store/local-repository/metadata-collection-id
Content-Type: text/plain

094b2e2e-bb79-4c5e-a0f0-ac2120f23624

###
# Add the server to the cohort.
POST {{baseURL}}/open-metadata/admin-services/servers/simple-metadata-store/cohorts/{{cohort}}


###
# ---------------------------------------------
# Metadata Access Store: active-metadata-store
#

###
# Set up the description of this server.
POST {{baseURL}}/open-metadata/admin-services/servers/active-metadata-store/server-description
Content-Type: text/plain

A metadata store that supports Open Metadata Access Services (OMASs) with event notifications.  It provides metadata to the cohort, engine-host and integration-daemon.

###
# @name Set local metadata collection id for active-metadata-store
# Fix the metadata collection id
POST {{baseURL}}/open-metadata/admin-services/servers/active-metadata-store/local-repository/metadata-collection-id
Content-Type: text/plain

fdf8de25-b213-4fa4-95d5-c9eb91e60b21

###
# Add the server to the cohort.
POST {{baseURL}}/open-metadata/admin-services/servers/active-metadata-store/cohorts/{{cohort}}


###
# ---------------------------------------------
# Metadata Access Point: metadata-access-point
#
###
# Set up the user Id that this server should use on open metadata requests when it is processing events (and consequently there is no end user id to use).
POST {{baseURL}}/open-metadata/admin-services/servers/metadata-access-point/server-user-id?id=activenpa

###
# Set up the description of this server.
POST {{baseURL}}/open-metadata/admin-services/servers/metadata-access-point/server-description
Content-Type: text/plain

A metadata access point that supports Open Metadata Access Services (OMASs) with event notifications.  It provides metadata to view-server via the cohort.


###
# Set up the common properties needed to call your event bus.  The value of ~{kafkaEndpoint}~ is resolved in the
# application.properties file using the `platform.placeholder.variables` property.
POST {{baseURL}}/open-metadata/admin-services/servers/metadata-access-point/event-bus
Content-Type: application/json

{
  "producer":
  {
    "bootstrap.servers":"~{kafkaEndpoint}~"
  },
  "consumer":
  {
    "bootstrap.servers":"~{kafkaEndpoint}~"
  }
}

###
# Add the server to the cohort.
POST {{baseURL}}/open-metadata/admin-services/servers/metadata-access-point/cohorts/{{cohort}}


###
# Set up all of the registered, undeprecated Open Metadata Access Services (OMASs) with kafka notifications enabled.
POST {{baseURL}}/open-metadata/admin-services/servers/metadata-access-point/access-services
Content-Type: application/json


###
# -------------------------
# View Server: view-server
#

###
# Point the view server at the metadata-access-point
POST {{baseURL}}/open-metadata/admin-services/servers/view-server/view-services
Content-Type: application/json

{
  "class": "ViewServiceRequestBody",
  "omagserverName": "metadata-access-point",
  "omagserverPlatformRootURL": "~{egeriaEndpoint}~"
}


###