# Egeria-my-profile-api
# Work with a user's personal profile - this API is designed for retrieving the logged on user's personal profile.
# Updates to the actors associate with a user are made using the Actor Manager API.
# https://egeria-project.org/concepts/personal-profile

@baseURL=https://localhost:7443
@viewServer=view-server

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "peterprofile",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}


###
# @name Get My Profile
# Return the profile for this user.
#
# @param serverName name of the server instances for this request
# @param requestBody optional properties to restrict search by and control how the results are formatted
#
# @return profile response object or
# InvalidParameterException the userId is null or invalid or
# PropertyServerException a problem retrieving information from the property server(s) or
# UserNotAuthorizedException the requesting user is not authorized to issue this request.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/my-profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "GetRequestBody",
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name getMyActors
# Return the list of actors linked to the user's profile.
#
# @param serverName name of the server instances for this request
# @param requestBody optional properties to restrict search by and control how the results are formatted
#
# @return profile response object or
# InvalidParameterException the userId is null or invalid or
# PropertyServerException a problem retrieving information from the property server(s) or
# UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/my-profile/actors
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ResultsRequestBody",
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name getMyUserIdentities
# Return the list of user identities linked to the user's profile.
#
# @param serverName name of the server instances for this request
# @param requestBody optional properties to restrict search by and control how the results are formatted
#
# @return profile response object or
# InvalidParameterException the userId is null or invalid or
# PropertyServerException a problem retrieving information from the property server(s) or
# UserNotAuthorizedException the requesting user is not authorized to issue this request.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/my-profile/actors/user-identities
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ResultsRequestBody",
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name getMyRoles
# Return the list of assigned roles linked to the user's profile.
#
# @param serverName name of the server instances for this request
# @param requestBody optional properties to restrict search by and control how the results are formatted
#
# @return profile response object or
# InvalidParameterException the userId is null or invalid or
# PropertyServerException a problem retrieving information from the property server(s) or
# UserNotAuthorizedException the requesting user is not authorized to issue this request.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/my-profile/actors/assigned-roles
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ResultsRequestBody",
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name getMyAssignedActions
# Return the list of actions that have been assigned to the user's profile, roles, or user identity.
#
# @param serverName name of the server instances for this request
# @param includeUserIds get actions for linked userIds; default=true
# @param includeRoles   get actions for linked roles; default=true
# @param requestBody optional properties to restrict search by and control how the results are formatted
#
# @return profile response object or
# InvalidParameterException the userId is null or invalid or
# PropertyServerException a problem retrieving information from the property server(s) or
# UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/my-profile/assigned-actions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ActivityStatusRequestBody",
  "activityStatusList": ["REQUESTED", "WAITING", "IN_PROGRESS"],
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name getMySponsoredActions
# Return the list of actions linked to the user's profile, roles, or user identity that this user has sponsored.
#
# @param serverName name of the server instances for this request
# @param includeUserIds get actions for linked userIds; default=true
# @param includeRoles   get actions for linked roles; default=true
# @param requestBody optional properties to restrict search by and control how the results are formatted
#
# @return profile response object or
# InvalidParameterException the userId is null or invalid or
# PropertyServerException a problem retrieving information from the property server(s) or
# UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/my-profile/sponsored-actions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ActivityStatusRequestBody",
  "activityStatusList": ["REQUESTED", "WAITING", "IN_PROGRESS"],
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}



###
# @name getMyRequestedActions
# Return the list of actions linked to the user's profile, roles, or user identity that this user has sponsored.
#
# @param serverName name of the server instances for this request
# @param includeUserIds get actions for linked userIds; default=true
# @param includeRoles   get actions for linked roles; default=true
# @param requestBody optional properties to restrict search by and control how the results are formatted
#
# @return profile response object or
# InvalidParameterException the userId is null or invalid or
# PropertyServerException a problem retrieving information from the property server(s) or
# UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/my-profile/requested-actions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ActivityStatusRequestBody",
  "activityStatusList": ["REQUESTED", "WAITING", "IN_PROGRESS"],
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name getMyResources
# Return the list of assigned resources linked to the user's profile.
#
# @param serverName name of the server instances for this request
# @param includeUserIds get actions for linked userIds; default=true
# @param includeRoles   get actions for linked roles; default=true
# @param requestBody optional properties to restrict search by and control how the results are formatted
#
# @return profile response object or
# InvalidParameterException the userId is null or invalid or
# PropertyServerException a problem retrieving information from the property server(s) or
# UserNotAuthorizedException the requesting user is not authorized to issue this request.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/my-profile/assigned-resources
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ResultsRequestBody",
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name logMyActivity
# Add the supplied notification to the user's activity log.
#
# @param serverName name of the server instances for this request
# @param requestBody details of the user profile to add
#
# @return profile response object or
# InvalidParameterException the userId is null or invalid or
# PropertyServerException a problem retrieving information from the property server(s) or
# UserNotAuthorizedException the requesting user is not authorized to issue this request.
#/
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/my-profile/log-my-activity
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewAttachmentRequestBody",
  "properties" : {
     "class" : "NotificationProperties",
     "qualifiedName" : "Add name here",
     "displayName" : "Add name here",
     "situation" : "Describe notification (title/summary)",
     "description" : "Add text for notification",
     "expectedBehaviour" : "Optionally, if action is to be taken, describe it here"
  }
}


###
# @name journalMyActivity
# Add the supplied notification to the user's journal.
#
# @param serverName name of the server instances for this request
# @param requestBody details of the user profile to add
#
# @return profile response object or
# InvalidParameterException the userId is null or invalid or
# PropertyServerException a problem retrieving information from the property server(s) or
# UserNotAuthorizedException the requesting user is not authorized to issue this request.
#/
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/my-profile/journal-my-activity
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewAttachmentRequestBody",
  "properties" : {
    "class" : "NotificationProperties",
    "qualifiedName" : "Add name here",
    "displayName" : "Add name here",
    "situation" : "Describe notification (title/summary)",
    "description" : "Add text for notification",
    "expectedBehaviour" : "Optionally, if action is to be taken, describe it here"
  }
}


###
# @name blogMyActivity
# Add the supplied notification to the user's blog.
#
# @param serverName name of the server instances for this request
# @param requestBody details of the user profile to add
#
# @return profile response object or
# InvalidParameterException the userId is null or invalid or
# PropertyServerException a problem retrieving information from the property server(s) or
# UserNotAuthorizedException the requesting user is not authorized to issue this request.
#/
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/my-profile/blog-my-activity
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewAttachmentRequestBody",
  "properties" : {
    "class" : "NotificationProperties",
    "qualifiedName" : "Add name here",
    "displayName" : "Add name here",
    "situation" : "Describe notification (title/summary)",
    "description" : "Add text for notification",
    "expectedBehaviour" : "Optionally, if action is to be taken, describe it here"
  }
}


###
# =====================================================================================================================
# If a userId does not have a user profile

###
# @name Add My Profile
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/my-profile/new
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewElementRequestBody",
  "isOwnAnchor": true,
  "properties": {
    "class" : "PersonProperties",
    "qualifiedName": "add unique name here",
    "displayName": "add preferred name here",
    "courtesyTitle" : "",
    "initials" : "",
    "givenNames" : "",
    "surname" : "",
    "fullName" : "",
    "pronouns" : "",
    "jobTitle" : "",
    "employeeNumber" : "",
    "employeeType" : "",
    "preferredLanguage" : "",
    "residentCountry" : "",
    "timeZone" : "",
    "description": "add description here",
    "additionalProperties": {
      "property1" : "propertyValue1",
      "property2" : "propertyValue2"
    }
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}
