# Egeria-my-profile-view-service

@baseURL=https://localhost:9443
@viewServer=view-server

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "peterprofile",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}


###
# @name Get My Profile
GET {{baseURL}}/servers/{{viewServer}}/api/open-metadata/my-profile
Authorization: Bearer {{token}}


###
# @name Add My Profile
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/my-profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewElementRequestBody",
  "isOwnAnchor": true,
  "properties": {
    "class" : "PersonProperties",
    "qualifiedName": "add unique name here",
    "displayName": "add preferred name here",
    "courtesyTitle" : "",
    "initials" : "",
    "givenNames" : "",
    "surname" : "",
    "fullName" : "",
    "pronouns" : "",
    "jobTitle" : "",
    "employeeNumber" : "",
    "employeeType" : "",
    "preferredLanguage" : "",
    "residentCountry" : "",
    "timeZone" : "",
    "description": "add description here",
    "additionalProperties": {
      "property1" : "propertyValue1",
      "property2" : "propertyValue2"
    }
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}
