# Egeria-asset-maker-view-service
# The Asset Maker OMVS provides APIs for supporting the creation and editing of assets.

@baseURL=https://localhost:9443
@viewServer=view-server

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "peterprofile",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}


###
# =====================================================================================================================
# Work with Assets
# https://egeria-project.org/concepts/asset

@assetGUID=add guid here


###
# @name createAsset
# Create an asset.
#
# Request body provides             properties for the asset.
#
# Returns unique identifier of the newly created element
#  InvalidParameterException  one of the parameters is invalid.
#  PropertyServerException    a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/assets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewElementRequestBody",
  "anchorGUID" : "add guid here",
  "isOwnAnchor": false,
  "parentGUID": "add guid here",
  "parentRelationshipTypeName": "add type name here",
  "parentRelationshipProperties": {
    "class": "RelationshipElementProperties",
    "propertyValueMap" : {
      "description" : {
        "class": "PrimitiveTypePropertyValue",
        "typeName": "string",
        "primitiveValue" : "New description"
      }
    }
  },
  "parentAtEnd1": false,
  "properties": {
    "class" : "AssetProperties",
    "typeName" : "enter the type of the element",
    "qualifiedName": "add unique name here",
    "displayName": "add short name here",
    "description": "add description here",
    "additionalProperties": {
      "property1" : "propertyValue1",
      "property2" : "propertyValue2"
    },
    "extendedProperties": {
      "property1" : "propertyValue1",
      "property2" : "propertyValue2"
    },
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name createAssetFromTemplate
# Create a new metadata element to represent an asset using an existing metadata element as a template.
# The template defines additional classifications and relationships that should be added to the new element.
#
# Request body provides properties that override the template
#
# Returns unique identifier of the new metadata element
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    there is a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/assets/from-template
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "TemplateRequestBody",
  "anchorGUID" : "add guid here",
  "isOwnAnchor": false,
  "parentGUID": "add guid here",
  "parentRelationshipTypeName": "add type name here",
  "parentRelationshipProperties": {
    "class": "RelationshipElementProperties",
    "propertyValueMap" : {
      "description" : {
        "class": "PrimitiveTypePropertyValue",
        "typeName": "string",
        "primitiveValue" : "New description"
      }
    }
  },
  "parentAtEnd1": false,
  "templateGUID": "add guid here",
  "replacementProperties": {
    "class": "ElementProperties",
    "propertyValueMap" : {
      "description" : {
        "class": "PrimitiveTypePropertyValue",
        "typeName": "string",
        "primitiveValue" : "New description"
      }
    }
  },
  "placeholderPropertyValues":  {
    "placeholder1" : "propertyValue1",
    "placeholder2" : "propertyValue2"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name updateAsset
# Update the properties of an asset.
#
# @param assetGUID unique identifier of the asset (returned from create)
# Request body provides     properties for the new element.
#
# Returns void or
#  InvalidParameterException  one of the parameters is invalid.
#  PropertyServerException    a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/assets/{{assetGUID}}/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "UpdateElementRequestBody",
  "properties": {
    "class" : "AssetProperties",
    "typeName" : "enter the type of the element",
    "qualifiedName": "add unique name here",
    "displayName": "add short name here",
    "description": "add description here",
    "additionalProperties": {
      "property1" : "propertyValue1",
      "property2" : "propertyValue2"
    },
    "extendedProperties": {
      "property1" : "propertyValue1",
      "property2" : "propertyValue2"
    }
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name deleteAsset
# Delete an asset.
#
# @param assetGUID  unique identifier of the element to delete
# Request body provides  description of the relationship.
#
# Returns void or
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/assets/{{assetGUID}}/delete
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteElementRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name getAssetsByName
# Returns the list of assets with a particular name.
#
# Request body provides string to find in the properties
#
# Returns list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    there is a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/assets/by-name
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "FilterRequestBody",
  "filter" : "Add name here",
  "startFrom" : 0,
  "pageSize": 10,
  "metadataElementTypeName": "GovernanceActionType",
  "metadataElementSubtypeNames": [],
  "skipRelationships": [],
  "includeOnlyRelationships": [],
  "relationshipsPageSize": 100,
  "skipClassifiedElements": [],
  "includeOnlyClassifiedElements": [],
  "graphQueryDepth" : 10,
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "limitResultsByStatus" : ["ACTIVE"],
  "sequencingOrder" : "PROPERTY_ASCENDING",
  "sequencingProperty" : "qualifiedName"
}


###
# @name findAssets
# Retrieve the list of asset metadata elements that contain the search string.
#
# Request body provides string to find in the properties
#
# Returns list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    there is a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/assets/by-search-string
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "SearchStringRequestBody",
  "searchString": "xxx",
  "metadataElementTypeName": "GovernanceActionType",
  "metadataElementSubtypeNames": [],
  "skipRelationships": [],
  "includeOnlyRelationships": [],
  "relationshipsPageSize": 100,
  "skipClassifiedElements": [],
  "includeOnlyClassifiedElements": [],
  "graphQueryDepth" : 10,
  "startsWith" : false,
  "endsWith" : false,
  "ignoreCase" : true,
  "startFrom" : 0,
  "pageSize": 0,
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "limitResultsByStatus" : ["ACTIVE"],
  "sequencingOrder" : "PROPERTY_ASCENDING",
  "sequencingProperty" : "qualifiedName"
}


###
# @name getAssetByGUID
# Return the properties of a specific asset.
#
# @param assetGUID    unique identifier of the required element
# Request body provides string to find in the properties
#
# Returns list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    there is a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/assets/{{assetGUID}}/retrieve
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "GetRequestBody",
  "metadataElementTypeName": "",
  "metadataElementSubtypeNames": [],
  "skipRelationships": [],
  "includeOnlyRelationships": [],
  "relationshipsPageSize": 100,
  "skipClassifiedElements": [],
  "includeOnlyClassifiedElements": [],
  "graphQueryDepth" : 10,
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# =====================================================================================================================
# Processes and Actions are assets.  
# https://egeria-project.org/concepts/action
###
# @name findProcesses
# Retrieve the processes that match the search string and activity status.
#
# @param serverName name of the server instances for this request
# @param urlMarker  view service URL marker
# @param requestBody     status of the action (null means current active)
#
# @return list of action beans or
# InvalidParameterException a parameter is invalid
# PropertyServerException the server is not available
# UserNotAuthorizedException the calling user is not authorized to issue the call
#/
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/processes/find-by-search-string
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ActivityStatusSearchString",
  "searchString" : "xxx",
  "activityStatus" : "IN_PROGRESS",
  "startsWith" : false,
  "endsWith" : false,
  "ignoreCase" : true,
  "startFrom" : 0,
  "pageSize": 0,
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "limitResultsByStatus" : ["ACTIVE"],
  "sequencingOrder" : "PROPERTY_ASCENDING",
  "sequencingProperty" : "qualifiedName"
}

###
# @name getProcessesByCategory
# Retrieve the actions that match the category name and status.
#
# @param serverName name of the server instances for this request
# @param urlMarker  view service URL marker
# @param requestBody     status of the action (null means current active)
#
# @return list of action beans or
# InvalidParameterException a parameter is invalid
# PropertyServerException the server is not available
# UserNotAuthorizedException the calling user is not authorized to issue the call
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/processes/by-category
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ActivityStatusFilterRequestBody",
  "filter" : "xxx",
  "activityStatus" : "IN_PROGRESS",
  "startFrom" : 0,
  "pageSize": 0,
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "limitResultsByStatus" : ["ACTIVE"],
  "sequencingOrder" : "PROPERTY_ASCENDING",
  "sequencingProperty" : "qualifiedName"
}

###

@actionTargetGUID=add guid here

###
# @name createAction
# Create a new action and link it to the supplied actor and targets (if applicable).
#
# @param serverName name of the server instances for this request
# @param urlMarker  view service URL marker
# @param requestBody properties of the action
#
# @return unique identifier of the action or
# InvalidParameterException a parameter is invalid
# PropertyServerException the server is not available
# UserNotAuthorizedException the calling user is not authorized to issue the call
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/actions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ActionRequestBody"
}

###

# @name addActionTarget
# Add an element to an action's workload.
#
# @param serverName name of the service to route the request to.
# @param urlMarker  view service URL marker
# @param actionGUID unique identifier of the integration service.
# @param metadataElementGUID unique identifier of the metadata element that is a catalog target.
# @param requestBody properties for the relationship.
#
# @return guid or
# InvalidParameterException one of the parameters is null or invalid or
# UserNotAuthorizedException user not authorized to issue this request or
# PropertyServerException problem storing the catalog target definition.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/actions/{{actionGUID}}/action-targets/{{metadataElementGUID}}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
   "properties" : {
     "class": "ActionTargetProperties",
     "activityStatus" : "IN_PROGRESS",
     "actionTargetName" : "add label here",
     "startTime" : "{{$isoTimestamp}}",
     "completionTime" : "{{$isoTimestamp}}",
     "completionMessage" : "Add message here"
  },
   "externalSourceGUID": "Add guid here",
   "externalSourceName": "Add qualified name here",
   "forLineage": false,
   "forDuplicateProcessing": false,
   "effectiveTime" : "{{$isoTimestamp}}"
}

###
# @name updateActionTargetProperties
# Update the properties associated with an Action Target for an action.
#
# @param serverName name of the server instances for this request
# @param urlMarker  view service URL marker
# @param actionTargetGUID               unique identifier of the action target relationship
# @param requestBody properties to change
#
# @return void or
# InvalidParameterException a parameter is invalid
# PropertyServerException the server is not available
# UserNotAuthorizedException the calling user is not authorized to issue the call
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/actions/action-targets/{{actionTargetGUID}}/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "UpdateRelationshipRequestBody",
  "properties": {
    "class": "ActionTargetProperties",
     "activityStatus" : "IN_PROGRESS",
     "actionTargetName" : "add label here",
     "startTime" : "{{$isoTimestamp}}",
     "completionTime" : "{{$isoTimestamp}}",
     "completionMessage" : "Add message here"
  },
  "mergeUpdate": true,
  "externalSourceGUID": "",
  "externalSourceName": "",
  "forLineage": false,
  "forDuplicateProcessing": true,
  "effectiveTime": "{{$isoTimestamp}}"
}

###
# @name getActionTarget
# Retrieve a specific action target associated with an action.
#
# @param serverName name of the service to route the request to
# @param urlMarker  view service URL marker
# @param relationshipGUID unique identifier of the relationship
# @param requestBody details of how the retrieve should be processed
#
# @return details of the governance service and the asset types it is registered for or
# InvalidParameterException one of the parameters is null or invalid or
# UserNotAuthorizedException user not authorized to issue this request or
# PropertyServerException problem storing the integration connector definition.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/actions/action-targets/{{actionTargetGUID}}/retrieve
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "GetRequestBody",
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name getActionTargets
# Return a list of elements that are target elements for an action.
#
# @param serverName name of the service to route the request to.
# @param urlMarker  view service URL marker
# @param actionGUID unique identifier of the integration connector.
# @param requestBody describe how results are to be returned
#
# @return list of unique identifiers or
# InvalidParameterException one of the parameters is null or invalid or
# UserNotAuthorizedException user not authorized to issue this request or
# PropertyServerException problem storing the integration connector definition.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/actions/{{actionGUID}}/action-targets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ActivityStatusRequestBody",
  "activityStatus": "IN_PROGRESS"
}

###
# @name getActionsForActionTarget
# Retrieve the "Actions" that are chained off of an action target element.
#
# @param serverName name of the server instances for this request
# @param urlMarker  view service URL marker
# @param metadataElementGUID unique identifier of the element to start with
# @param requestBody     status of the action (null means current active)
#
# @return list of action beans or
# InvalidParameterException a parameter is invalid
# PropertyServerException the server is not available
# UserNotAuthorizedException the calling user is not authorized to issue the call
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/elements/{{metadataElementGUID}}/action-targets/actions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ActivityStatusRequestBody",
  "activityStatus": "IN_PROGRESS"
}


###
# Linking Actors and Actions
# https://egeria-project.org/concepts/action

@actionGUID=add guid here
@actorGUID=add guid here

###
# @name assignAction
# Assign an action to an actor. Request body is optional.
#
# @param serverName name of the server instances for this request
# @param urlMarker  view service URL marker
# @param actionGUID unique identifier of the action
# @param actorGUID  actor to assign the action to
# @param requestBody  request body
#
# @return void or
# InvalidParameterException a parameter is invalid
# PropertyServerException the server is not available
# UserNotAuthorizedException the calling user is not authorized to issue the call
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/actions/{{actionGUID}}/assign/{{actorGUID}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "class" : "NewRelationshipRequestBody",
   "properties" : {
     "class": "AssignmentScopeProperties",
     "label" : "add label here",
     "description" : "Add description here"
  },
   "externalSourceGUID": "Add guid here",
   "externalSourceName": "Add qualified name here",
   "forLineage": false,
   "forDuplicateProcessing": false,
   "effectiveTime" : "{{$isoTimestamp}}"
}


###
# @name reassignAction
# Assign an action to a new actor.  This will unassign all other actors previously assigned to the action.
#
# @param serverName name of the server instances for this request
# @param urlMarker  view service URL marker
# @param actionGUID unique identifier of the action
# @param actorGUID  actor to assign the action to
# @param requestBody  request body
#
# @return void or
# InvalidParameterException a parameter is invalid
# PropertyServerException the server is not available
# UserNotAuthorizedException the calling user is not authorized to issue the call
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/actions/{{actionGUID}}/reassign/{{actorGUID}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "class" : "NewRelationshipRequestBody",
   "properties" : {
     "class": "AssignmentScopeProperties",
     "label" : "add label here",
     "description" : "Add description here"
  },
   "externalSourceGUID": "Add guid here",
   "externalSourceName": "Add qualified name here",
   "forLineage": false,
   "forDuplicateProcessing": false,
   "effectiveTime" : "{{$isoTimestamp}}"
}


###
# @name unassignAction
# Remove an action from an actor.
#
# @param serverName name of the server instances for this request
# @param urlMarker  view service URL marker
# @param actionGUID unique identifier of the action
# @param actorGUID  actor to assign the action to
# @param requestBody  request body
#
# @return void or
# InvalidParameterException a parameter is invalid
# PropertyServerException the server is not available
# UserNotAuthorizedException the calling user is not authorized to issue the call
#/
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/actions/{{actionGUID}}/reassign/{{actorGUID}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "class" : "DeleteRelationshipRequestBody",
   "externalSourceGUID": "Add guid here",
   "externalSourceName": "Add qualified name here",
   "forLineage": false,
   "forDuplicateProcessing": false,
   "effectiveTime" : "{{$isoTimestamp}}"
}

###

@actorGUIG=add guid here

###
# @name getAssignedActions
# Retrieve the actions for a particular actor.
#
# @param serverName name of the server instances for this request
# @param urlMarker  view service URL marker
# @param actorGUID unique identifier of the role
# @param requestBody     status of the action (null means current active)
#
# @return list of action beans or
# InvalidParameterException a parameter is invalid
# PropertyServerException the server is not available
# UserNotAuthorizedException the calling user is not authorized to issue the call
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/actors/{{actorGUID}}/assigned/actions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ActivityStatusRequestBody",
  "activityStatus": "IN_PROGRESS"
}

###
# @name getActionsForSponsor
# Retrieve the "Actions" that are chained off of a sponsor's element.
#
# @param serverName name of the server instances for this request
# @param urlMarker  view service URL marker
# @param metadataElementGUID unique identifier of the element to start with
# @param requestBody     status of the action (null means current active)
#
# @return list of action beans or
# InvalidParameterException a parameter is invalid
# PropertyServerException the server is not available
# UserNotAuthorizedException the calling user is not authorized to issue the call
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/elements/{{metadataElementGUID}}/sponsored/actions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ActivityStatusRequestBody",
  "activityStatus": "IN_PROGRESS"
}


###
# =====================================================================================================================
# IT infrastructure is a type of asset.  It includes hosts and servers.
#
#

###
# @name findInfrastructure
# https://egeria-project.org/concepts/asset
# Returns the list of infrastructure assets matching the search string and optional deployment status.
#
# @param serverName name of the service to route the request to
# @param urlMarker  view service URL marker
# @param requestBody string to find in the properties
#
# @return a list of infrastructure assets
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/infrastructure-assets/by-search-string
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeploymentStatusSearchString",
  "searchString" : "xxx",
  "deploymentStatus" : "ACTIVE",
  "startsWith" : false,
  "endsWith" : false,
  "ignoreCase" : true,
  "startFrom" : 0,
  "pageSize": 0,
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "limitResultsByStatus" : ["ACTIVE"],
  "sequencingOrder" : "PROPERTY_ASCENDING",
  "sequencingProperty" : "qualifiedName"
}

###
# @name getInfrastructureByCategory
# https://egeria-project.org/concepts/asset
# Returns the list of infrastructure assets matching the category and optional deployment status.
#
# @param serverName name of the service to route the request to
# @param urlMarker  view service URL marker
# @param requestBody string to find in the properties
#
# @return a list of infrastructure assets
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/infrastructure-assets/by-category
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeploymentStatusFilterRequestBody",
  "filter" : "xxx",
  "deploymentStatus" : "ACTIVE",
  "startFrom" : 0,
  "pageSize": 0,
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "limitResultsByStatus" : ["ACTIVE"],
  "sequencingOrder" : "PROPERTY_ASCENDING",
  "sequencingProperty" : "qualifiedName"
}

###

@infrastructureAssetGUID=add guid here
@destinationGUID=add guid here
@capabilityGUID=add guid here

###
# @name deployITAsset
# Create a relationship that represents the deployment of an IT infrastructure asset to a specific deployment destination (another asset).
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param assetGUID       unique identifier of the asset
# @param destinationGUID           unique identifier of the destination asset
# @param requestBody properties to help with the mapping of the elements in the external asset manager and open metadata
#
# @return  void or
# InvalidParameterException  one of the parameters is invalid
# UserNotAuthorizedException the user is not authorized to issue this request
# PropertyServerException    there is a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/assets/{{infrastructureAssetGUID}}/deployed-on/{{destinationGUID}}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "DeployedOnProperties",
    "deployer": "add name of actor",
    "deployerTypeName": "add type of actor",
    "deployerPropertyName": "add property of name of actor",
    "deploymentTime": "{{$isoTimestamp}}",
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name unDeployITAsset
# Remove a DeployedOn relationship.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param assetGUID       unique identifier of the asset
# @param destinationGUID           unique identifier of the destination asset
# @param requestBody properties to help with the mapping of the elements in the external asset manager and open metadata
#
# @return void or
# InvalidParameterException  one of the parameters is invalid
# UserNotAuthorizedException the user is not authorized to issue this request
# PropertyServerException    there is a problem reported in the open metadata server(s)
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/assets/{{infrastructureAssetGUID}}/deployed-on/{{destinationGUID}}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}
  
###
# @name linkSoftwareCapability
# Create a relationship that links a software capability to an infrastructure asset like a software server.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param assetGUID          unique identifier of the data set
# @param capabilityGUID          unique identifier of the data asset supplying the data
# @param requestBody properties to help with the mapping of the elements in the external asset manager and open metadata
#
# @return  void or
# InvalidParameterException  one of the parameters is invalid
# UserNotAuthorizedException the user is not authorized to issue this request
# PropertyServerException    there is a problem reported in the open metadata server(s)
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/assets/{{infrastructureAssetGUID}}/supported-software-capabilities/{{capabilityGUID}}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "SupportedSoftwareCapabilityProperties",
    "deployer": "add name of actor",
    "deployerTypeName": "add type of actor",
    "deployerPropertyName": "add property of name of actor",
    "deploymentTime": "{{$isoTimestamp}}",
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name detachSoftwareCapability
# Remove a relationship that links a software capability to an infrastructure asset like a software server.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param assetGUID          unique identifier of the data set
# @param capabilityGUID          unique identifier of the data asset supplying the data
# @param requestBody properties to help with the mapping of the elements in the external asset manager and open metadata
#
# @return void or
# InvalidParameterException  one of the parameters is invalid
# UserNotAuthorizedException the user is not authorized to issue this request
# PropertyServerException    there is a problem reported in the open metadata server(s)
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/assets/{{infrastructureAssetGUID}}/supported-software-capabilities/{{capabilityGUID}}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# =====================================================================================================================
# Data Assets include Files, Databases and APIs
#

###
# @name findDataAssets
# https://egeria-project.org/concepts/asset
# Returns the list of data assets matching the search string and optional content status.
#
# @param serverName name of the service to route the request to
# @param urlMarker  view service URL marker
# @param requestBody string to find in the properties
#
# @return a list of data assets
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/data-assets/by-search-string
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ContentStatusSearchString",
  "searchString" : "xxx",
  "contentStatus" : "ACTIVE",
  "startsWith" : false,
  "endsWith" : false,
  "ignoreCase" : true,
  "startFrom" : 0,
  "pageSize": 0,
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "limitResultsByStatus" : ["ACTIVE"],
  "sequencingOrder" : "PROPERTY_ASCENDING",
  "sequencingProperty" : "qualifiedName"
}

###
# @name getDataAssetsByCategory
# https://egeria-project.org/concepts/asset
# Returns the list of data assets matching the category and optional content status.
#
# @param serverName name of the service to route the request to
# @param urlMarker  view service URL marker
# @param requestBody string to find in the properties
#
# @return a list of data assets
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/data-assets/by-category
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ContentStatusFilterRequestBody",
  "filter" : "xxx",
  "contentStatus" : "ACTIVE",
  "startFrom" : 0,
  "pageSize": 0,
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "limitResultsByStatus" : ["ACTIVE"],
  "sequencingOrder" : "PROPERTY_ASCENDING",
  "sequencingProperty" : "qualifiedName"
}

###

@dataSetGUID=add guid here
@dataContentAssetGUID=get guid here

###
# @name linkDataSetContent
# Attach a data set to another asset (typically a data store) that is supplying the data.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param dataSetGUID          unique identifier of the data set
# @param dataContentAssetGUID          unique identifier of the data asset supplying the data
# @param requestBody properties to help with the mapping of the elements in the external asset manager and open metadata
#
# @return  void or
# InvalidParameterException  one of the parameters is invalid
# UserNotAuthorizedException the user is not authorized to issue this request
# PropertyServerException    there is a problem reported in the open metadata server(s)
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/data-sets/{{dataSetGUID}}/data-set-content/{{dataContentAssetGUID}}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "DataSetContentProperties",
    "queryId": "add id that is used on overall formula",
    "query": "add query",
    "queryType": "add query type",
    "iscQualifiedName": "add qualified name",
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name detachDataSetContent
# Detach a data set from another asset that was supplying the data and is no more.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param dataSetGUID          unique identifier of the data set
# @param dataContentAssetGUID          unique identifier of the data asset supplying the data
# @param requestBody properties to help with the mapping of the elements in the external asset manager and open metadata
#
# @return void or
# InvalidParameterException  one of the parameters is invalid
# UserNotAuthorizedException the user is not authorized to issue this request
# PropertyServerException    there is a problem reported in the open metadata server(s)
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/data-sets/{{dataSetGUID}}/data-set-content/{{dataContentAssetGUID}}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# =====================================================================================================================
# A catalog target links an element (typically an asset) to an integration connector for processing.
#

@integrationConnectorGUID=fa1f711c-0b34-4b57-8e6e-16162b132b0c
@metadataElementGUID=add guid here
@relationshipGUID=add guid here

###
# @name addCatalogTarget
# Add a catalog target to an integration connector.
# Further Information: https://egeria-project.org/concepts/integration-connector/
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/automated-curation/integration-connectors/{{integrationConnectorGUID}}/catalog-targets/{{metadataElementGUID}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "properties": {
    "class": "CatalogTargetProperties",
    "catalogTargetName" : "Freddy",
    "metadataSourceQualifiedName" : "",
    "templates" : {
       "templateName1" : "template1GUID",
       "templateName2" : "template2GUID"
    },
    "configurationProperties" : {
      "propertyName1" : "propertyValue1",
      "propertyName2" : "propertyValue2"
    },
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  }
}


###
# Full catalog target properties
#{
#    "class": "CatalogTargetProperties",
#    "catalogTargetName" : "",
#    "metadataSourceQualifiedName" : "",
#    "templates" : {
#        "templateName1" : "template1GUID",
#        "templateName2" : "template2GUID"
#    },
#    "configurationProperties" : {
#        "propertyName1" : "propertyValue1",
#        "propertyName2" : "propertyValue2"
#    }
#}


###
# @name updateCatalogTarget
# Update a catalog target for an integration connector.
# Further Information: https://egeria-project.org/concepts/integration-connector/
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/automated-curation/catalog-targets/{{relationshipGUID}}/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "UpdateRelationshipRequestBody",
  "properties" : {
    "class": "CatalogTargetProperties",
    "catalogTargetName" : "Freddy",
    "metadataSourceQualifiedName" : "",
    "templates" : {
       "templateName1" : "template1GUID",
       "templateName2" : "template2GUID"
    },
    "configurationProperties" : {
      "propertyName1" : "propertyValue1",
      "propertyName2" : "propertyValue2"
    }
  },
  "mergeUpdate": true,
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name getCatalogTarget
# Retrieve a specific catalog target associated with an integration connector.
# Further Information: https://egeria-project.org/concepts/integration-connector/
GET {{baseURL}}/servers/{{viewServer}}/api/open-metadata/automated-curation/catalog-targets/{{relationshipGUID}}
Authorization: Bearer {{token}}
Content-Type: application/json


###
# @name getCatalogTargets
# Retrieve the details of the metadata elements identified as catalog targets with an integration connector.
# Further Information: https://egeria-project.org/concepts/integration-connector/
GET {{baseURL}}/servers/{{viewServer}}/api/open-metadata/automated-curation/integration-connectors/{{integrationConnectorGUID}}/catalog-targets?startFrom=0&pageSize=0
Authorization: Bearer {{token}}
Content-Type: application/json


###
# @name removeCatalogTarget
# Unregister a catalog target from the integration connector.
# Further Information: https://egeria-project.org/concepts/integration-connector/
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/automated-curation/catalog-targets/{{relationshipGUID}}/remove
Authorization: Bearer {{token}}
Content-Type: application/json

