# Egeria-InMemoryRepository

###
# @name configure event bus
POST {{baseURL}}/open-metadata/admin-services/users/{{user}}/servers/{{server}}/event-bus
Authorization: Basic admin admin
X-XSRF-HEADER: valid
Content-Type: application/json

{
"producer":
{
"bootstrap.servers":"{{kafkaep}}",
"acks":"all",
"retries":"0",
"batch.size":"16384",
"linger.ms":"1",
"buffer.memory":"33554432",
"max.request.size":"10485760",
"key.serializer":"org.apache.kafka.common.serialization.StringSerializer",
"value.serializer":"org.apache.kafka.common.serialization.StringSerializer",
"kafka.omrs.topic.id":"{{cohort}}"
},
"consumer":
{
"bootstrap.servers":"{{kafkaep}}",
"zookeeper.session.timeout.ms":"400",
"zookeeper.sync.time.ms":"200",
"fetch.message.max.bytes":"10485760",
"max.partition.fetch.bytes":"10485760",
"key.deserializer":"org.apache.kafka.common.serialization.StringDeserializer",
"value.deserializer":"org.apache.kafka.common.serialization.StringDeserializer",
"kafka.omrs.topic.id":"{{cohort}}"
}
}



###
# @name Enable the access services
# Query Current Configuration
POST {{baseURL}}/open-metadata/admin-services/users/{{user}}/servers/{{server}}/access-services?
    serviceMode=ENABLED

###
# @name Cohort configuration
POST {{baseURL}}/open-metadata/admin-services/users/{{user}}/servers/{{server}}/cohorts/{{cohort}}
User-Agent: Mozzzzz
Authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/json

{
"producer":
{
"bootstrap.servers":"{{kafkaep}}",
"acks":"all",
"retries":"0",
"batch.size":"16384",
"linger.ms":"1",
"buffer.memory":"33554432",
"max.request.size":"10485760",
"key.serializer":"org.apache.kafka.common.serialization.StringSerializer",
"value.serializer":"org.apache.kafka.common.serialization.StringSerializer",
"kafka.omrs.topic.id":"{{cohort}}"
},
"consumer":
{
"bootstrap.servers":"{{kafkaep}}",
"zookeeper.session.timeout.ms":"400",
"zookeeper.sync.time.ms":"200",
"fetch.message.max.bytes":"10485760",
"max.partition.fetch.bytes":"10485760",
"key.deserializer":"org.apache.kafka.common.serialization.StringDeserializer",
"value.deserializer":"org.apache.kafka.common.serialization.StringDeserializer",
"kafka.omrs.topic.id":"{{cohort}}"
}
}



###
# @name Set local server mode - inmemory
# Query Current Configuration
POST {{baseURL}}/open-metadata/admin-services/users/{{user}}/servers/{{server}}/local-repository/mode/in-memory-repository

###
# @name Start Server using config
# Query Current Configuration
POST {{baseURL}}/open-metadata/admin-services/users/{{user}}/servers/{{server}}/instance

###
# @name Query Configuration
# Query Current Configuration
GET {{baseURL}}/open-metadata/admin-services/users/{{user}}/servers/{{server}}/configuration/
Authorization: Basic admin admin