/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright Contributors to the ODPi Egeria project. */

package org.odpi.openmetadata.accessservices.informationview.utils;

public class Constants {


    public static final String INFORMATION_VIEW_OMAS_NAME = "InformationViewOmas";
    public static final String INFORMATION_VIEW = "InformationView";
    public static final String RELATIONAL_TABLE = "RelationalTable";
    public static final String RELATIONAL_COLUMN = "RelationalColumn";
    public static final String BUSINESS_TERM = "GlossaryTerm";
    public static final String RELATIONAL_DB_SCHEMA_TYPE = "RelationalDBSchemaType";
    public static final String DERIVED_RELATIONAL_COLUMN = "DerivedRelationalColumn";
    public static final String DERIVED_SCHEMA_ATTRIBUTE = "DerivedSchemaAttributeProperties";
    public static final String DATA_STORE = "DataStoreProperties";
    public static final String QUALIFIED_NAME = "qualifiedName";
    public static final String OWNER = "owner";
    public static final String DESCRIPTION = "description";
    public static final String ATTRIBUTE_FOR_SCHEMA = "AttributeForSchema";
    public static final String SCHEMA_ATTRIBUTE_TYPE = "SchemaAttributeType";
    public static final String CONNECTION_TO_ASSET = "ConnectionToAsset";
    public static final String DATA_CONTENT_FOR_DATASET = "DataContentForDataSet";
    public static final String CONNECTION_TO_ENDPOINT = "ConnectionEndpoint";
    public static final String ASSET_SCHEMA_TYPE = "AssetSchemaType";
    public static final String ASSET = "Asset";
    public static final String NAME = "name";
    public static final String ATTRIBUTE_NAME = "name";
    public static final String DISPLAY_NAME = "displayName";
    public static final String AUTHOR = "author";
    public static final String USAGE = "usage";
    public static final String SUMMARY = "summary";
    public static final String ABBREVIATION = "abbreviation";
    public static final String ENCODING_STANDARD = "encodingStandard";
    public static final String DATA_TYPE = "dataType";
    public static final String ELEMENT_POSITION_NAME = "position";
    public static final String IS_NULLABLE = "isNullable";
    public static final String IS_UNIQUE = "isUnique";
    public static final String QUERY = "query";
    public static final String FORMULA = "formula";
    public static final String INFO_VIEW_PREFIX = "iv_";
    public static final String TYPE_SUFFIX = "_type";
    public static final String CONNECTION_CONNECTOR_TYPE = "ConnectionConnectorType";
    public static final String RELATIONAL_COLUMN_TYPE = "RelationalColumnType";
    public static final String SCHEMA_QUERY_IMPLEMENTATION = "SchemaQueryImplementation";
    public static final String SEMANTIC_ASSIGNMENT = "SemanticAssignment";
    public static final String RELATIONAL_TABLE_TYPE = "RelationalTableType";
    public static final String URL = "url";
    public static final String EXAMPLES = "examples";
    public static final String PROTOCOL = "protocol";
    public static final String ENCRYPTION_METHOD = "encryptionMethod";
    public static final String NETWORK_ADDRESS = "networkAddress";
    public static final String ADDITIONAL_PROPERTIES = "additionalProperties";
    public static final String CONNECTOR_PROVIDER_CLASSNAME = "connectorProviderClassName";
    public static final String GAIAN_DB_NODE_NAME = "GDName";
    public static final String INFORMATION_VIEW_USER_ID = "informationViewOmas";
    public static final String CONNECTOR_TYPE = "ConnectorType";
    public static final String DEPLOYED_DATABASE_SCHEMA = "DeployedDatabaseSchema";
    public static final String ENDPOINT = "Endpoint";
    public static final String CONNECTION = "Connection";
    public static final String SOFTWARE_SERVER = "SoftwareServer";
    public static final String DATABASE_SERVER = "DatabaseServer";
    public static final String SERVER_ENDPOINT = "ServerEndpoint";
    public static final String SOFTWARE_SERVER_CAPABILITY = "SoftwareServerCapability";
    public static final String ENGINE = "Engine";
    public static final String REPORTING_ENGINE = "ReportingEngine";
    public static final String PRIMARY_KEY = "PrimaryKey";
    public static final String FOREIGN_KEY = "ForeignKey";
    public static final String DEPLOYED_REPORT = "DeployedReport";
    public static final String ID = "id";
    public static final String DOCUMENT_SCHEMA_TYPE = "DocumentSchemaType";
    public static final String DOCUMENT_SCHEMA_ATTRIBUTE = "DocumentSchemaAttribute";
    public static final String COMPLEX_SCHEMA_TYPE = "ComplexSchemaType";
    public static final String LAST_MODIFIER = "lastModifier";
    public static final String LAST_MODIFIED_TIME = "lastModifiedTime";
    public static final String CREATE_TIME = "createdTime";
    public static final String SCHEMA_ATTRIBUTE = "SchemaAttribute";
    public static final String SCHEMA_TYPE = "SchemaType";
    public static final String NATIVE_CLASS = "nativeClass";
    public static final String AGGREGATING_FUNCTION = "aggregatingFunction";
    public static final String COMMENT = "comment";
    public static final String PRIMITIVE_SCHEMA_TYPE = "PrimitiveSchemaType";
    public static final String ZONE_MEMBERSHIP = "zoneMembership";
    public static final Integer PAGE_SIZE = 100;
    public static final int START_FROM = 0;
    public static final String GUID = "guid";
    public static final String TYPE = "type";
    public static final String VERSION = "version";
    public static final String PATCH_LEVEL = "patchLevel";
    public static final String SOURCE = "source";
    public static final String USER_ID = "userId";
    public static final String OWNER_TYPE = "ownerType";
    public static final String DATABASE = "Database";
}
