# Egeria-baudot-subscription-requests
## Locate the types of subscriptions available for a digital product

@baseURL=https://localhost:7443
@viewServer=view-server

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "peterprofile",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}

###
# =====================================================================================================================
# Retrieve the profile of the subscriber
# https://egeria-project.org/concepts/governance-action-process


###
# @name getActorProfilesByName
# Returns the list of actor profiles with a particular name.
#
# Request body provides string to find in the properties
#
# Returns list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/actor-manager/actor-profiles/by-name
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "FilterRequestBody",
  "filter" : "Callie Quartile",
  "startFrom": 0,
  "pageSize": 10
}

> {% client.global.set("callieQuartileProfileGUID", response.body.elements[0].elementHeader.guid); %}

###
# =====================================================================================================================
# Initiate the create evaluation subscription
# https://egeria-project.org/concepts/governance-action-process


###
# @name initiateGovernanceActionProcess (Create Evaluation Subscription for Valid Metadata Value Sets List)
# Using the named governance action process as a template, initiate a chain of engine actions.

POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/automated-curation/governance-action-processes/initiate
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "processQualifiedName": "GovernanceActionProcess::Valid Metadata Value Set List::Create Subscription::EVALUATION-SUBSCRIPTION",
  "actionTargets": [
     {
       "class" : "NewActionTarget",
       "actionTargetName" : "digitalSubscriptionRequester",
       "actionTargetGUID" : "{{callieQuartileProfileGUID}}"
     },
     {
       "class" : "NewActionTarget",
       "actionTargetName" : "destinationDataSet",
       "actionTargetGUID" : "{{csvFileTabularDataSetGUID}}"
     }]
 }

###
# ================================================
# Engine actions are Assets and standard queries are available through
# Asset Maker OMVS.  These are the special requests provided by Automated Curation OMVS

@engineActionGUID=add guid here

###
# @name cancelEngineAction
# Request that an engine action request is cancelled and any running governance service is stopped.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/automated-curation/engine-actions/{{engineActionGUID}}/cancel
Authorization: Bearer {{token}}


###
# @name getActiveEngineActions
# Retrieve the engine actions that are still in process.
GET {{baseURL}}/servers/{{viewServer}}/api/open-metadata/automated-curation/engine-actions/active?startFrom=0&pageSize=0
Authorization: Bearer {{token}}









