# Egeria-notification-types-and-actions
## Egeria's Notification Manager API
## Egeria's Notification Manager API
## Sets up the definitions of the resources to monitor and the subscribers to receive notifications from.

@baseURL=https://localhost:9443
@viewServer=view-server

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "peterprofile",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}


###
# =====================================================================================================================
# Work with Notification Types
# https://egeria-project.org/concepts/notification-type

@notificationTypeGUID=add guid here
@monitoredResourceGUID=add guid here
@subscriberGUID=add guid here

###
# @name findNotificationTypes
# Retrieve the list of governance definition metadata elements that contain the search string.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/notification-manager/governance-definitions/by-search-string
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "SearchStringRequestBody",
  "metadataElementTypeName": "NotificationType",
  "startsWith" : false,
  "endsWith" : false,
  "ignoreCase" : true,
  "startFrom" : 0,
  "pageSize": 0
}

###
# @name linkMonitoredResource
# Attach a monitored resource to a notification type.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/notification-manager/notification-types/{{notificationTypeGUID}}/monitored-resources/{{monitoredResourceGUID}}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "MonitoredResourceProperties",
    "label" : "",
    "description" : "",
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###

# @name detachMonitoredResource
# Detach a monitored resource from a notification type.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/notification-manager/notification-types/{{notificationTypeGUID}}/monitored-resources/{{monitoredResourceGUID}}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name linkNotificationSubscriber
# Attach a subscriber to a notification type.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/notification-manager/notification-types/{{notificationTypeGUID}}/notification-subscribers/{{subscriberGUID}}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "MonitoredResourceProperties",
    "label" : "",
    "description" : "",
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###

# @name detachNotificationSubscriber
# Detach a subscriber from a notification type.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/notification-manager/notification-types/{{notificationTypeGUID}}/notification-subscribers/{{subscriberGUID}}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}




