# Egeria-schema-maker-api
# The Schema Maker OMVS provides APIs for supporting the creation and editing of schema types and
# schema attributes.

@baseURL=https://localhost:7443
@viewServer=view-server

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "peterprofile",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}


###
# =====================================================================================================================
# Work with Schema Elements
# https://egeria-project.org/concepts/schema-type

@schemaTypeGUID=add guid here


###
# @name createSchemaType
# Create a schema type.
#
# Request body provides             properties for the schema type.
#
# Returns unique identifier of the newly created element
#  InvalidParameterException  one of the parameters is invalid.
#  PropertyServerException    a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-types
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewElementRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "anchorGUID" : "add guid here",
  "isOwnAnchor": false,
  "parentGUID": "add guid here",
  "parentRelationshipTypeName": "add type name here",
  "parentRelationshipProperties": {
    "class": "RelationshipElementProperties",
    "propertyValueMap" : {
      "description" : {
        "class": "PrimitiveTypePropertyValue",
        "typeName": "string",
        "primitiveValue" : "New description"
      }
    }
  },
  "parentAtEnd1": false,
  "properties": {
    "class" : "SchemaTypeProperties",
    "typeName" : "enter the type of the element",
    "qualifiedName": "add unique name here",
    "displayName": "add short name here",
    "description": "add description here",
    "additionalProperties": {
      "property1" : "propertyValue1",
      "property2" : "propertyValue2"
    },
    "extendedProperties": {
      "property1" : "propertyValue1",
      "property2" : "propertyValue2"
    },
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  }
}


###
# @name createSchemaTypeFromTemplate
# Create a new metadata element to represent a schema type using an existing metadata element as a template.
# The template defines additional classifications and relationships that should be added to the new element.
#
# Request body provides properties that override the template
#
# Returns unique identifier of the new metadata element
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-types/from-template
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "TemplateRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "anchorGUID" : "add guid here",
  "isOwnAnchor": false,
  "parentGUID": "add guid here",
  "parentRelationshipTypeName": "add type name here",
  "parentRelationshipProperties": {
    "class": "RelationshipElementProperties",
    "propertyValueMap" : {
      "description" : {
        "class": "PrimitiveTypePropertyValue",
        "typeName": "string",
        "primitiveValue" : "New description"
      }
    }
  },
  "parentAtEnd1": false,
  "templateGUID": "add guid here",
  "replacementProperties": {
    "class": "EntityElementProperties",
    "propertyValueMap" : {
      "description" : {
        "class": "PrimitiveTypePropertyValue",
        "typeName": "string",
        "primitiveValue" : "New description"
      }
    }
  },
  "placeholderPropertyValues":  {
    "placeholder1" : "propertyValue1",
    "placeholder2" : "propertyValue2"
  }
}


###
# @name updateSchemaType
# Update the properties of a schema type.
#
# @param schemaTypeGUID unique identifier of the schema type (returned from create)
# Request body provides     properties for the new element.
#
# Returns void or
#  InvalidParameterException  one of the parameters is invalid.
#  PropertyServerException    a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-types/{{schemaTypeGUID}}/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "UpdateElementRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "properties": {
    "class" : "SchemaTypeProperties",
    "typeName" : "enter the type of the element",
    "qualifiedName": "add unique name here",
    "displayName": "add short name here",
    "description": "add description here",
    "additionalProperties": {
      "property1" : "propertyValue1",
      "property2" : "propertyValue2"
    },
    "extendedProperties": {
      "property1" : "propertyValue1",
      "property2" : "propertyValue2"
    },
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  }
}


###
# @name deleteSchemaType
# Delete a schema type.
#
# @param schemaTypeGUID  unique identifier of the element to delete
# Request body provides  description of the relationship.
#
# Returns void or
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-types/{{schemaTypeGUID}}/delete
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "MetadataSourceRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name getSchemaTypesByName
# Returns the list of schema types with a particular name.
#
# Request body provides string to find in the properties
#
# Returns list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-types/by-name
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "FilterRequestBody",
  "filter" : "Add name here",
  "startFrom": 0,
  "pageSize": 10,
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "limitResultsByStatus" : ["ACTIVE"],
  "sequencingOrder" : "PROPERTY_ASCENDING",
  "sequencingProperty" : "qualifiedName"
}


###
# @name findSchemaTypes
# Retrieve the list of schema type metadata elements that contain the search string.
#
# Request body provides string to find in the properties
#
# Returns list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-types/by-search-string
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "SearchStringRequestBody",
  "searchString": "xxx",
  "startsWith" : false,
  "endsWith" : false,
  "ignoreCase" : true,
  "startFrom" : 0,
  "pageSize": 0,
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "limitResultsByStatus" : ["ACTIVE"],
  "sequencingOrder" : "PROPERTY_ASCENDING",
  "sequencingProperty" : "qualifiedName"
}


###
# @name getSchemaTypeByGUID
# Return the properties of a specific schema type.
#
# @param schemaTypeGUID    unique identifier of the required element
# Request body provides string to find in the properties
#
# Returns list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-types/{{schemaTypeGUID}}/retrieve
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "GetRequestBody",
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name createSchemaAttribute
# Create a schema attribute.
#
# Request body provides             properties for the schema attribute.
#
# Returns unique identifier of the newly created element
#  InvalidParameterException  one of the parameters is invalid.
#  PropertyServerException    a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-attributes
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewElementRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "anchorGUID" : "add guid here",
  "isOwnAnchor": false,
  "parentGUID": "add guid here",
  "parentRelationshipTypeName": "add type name here",
  "parentRelationshipProperties": {
    "class": "RelationshipElementProperties",
    "propertyValueMap" : {
      "description" : {
        "class": "PrimitiveTypePropertyValue",
        "typeName": "string",
        "primitiveValue" : "New description"
      }
    }
  },
  "parentAtEnd1": false,
  "properties": {
    "class" : "SchemaAttributeProperties",
    "typeName" : "enter the type of the element",
    "qualifiedName": "add unique name here",
    "displayName":"add name here",
    "identifier": "add name here",
    "description": "add description here",
    "scope": "add scope here",
    "additionalProperties": {
      "property1" : "propertyValue1",
      "property2" : "propertyValue2"
    },
    "extendedProperties": {
      "property1" : "propertyValue1",
      "property2" : "propertyValue2"
    },
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  }
}


###
# @name createSchemaAttributeFromTemplate
# Create a new metadata element to represent a schema attribute using an existing metadata element as a template.
# The template defines additional classifications and relationships that should be added to the new element.
#
# Request body provides properties that override the template
#
# Returns unique identifier of the new metadata element
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-attributes/from-template
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "TemplateRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "anchorGUID" : "add guid here",
  "isOwnAnchor": false,
  "parentGUID": "add guid here",
  "parentRelationshipTypeName": "add type name here",
  "parentRelationshipProperties": {
    "class": "RelationshipElementProperties",
    "propertyValueMap" : {
      "description" : {
        "class": "PrimitiveTypePropertyValue",
        "typeName": "string",
        "primitiveValue" : "New description"
      }
    }
  },
  "parentAtEnd1": false,
  "templateGUID": "add guid here",
  "replacementProperties": {
    "class": "EntityElementProperties",
    "propertyValueMap" : {
      "description" : {
        "class": "PrimitiveTypePropertyValue",
        "typeName": "string",
        "primitiveValue" : "New description"
      }
    }
  },
  "placeholderPropertyValues":  {
    "placeholder1" : "propertyValue1",
    "placeholder2" : "propertyValue2"
  }
}


###
# @name updateSchemaAttribute
# Update the properties of a schema attribute.
#
# @param schemaAttributeGUID unique identifier of the schema attribute (returned from create)
# Request body provides     properties for the new element.
#
# Returns void or
#  InvalidParameterException  one of the parameters is invalid.
#  PropertyServerException    a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-attributes/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "UpdateElementRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "properties": {
    "class" : "SchemaAttributeProperties",
    "typeName" : "enter the type of the element",
    "qualifiedName": "add unique name here",
    "displayName":"add name here",
    "identifier": "add name here",
    "description": "add description here",
    "scope": "add scope here",
    "additionalProperties": {
      "property1" : "propertyValue1",
      "property2" : "propertyValue2"
    },
    "extendedProperties": {
      "property1" : "propertyValue1",
      "property2" : "propertyValue2"
    },
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  }
}




###
# @name deleteSchemaAttribute
# Delete a schema attribute.
#
# @param schemaAttributeGUID  unique identifier of the element to delete
# Request body provides  description of the relationship.
#
# Returns void or
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-attributes/delete
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "MetadataSourceRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name getSchemaAttributesByName
# Returns the list of schema attributes with a particular name.
#
# Request body provides string to find in the properties
#
# Returns list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-attributes/by-name
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "FilterRequestBody",
  "filter" : "Add name here",
  "startFrom": 0,
  "pageSize": 10,
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "limitResultsByStatus" : ["ACTIVE"],
  "sequencingOrder" : "PROPERTY_ASCENDING",
  "sequencingProperty" : "qualifiedName"
}


###
# @name findSchemaAttributes
# Retrieve the list of schema attribute metadata elements that contain the search string.
#
# Request body provides string to find in the properties
#
# Returns list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-attributes/by-search-string
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "SearchStringRequestBody",
  "searchString": "xxx",
  "startsWith" : false,
  "endsWith" : false,
  "ignoreCase" : true,
  "startFrom" : 0,
  "pageSize": 0,
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "limitResultsByStatus" : ["ACTIVE"],
  "sequencingOrder" : "PROPERTY_ASCENDING",
  "sequencingProperty" : "qualifiedName"
}


###
# @name getSchemaAttributeByGUID
# Return the properties of a specific schema attribute.
#
# @param schemaAttributeGUID    unique identifier of the required element
# Request body provides string to find in the properties
#
# Returns list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-attributes/{{schemaAttributeGUID}}/retrieve"})
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "GetRequestBody",
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# =====================================================================================================================
# Schema element relationships

###
# @name linkNestedSchemaAttribute
# Attach a nested schema attribute to its parent schema attribute.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param schemaAttributeGUID unique identifier of the parent schema attribute
# @param nestedSchemaAttributeGUID unique identifier of the nested schema attribute
# @param requestBody properties for the relationship
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-attributes/{{schemaAttributeGUID}}/nested-schema-attributes/{{nestedSchemaAttributeGUID}}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "NestedSchemaAttributeProperties",
    "position": 0,
    "minCardinality": 0,
    "maxCardinality": 1,
    "coverageCategory": "CORE_DETAIL",
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name detachNestedSchemaAttribute
# Detach a nested schema attribute from its parent schema attribute.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param schemaAttributeGUID unique identifier of the parent schema attribute
# @param nestedSchemaAttributeGUID unique identifier of the nested schema attribute
# @param requestBody delete options
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-attributes/{{schemaAttributeGUID}}/nested-schema-attributes/{{nestedSchemaAttributeGUID}}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name linkAttributeForSchema
# Attach a schema attribute to the schema type that it belongs to.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param schemaTypeGUID unique identifier of the schema type
# @param nestedSchemaAttributeGUID unique identifier of the schema attribute
# @param requestBody properties for the relationship
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-types/{{schemaTypeGUID}}/attribute-for-schema/{{nestedSchemaAttributeGUID}}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "AttributeForSchemaProperties",
    "position": 0,
    "minCardinality": 0,
    "maxCardinality": 1,
    "coverageCategory": "CORE_DETAIL",
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name detachAttributeForSchema
# Detach a schema attribute from the schema type that it belongs to.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param schemaTypeGUID unique identifier of the schema type
# @param nestedSchemaAttributeGUID unique identifier of the schema attribute
# @param requestBody delete options
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-types/{{schemaTypeGUID}}/attribute-for-schema/{{nestedSchemaAttributeGUID}}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name linkForeignKey
# Attach a foreign key column to the primary key column that it refers to.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param primaryKeyColumnGUID unique identifier of the primary key column
# @param foreignKeyColumnGUID unique identifier of the foreign key column
# @param requestBody properties for the relationship
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-attributes/{{primaryKeyColumnGUID}}/foreign-keys/{{foreignKeyColumnGUID}}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "ForeignKeyProperties",
    "displayName": "add display name",
    "description": "add description",
    "confidence": 100,
    "steward": "add steward name",
    "source": "add source",
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name detachForeignKey
# Detach a foreign key column from the primary key column that it refers to.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param primaryKeyColumnGUID unique identifier of the primary key column
# @param foreignKeyColumnGUID unique identifier of the foreign key column
# @param requestBody delete options
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-attributes/{{primaryKeyColumnGUID}}/foreign-keys/{{foreignKeyColumnGUID}}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name linkExternalSchemaType
# Attach an external schema type to the schema element that uses it.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param schemaElementGUID unique identifier of the schema element
# @param schemaTypeGUID unique identifier of the external schema type
# @param requestBody properties for the relationship
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-elements/{{schemaElementGUID}}/linked-external-schema-types/{{schemaTypeGUID}}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "LinkedExternalSchemaTypeProperties",
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name detachExternalSchemaType
# Detach an external schema type from the schema element that uses it.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param schemaElementGUID unique identifier of the schema element
# @param schemaTypeGUID unique identifier of the external schema type
# @param requestBody delete options
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-elements/{{schemaElementGUID}}/linked-external-schema-types/{{schemaTypeGUID}}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name linkMapFromSchemaType
# Attach the schema type that describes the domain (from) element of a map.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param schemaElementGUID unique identifier of the map schema element
# @param schemaTypeGUID unique identifier of the schema type describing the domain of the map
# @param requestBody properties for the relationship
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-elements/{{schemaElementGUID}}/map-from-element-types/{{schemaTypeGUID}}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "MapFromElementTypeProperties",
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name detachMapFromSchemaType
# Detach the schema type that describes the domain (from) element of a map.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param schemaElementGUID unique identifier of the map schema element
# @param schemaTypeGUID unique identifier of the schema type describing the domain of the map
# @param requestBody delete options
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-elements/{{schemaElementGUID}}/map-from-element-types/{{schemaTypeGUID}}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name linkMapToSchemaType
# Attach the schema type that describes the range (to) element of a map.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param schemaElementGUID unique identifier of the map schema element
# @param schemaTypeGUID unique identifier of the schema type describing the range of the map
# @param requestBody properties for the relationship
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-elements/{{schemaElementGUID}}/map-to-element-types/{{schemaTypeGUID}}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "MapToElementTypeProperties",
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name detachMapToSchemaType
# Detach the schema type that describes the range (to) element of a map.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param schemaElementGUID unique identifier of the map schema element
# @param schemaTypeGUID unique identifier of the schema type describing the range of the map
# @param requestBody delete options
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-elements/{{schemaElementGUID}}/map-to-element-types/{{schemaTypeGUID}}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name linkGraphEdge
# Attach a graph edge to one of the graph vertices that it connects.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param graphEdgeGUID unique identifier of the graph edge
# @param graphVertexGUID unique identifier of the graph vertex
# @param requestBody properties for the relationship
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/graph-edges/{{graphEdgeGUID}}/graph-vertices/{{graphVertexGUID}}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "GraphEdgeLinkProperties",
    "linkTypeName": "add link type name",
    "relationshipEnd": 1,
    "relationshipEndName": "add end name",
    "description": "add description",
    "minCardinality": 0,
    "maxCardinality": 1,
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name detachGraphEdge
# Detach a graph edge from one of the graph vertices that it connects.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param graphEdgeGUID unique identifier of the graph edge
# @param graphVertexGUID unique identifier of the graph vertex
# @param requestBody delete options
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/graph-edges/{{graphEdgeGUID}}/graph-vertices/{{graphVertexGUID}}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name linkQueryTarget
# Attach a query target to the derived schema element that queries it.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param schemaElementGUID unique identifier of the derived schema element
# @param queryTargetSchemaElementGUID unique identifier of the schema element supplying the query target
# @param requestBody properties for the relationship
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-elements/{{schemaElementGUID}}/query-targets/{{queryTargetSchemaElementGUID}}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "DerivedSchemaTypeQueryTargetProperties",
    "queryId": "add id that is used on the overall formula",
    "query": "add query",
    "queryType": "add query type",
    "iscQualifiedName": "add information supply chain qualified name",
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name detachQueryTarget
# Detach a query target from the derived schema element that queries it.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param schemaElementGUID unique identifier of the derived schema element
# @param queryTargetSchemaElementGUID unique identifier of the schema element supplying the query target
# @param requestBody delete options
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/schema-elements/{{schemaElementGUID}}/query-targets/{{queryTargetSchemaElementGUID}}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name linkSchema
# Attach a schema type to the element that it describes.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param elementGUID unique identifier of the element that is described by the schema type
# @param schemaTypeGUID unique identifier of the schema type
# @param requestBody properties for the relationship
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/elements/{{elementGUID}}/schema-types/{{schemaTypeGUID}}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "SchemaProperties",
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name detachSchema
# Detach a schema type from the element that it describes.
#
# @param serverName name of the server to route the request to
# @param urlMarker  view service URL marker
# @param elementGUID unique identifier of the element that is described by the schema type
# @param schemaTypeGUID unique identifier of the schema type
# @param requestBody delete options
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/elements/{{elementGUID}}/schema-types/{{schemaTypeGUID}}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# =====================================================================================================================
# Relational database schema relationships
# https://egeria-project.org/concepts/schema-type

@databaseSchemaTypeListGUID=add guid here
@relationalDBSchemaTypeGUID=add guid here

###
# @name linkRelationalDBSchema
# Attach a relational database schema type to the list that contains it.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/relational-db-schema-type-lists/{{databaseSchemaTypeListGUID}}/relational-db-schemas/{{relationalDBSchemaTypeGUID}}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "RelationalDBSchemaProperties",
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name detachRelationalDBSchema
# Detach a relational database schema type from the list that contained it.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/schema-maker/relational-db-schema-type-lists/{{databaseSchemaTypeListGUID}}/relational-db-schemas/{{relationalDBSchemaTypeGUID}}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}
