# Setting up the sample servers: active-metadata-store, integration-daemon, engine-host, view-server for monitoring.

@adminUserId=garygeeke
@user=garygeeke
@kafkaep=localhost:9092

@baseURL=https://localhost:9443
@nannyAuditLogTopic=logging


###
# Add topic audit log destination to active-metadata-store server
POST {{baseURL}}/open-metadata/admin-services/users/{{adminUserId}}/servers/active-metadata-store/audit-log-destinations/event-topic?
    topicName={{nannyAuditLogTopic}}
Content-Type: application/json

[]


###
# Set up event bus in engine-host server
POST {{baseURL}}/open-metadata/admin-services/users/{{adminUserId}}/servers/engine-host/event-bus
Content-Type: application/json

{
    "producer": {
        "bootstrap.servers": "{{kafkaep}}"
    },
    "consumer":{
        "bootstrap.servers": "{{kafkaep}}"
    }
}

###
# Add topic audit log destination to engine-host server
POST {{baseURL}}/open-metadata/admin-services/users/{{adminUserId}}/servers/engine-host/audit-log-destinations/event-topic?
    topicName={{nannyAuditLogTopic}}
Content-Type: application/json

[]



###
# Set up event bus in integration-daemon server
POST {{baseURL}}/open-metadata/admin-services/users/{{adminUserId}}/servers/integration-daemon/event-bus
Content-Type: application/json

{
    "producer": {
        "bootstrap.servers": "{{kafkaep}}"
    },
    "consumer":{
        "bootstrap.servers": "{{kafkaep}}"
    }
}

###
# Add topic audit log destination to integration-daemon server
POST {{baseURL}}/open-metadata/admin-services/users/{{adminUserId}}/servers/integration-daemon/audit-log-destinations/event-topic?
    topicName={{nannyAuditLogTopic}}
Content-Type: application/json

[]


###
# Set up event bus in view-server server
POST {{baseURL}}/open-metadata/admin-services/users/{{adminUserId}}/servers/view-server/event-bus
Content-Type: application/json

{
    "producer": {
        "bootstrap.servers": "{{kafkaep}}"
    },
    "consumer":{
        "bootstrap.servers": "{{kafkaep}}"
    }
}

###
# Add topic audit log destination to view-server server
POST {{baseURL}}/open-metadata/admin-services/users/{{adminUserId}}/servers/view-server/audit-log-destinations/event-topic?
    topicName={{nannyAuditLogTopic}}
Content-Type: application/json

[]

