# Egeria-subject-area-omas

###
# @name Create Glossary
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/subject-area/users/{{user}}/glossaries
Content-Type: application/json

{
    "class" : "Glossary",
    "qualifiedName" : "glossaryTime",
    "name" : "XY",
    "effectiveFromTime" : 77777777,
    "effectiveToTime" : 88888888
}

###
# @name Update Glossary
PUT {{baseURL}}/servers/{{server}}/open-metadata/access-services/subject-area/users/{{user}}/glossaries/{{glossaryGUID}}
Content-Type: application/json

{
    "class" : "Glossary",
    "qualifiedName" : "glossaryTime",
    "name" : "XY",
    "effectiveFromTime" : 77777777,
    "effectiveToTime" : 9999999999
}

###
# @name Create Term
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/subject-area/users/{{user}}/terms
Content-Type: application/json

{
    "class" : "Term",
    "qualifiedName" : "termXXXX2",
    "name" : "X",
    "glossary" : 
        {
            "class" : "GlossarySummary",
            "guid" : "01723297-dfc0-4ca6-a81b-29e6e385252e"
        }
}