# Egeria-governance-engine-omas

###
# @name Get Governance Action
# Asset is the top level type definition for an asset.  The type system also defines many more specialized types for Asset.  This requests lists the names of all of these specialized types found in the open metadata ecosystem that this instance of the Asset Owner OMAS is connected to.
GET {{baseURL}}/servers/{{server}}/open-metadata/access-services/governance-engine/users/{{user}}/governance-actions/{{guid}}

###
# @name Get All Governance Actions
# Asset is the top level type definition for an asset.  The type system also defines many more specialized types for Asset.  This requests lists the names of all of these specialized types found in the open metadata ecosystem that this instance of the Asset Owner OMAS is connected to.
GET {{baseURL}}/servers/{{server}}/open-metadata/access-services/governance-engine/users/{{user}}/governance-actions?
    startFrom=0&
    pageSize=0

###
# @name Get Active Governance Actions
# Asset is the top level type definition for an asset.  The type system also defines many more specialized types for Asset.  This requests lists the names of all of these specialized types found in the open metadata ecosystem that this instance of the Asset Owner OMAS is connected to.
GET {{baseURL}}/servers/{{server}}/open-metadata/access-services/governance-engine/users/{{user}}/governance-actions/active?
    startFrom=0&
    pageSize=0

###
# @name Get Out Topic Connection
# Asset is the top level type definition for an asset.  The type system also defines many more specialized types for Asset.  This requests lists the details of all of these specialized types found in the open metadata ecosystem that this instance of the Asset Owner OMAS is connected to.
GET {{baseURL}}/servers/{{server}}/open-metadata/access-services/governance-engine/users/{{user}}/topics/out-topic-connection/1111

###
# @name Create a Governance Action Process
# Add an asset definition for a CSV file
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/governance-engine/users/{{user}}/governance-action-processes/new
Content-Type: application/json

{
	"class" : "NewGovernanceActionProcessRequestBody",
    "processStatus" : "ACTIVE",
    "properties" : {
            "class" : "GovernanceActionProcessProperties",
            "qualifiedName" : "Process1",
            "displayName" : "Process1",
            "description" : "description",
            "technicalName" : "technicalName",
            "technicalDescription" : "technicalDescription",
            "owner" : "{{user}}",
            "ownerCategory" : "USER_ID"
    }
}

###
# @name Get Governance Action Processes by name
# Return a list of assets with the requested name.
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/governance-engine/users/{{user}}/governance-action-processes/by-name?
    startFrom=0&
    pageSize=10
Content-Type: application/json

{
  "class": "NameRequestBody",
  "name": "Process1"
}

###
# @name Get Governance Action Processes by search string
# Return a list of assets with the requested search string in their name, qualified name or description.
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/governance-engine/users/{{user}}/governance-action-processes/by-search-string?
    startFrom=0&
    pageSize=10
Content-Type: application/json

{
  "class": "SearchStringRequestBody",
  "searchString": ".*P.*"
}

###
# @name Get Governance Action Process By GUID
GET {{baseURL}}/servers/{{server}}/open-metadata/access-services/governance-engine/users/{{user}}/governance-action-processes/{{guid}}

###
# @name Create a Governance Action Type
# Add an asset definition for a CSV file
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/governance-engine/users/{{user}}/governance-action-types/new
Content-Type: application/json

{
	"class" : "GovernanceActionTypeProperties",
    "qualifiedName" : "Step-1",
    "displayName" : "Step-1",
    "description" : "description",
    "owner" : "{{user}}",
    "ownerCategory" : "USER_ID"
}

###
# @name Create a CSV file with schema
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-owner/users/{{user}}/assets/data-files/csv
Content-Type: application/json

{
  "class": "NewCSVFileAssetRequestBody",
  "displayName": "AIS data for January 2015 zone 1",
  "description": "TBA .",
  "fullPath": "file://Users/davidradley/testplatforms/usaf/files/AIS_2015_01_Zone06.csv",
  "columnHeaders": [
    "MMSI",
    "BaseDateTime",
    "LAT",
    "LON",
    "SOG",
    "COG",
    "Heading",
    "VesselName",
    "IMO",
    "CallSign",
    "VesselType",
    "Status",
    "Length",
    "Width",
    "Draft",
    "Cargo"
  ]
}

###
# @name Get Schema Attributes
GET {{baseURL}}/servers/{{server}}/open-metadata/common-services/asset-owner/connected-asset/users/{{user}}/assets/schemas/{{guid}}/schema-attributes?
    elementStart=0&
    maxElements=100

###
# @name Link duplicates
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/data-engine/users/{{user}}/open-metadata-store/related-elements/link-as-peer-duplicate
Authorization: Basic demo demo
Content-Type: application/json

{
	"class" : "DuplicatesRequestBody",
    "metadataElement1GUID" : "{{guid1}}",
    "metadataElement2GUID" : "{{guid2}}",
    "statusIdentifier" : 1,
    "steward" : "steward",
    "stewardTypeName" : "stewardTypeName",
    "stewardPropertyName" : "stewardPropertyName",
    "source" : "source",
    "notes" : "notes"
}