# SPDX-License-Identifier: CC-BY-4.0
# Copyright Contributors to the Egeria project.
---
name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [bug, triage]
body:
  - type: input
    id: issue_exists
    attributes:
      label: Existing/related issue?
      description: "Search for related issues. List below as #123456"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: More detailed specific steps to reproduce the behavior.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - Egeria: 3.0
          - OS: Ubuntu 20.04
          - Java: 11.0.3 (adoptopenjdk hotspot)
          - Browser: Chrome 80.02
          - Additional Connectors and integration: Egeria Postgres Connector
      value: |
        - Egeria:
        - OS:
        - Java:
        - Browser (for UI issues):
        - Additional connectors and integration:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Any Further Information?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering    !

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
