# SPDX-License-Identifier: CC-BY-4.0
# Copyright Contributors to the Egeria project.
---
name: Enhancement
description: Suggest an Enhancement
title: "[Enhancement] <title>"
labels: [enhancement, triage]
body:
  - type: input
    id: issue_exists
    attributes:
      label: Existing/related issue?
      description: "Search for related issues. List below as #123456"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Please describe the new behavior that that will improve Egeria
      description: Summarise what you'd like to see changed or added
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description: Can you think of any alternatives?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Any Further Information?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering    !

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: input
    id: work_on_it
    attributes:
      label: Would you be prepared to be assigned this issue to work on?
      description: Let us know if you'd be able to be involved in designing and implementing this enhancement
    validations:
      required: false
