# SPDX-License-Identifier: CC-BY-4.0
# Copyright Contributors to the Egeria project.
---
name: Release
description: Track a new release
title: "[RELEASE] Release x.y"
labels: [release]
assignees: 
  - mandy-chessell
  - lpalashevski

body:
  - type: textarea
    attributes:
      label: Work Plan
      description: Work Plan
      value: |
        Create release x.y :
        Prior to the release work
        - [ ] Slack post advising of upcoming release & linking to issue
        - [ ] Advance warning in developer/community call
        - [ ] Final agreement to start branch in team call & identification of outstanding issues
        - [ ] Agree required updates/versions for additional connector repos etc

        Branching & Correcting versions
        - [ ] Create branch (egeria-release-x.y)
        - [ ] Reassign any issues not being worked on to the next release
        - [ ] Update version for main (ie x.y-SNAPSHOT > x.y+1-SNAPSHOT)
        - [ ] Update version for release branch (ie x.y-SNAPSHOT -> x.y)
        

        Final updates to the release
        - [ ] Ensure any remaining fixes are merged into branch (and vice-versa to main)

        Pre-release security check
        - [ ] Check security scans (ie owasp dependency check)

        Generate a release image for testing
        - [ ] Start [Release](https://github.com/odpi/egeria/actions/workflows/release-v5.yml) pipeline manually to generate container image and stage artifacts on maven central.  Remember to select the release branch rather than `main`.


        Updating the Helm Charts (egeria-charts repo)
        - [ ] check correct container images are on [docker.io](https://hub.docker.com/u/odpi) & [quay.io](https://quay.io/organization/odpi) (these are built by the 'merge' build of a release)
        - [ ] update image versions for helm charts [egeria-charts](https://github.com/odpi/egeria-charts/) repo (using -prerelease for chart version)
          - check/update the [strimzi chart versions](https://github.com/strimzi/strimzi-kafka-operator/releases)
          - check/update supported kafka version used for the strimzi CR in each chart
          - check/update the current [jupyter lab version](https://hub.docker.com/r/jupyter/minimal-notebook/tags) & generate a new docker image in egeria-jupyter
          - update the jupyter lab image version in the charts


        Final tests
        - [ ] Check [swagger doc](https://egeria-project.org/education/tutorials/swagger-tutorial/overview/?h=swagger) renders (no regressions)
        - [ ] Verify odpi-egeria-lab chart (pods active/ready)
        - [ ] Verify egeria-base chart (pods active/ready)
        - [ ] Check notebooks (config, start, data catalog at a minimum)
        - [ ] Check Egeria UI (only possible to check it runs and run UI lab)
        - [ ] Check React UI (rex, tex, glossary author). Some of the steps described [here](https://egeria-project.org/education/egeria-dojo/running-egeria/user-interfaces/ecosystem-ui/ecosystem-ui-start/)
        - [ ] Check and validate [CTS results](https://egeria-project.org/guides/operations/kubernetes/charts/cts/)
          - CTS using in-memory
          - CTS using graph
          - CTS using xtdb

        Final Docs
        - [ ] Update release notes in [egeria-docs](https://github.com/odpi/egeria-docs/tree/main/site/docs/release-notes)

        Final build and publish
        - [ ] Check if the Release pipeline release artifacts are shown in staging repo in [OSS Repository Manager](https://oss.sonatype.org/#welcome)
        - [ ] Close staging repo & validate artifacts ok (number, structure, validations) on oss.sonatype.org 
        - [ ] Check 'release' repo on oss.sonatype.org has artifacts
        - [ ] Release the repo (takes time for the operation to complete and for the artifacts to be visible in maven central repository)
        - [ ] Create final [github release](https://github.com/odpi/egeria/releases) (add link to egeria docs)
        - [ ] Update final versions of egeria-charts to release ie x.y
        - [ ] Publish that release is now shipped via slack #egeria-announce
        - [ ] Post on egeria-announce [mailing list](egeria-announce@lists.lfaidata.foundation)
        - [ ] Additional posts to social media
        - [ ] Communicate to other repo owners ie for connectors so that they can be rebuilt/shipped as needed (Egeria Dev Projects etc.)


        Get Ready for next release
        - [ ] Open Release Issue for next release
---
