/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Contributors to the ODPi Egeria project.
 */


dependencies {
    implementation 'commons-io:commons-io'
    implementation 'org.slf4j:slf4j-api'
    implementation project(':open-metadata-implementation:frameworks:audit-log-framework')
    implementation project(':open-metadata-implementation:frameworks:open-connector-framework')
    implementation project(':open-metadata-implementation:frameworks:open-metadata-framework')
    compileOnly 'com.fasterxml.jackson.core:jackson-annotations'
    testImplementation project(':open-metadata-test:open-metadata-ut')
    testImplementation 'org.testng:testng'

}

description = 'Open Governance Framework (OFF)'

java {
    withJavadocJar()
}

test {
    useTestNG()
    // This will default to standard search pattern - see https://docs.gradle.org/current/userguide/java_testing.html#sec:test_detection
    scanForTestClasses = false
}
