# Egeria-it-infrastructure-omas

###
# @name Create Software Server Capability
POST {{baseURL}}/servers/cocoMDS2/open-metadata/access-services/it-infrastructure/users/{{user}}/software-server-capabilities?
    infrastructureManagerIsHome=false
Content-Type: application/json

{
    "class" : "SoftwareServerCapabilityRequestBody",
    "externalSourceGUID" : null,
    "externalSourceName" : null,
    "typeName" : null,
    "classificationName" : null,
    "qualifiedName" : "EngineHost2",
    "effectiveFrom" : null,
    "effectiveTo" : null,
    "displayName" : "",
    "description" : "",
    "typeDescription" : null,
    "version" : null,
    "patchLevel" : null,
    "source" : "postman",
    "additionalProperties" : null,
    "vendorProperties" : null,
    "extendedProperties" : null
}

###
# @name Create Software Server Capability From Template
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/it-infrastructure/users/{{user}}/software-server-capabilities/from-template/{{guid}}?
    infrastructureManagerIsHome=false
Content-Type: application/json

{
    "class" : "TemplateRequestBody",
    "externalSourceGUID" : null,
    "externalSourceName" : null,
    "typeName" : "",
    "classificationName" : null,
    "qualifiedName" : "",
    "displayName" : "",
    "description" : "",
    "networkAddress" : null
}

###
# @name Create Server Asset Use
POST {{baseURL}}/servers/cocoMDS2/open-metadata/access-services/it-infrastructure/users/{{user}}/server-asset-uses/software-server-capabilities/4e0db25f-1997-442c-b85c-a16b53767f58/assets/4ce19d15-86cf-42b0-a0ef-15a15553947c?
    infrastructureManagerIsHome=false
Content-Type: application/json

{
    "class" : "ServerAssetUseRequestBody",
    "externalSourceGUID" : null,
    "externalSourceName" : null,
    "properties" : 
    {
        "class" : "ServerAssetUseProperties",
        "useType" : "GOVERNS",
        "description" : "Governer"
    },
    "classificationName" : null,
    "qualifiedName" : "",
    "effectiveFrom" : null,
    "effectiveTo" : null,
    "displayName" : "",
    "description" : "",
    "typeDescription" : null,
    "version" : null,
    "patchLevel" : null,
    "source" : "postman",
    "additionalProperties" : null,
    "vendorProperties" : null,
    "extendedProperties" : null
}

###
# @name Get Capabilities for Asset
POST {{baseURL}}/servers/cocoMDS2/open-metadata/access-services/it-infrastructure/users/{{user}}/server-asset-uses/assets/d606772c-197a-47a3-a533-56cd5ebfc63c?
    startFrom=0&
    pageSize=0
Content-Type: application/json

{
    "class" : "UseTypeRequestBody"
}