# Egeria-server-operations

###
# @name Get active server configuration
# Retrieve the configuration document used to start the named server.
# The stored configuration document may have changed since the server was started.
# This operation makes it possible to verify the configuration values actually
# being used in the running server. An InvalidParameterException is returned if the server is not running.
# Further Information: https://egeria-project.org/concepts/configuration-document
GET {{baseURL}}/open-metadata/server-operations/users/{{adminUserId}}/servers/{{server}}/instance/configuration

###
# @name Get active server instance status
# Retrieve the status for a running instance of a server. This includes the status of each running
# service. It is used to verify that the required services are running.  An InvalidParameterException is returned if the server is not running.
# Further Information: https://egeria-project.org/concepts/omag-server
GET {{baseURL}}/open-metadata/server-operations/users/{{adminUserId}}/servers/{{server}}/instance/status

###
# @name Query the active services of a specific server
# Retrieve the list of services that are running inside of a specific server.
GET {{baseURL}}/open-metadata/server-operations/users/{{adminUserId}}/servers/{{server}}/services


###
# @name Load open metadata archive file
# Load a file that contains open metadata types and instances.
POST {{baseURL}}/open-metadata/server-operations/users/{{adminUserId}}/servers/{{server}}/instance/open-metadata-archives/file
Content-Type: text/plain

../opt/content-packs/CocoComboArchive.omarchive

###
# @name Load open metadata archive connection
# Load a file that contains open metadata types and instances.
POST {{baseURL}}/open-metadata/admin-services/users/{{adminUserId}}/servers/{{server}}/instance/open-metadata-archives/connection
Content-Type: application/json

{
    "class": "Connection",
    "connectorType": {
        "class": "ConnectorType",
        "connectorProviderClassName": "class name of connector provider here"
    },
    "endpoint" : {
        "class" : "Endpoint",
        "address" : "Add location of the archive here"
    }
}
