# Egeria-product-manager-view-service
# Manage the definition of a digital product (works with collection manager)

@baseURL=https://localhost:9443
@viewServer=view-server

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "peterprofile",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}


###

@digitalProductGUID=xxx

###
# @name createDigitalProduct (collection manager)
# Create a new collection that represents a digital product.
# Note: the three dates: introductionDate, nextVersionDate and withdrawDate must be valid dates if specified,
# otherwise you will get a 400 error response
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/product-manager/collections
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewElementRequestBody",
  "isOwnAnchor" : true,
  "anchorScopeGUID" : "optional GUID of search scope",
  "parentGUID" : "xxx",
  "parentRelationshipTypeName" : "CollectionMembership",
  "parentAtEnd1": true,
  "properties": {
    "class" : "DigitalProductProperties",
    "qualifiedName": "DigitalProduct::Add product name here",
    "displayName" : "Product contents",
    "description" : "Add description of product and its expected usage here",
    "identifier" : "Add product identifier here",
    "productName" : "Add product name here",
    "category" : "Periodic Delta",
    "maturity" : "Add valid value here",
    "serviceLife" : "Add the estimated lifetime of the product",
    "introductionDate" : "date",
    "nextVersionDate": "date",
    "withdrawDate": "date",
    "currentVersion": "V0.1",
    "additionalProperties": {
      "property1Name" : "property1Value",
      "property2Name" : "property2Value"
    }
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name updateDigitalProduct (collection manager)
# Update the properties of the DigitalProduct collection.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/product-manager/collections/{{digitalProductGUID}}/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "UpdateElementRequestBody",
  "properties": {
    "class" : "DigitalProductProperties",
    "qualifiedName": "DigitalProduct::Add product name here",
    "displayName" : "Product contents",
    "description" : "Add description of product and its expected usage here",
    "userDefinedStatus" : "OBSOLETE",
    "identifier" : "Add product identifier here",
    "productName" : "Add product name here",
    "category" : "Periodic Delta",
    "maturity" : "Add valid value here",
    "serviceLife" : "Add the estimated lifetime of the product",
    "introductionDate" : "date",
    "nextVersionDate": "date",
    "withdrawDate": "date",
    "currentVersion": "V0.1",
    "additionalProperties": {
      "property1Name" : "property1Value",
      "property2Name" : "property2Value"
    }
  },
  "mergeUpdate": true,
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name updateDigitalProductStatus (collection manager)
# Update the status of the DigitalProduct collection.  There are two statuses to consider.  The content status
# describes the state of the product description.  The deploymentStatus covers the status of the technical work to
# implement the product's digital resources.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/product-manager/collections/{{digitalProductGUID}}/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "UpdateElementRequestBody",
  "properties": {
    "class" : "DigitalProductProperties",
    "contentStatus": "APPROVED",
    "deploymentStatus": "UNDER_DEVELOPMENT"
  },
  "mergeUpdate": true
}


###

@consumerDigitalProductGUID=add guid here
@consumedDigitalProductGUID=add guid here

###
# @name linkDigitalProductDependency
# Link two dependent digital products.  The linked elements are of type 'DigitalProduct' . Request body is optional.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/product-manager/digital-products/{{consumerDigitalProductGUID}}/product-dependencies/{{consumedDigitalProductGUID}}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "properties": {
    "class": "DigitalPropertyDependencyProperties",
    "label": "add label here",
    "description": "add description here",
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  }
}


###
# @name detachDigitalProductDependency
# Unlink dependent digital products. Request body is optional.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/product-manager/digital-products/{{consumerDigitalProductGUID}}/product-dependencies/{{consumedDigitalProductGUID}}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###

@digitalProductManagerRoleGUID=Add guid here

###
# @name linkProductManager
# Attach a product manager role to a digital product. Request body is optional.
# This role acts as a placeholder in the organization.  It may be a PersonRole, TeamRole or ITProfileRole.
# People/Teams/Software Components can be assigned to the role at a later time.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/product-manager/digital-products/{{digitalProductGUID}}/product-managers/{{digitalProductManagerRoleGUID}}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
      "class" : "AssignmentScope",
      "assignmentType" : "Add type here",
      "description" : "Add assignment description here"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name detachProductManager
# Detach a product manager from a digital product. Request body is optional.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/product-manager/digital-products/{{digitalProductGUID}}/product-managers/{{digitalProductManagerRoleGUID}}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

