# Egeria-glossary-browser-omvs

@baseURL=https://localhost:9443
@viewServer=view-server

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "peterprofile",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}


###
# group: Glossaries
# @name getGlossaryTermStatuses
# Return the list of glossary term status enum values.
GET {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/terms/status-list
Authorization: Bearer {{token}}

###
# group: Glossaries
# @name getGlossaryTermRelationshipStatuses
# Return the list of glossary term relationship status enum values.  These values are stored in a term-to-term,
# or term-to-category, relationship and are used to indicate how much the relationship should be trusted.
GET {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/terms/relationships/status-list
Authorization: Bearer {{token}}


###
# group: Glossaries
# @name getGlossaryTermActivityTypes
# Return the list of glossary term activity type enum values.
GET {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/terms/activity-types
Authorization: Bearer {{token}}


###
# group: Glossaries
# @name findGlossaries
# Retrieve the list of glossary metadata elements that contain the search string.  The search string is located
# in the request body and is interpreted as a plain string.  The request parameters, startsWith, endsWith and
# ignoreCase can be used to allow a fuzzy search.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/by-search-string?
    startFrom=0&pageSize=0&startsWith=true&endsWith=false&ignoreCase=false
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "SearchStringRequestBody",
  "searchString" : "sus"
}


###
# group: Glossaries
# @name getGlossariesByName
# Retrieve the list of glossary metadata elements with an exactly matching qualified or display name.
# There are no wildcards supported on this request.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/by-name?startFrom=0&pageSize=0
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NameRequestBody",
  "name" : "Sustainability Glossary"
}



###
# group: Glossaries
# @name getGlossaryByGUID
# Retrieve the glossary metadata element with the supplied unique identifier.  The optional request body allows you to
# specify that the glossary element should only be returned if it was effective at a particular time.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/{{glossaryGUID}}/retrieve
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"class" : "EffectiveTimeQueryRequestBody",
	 "effectiveTime" : "null"
}


###
# group: Glossaries
# @name getGlossaryForCategory
# Retrieve the glossary metadata element for the requested category.  The optional request body allows you to specify
# that the glossary element should only be returned if it was effective at a particular time.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/for-category/{{glossaryCategoryGUID}}/retrieve
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "EffectiveTimeQueryRequestBody",
  "effectiveTime" : "null"
}


###
# group: Glossaries
# @name getGlossaryForTerm
# Retrieve the glossary metadata element for the requested term.  The optional request body allows you to specify
# that the glossary element should only be returned if it was effective at a particular time.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/for-term/{{glossaryTermGUID}}/retrieve
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "EffectiveTimeQueryRequestBody",
  "effectiveTime" : "null"
}


###
# group: Glossaries
# @name getRelatedTerms
# Retrieve the glossary terms that are linked to the requested glossary term.  The optional request body allows you to specify
# that the glossary term should only be returned if it was effective at a particular time and limit the results by relationship type name,
# owning type name and the status of the relatiosnships
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/terms/{{glossaryTermGUID}}/related-terms
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "GlossaryTermRelationshipRequestBody",
  "effectiveTime" : "null",
  "glossaryGUID" : "add guid",
  "relationshipTypeName" :  "add type name",
  "limitResultsByStatus" :  []
}


###
# group: GlossaryCategories
# @name findGlossaryCategories
# Retrieve the list of glossary category metadata elements that contain the search string.
# The search string is located in the request body and is interpreted as a plain string.
# The request parameters, startsWith, endsWith and ignoreCase can be used to allow a fuzzy search.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/categories/by-search-string?
    startFrom=0&pageSize=0&startsWith=false&endsWith=false&ignoreCase=false
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "SearchStringRequestBody",
  "searchString" : ""
}

###
# group: GlossaryCategories
# @name getCategoriesForGlossary
# Return the list of categories associated with a glossary.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/{{glossaryGUID}}/categories/retrieve?
    startFrom=0&pageSize=0
Authorization: Bearer {{token}}
Content-Type: application/json


###
# group: GlossaryCategories
# @name getCategoriesForTerm
# Return the list of categories associated with a glossary term.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/terms/{{glossaryTermGUID}}/categories/retrieve?
    startFrom=0&pageSize=0
Authorization: Bearer {{token}}
Content-Type: application/json


###
# group: GlossaryCategories
# @name getGlossaryCategoriesByName
# Retrieve the list of glossary category metadata elements that either have the requested qualified name or display name.
# The name to search for is located in the request body and is interpreted as a plain string.
# The request body also supports the specification of a glossaryGUID to restrict the search to within a single glossary.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/categories/by-name
    ?startFrom=0&pageSize=0
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "GlossaryNameRequestBody",
  "name" : "Chemicals",
  "glossaryGUID" : "{{glossaryGUID}}",
  "limitResultsByStatus" : [ "DRAFT", "PREPARED", "PROPOSED", "APPROVED", "ACTIVE"]
}


###
# group: GlossaryCategories
# @name getGlossaryCategoryByGUID
# Retrieve the requested glossary category metadata element.  The optional request body contain an effective time for the query.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/categories/{{glossaryCategoryGUID}}/retrieve
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "EffectiveTimeQueryRequestBody",
  "effectiveTime" : "null"
}


###
# group: GlossaryCategories
# @name getGlossaryCategoryParent
# Glossary categories can be organized in a hierarchy. Retrieve the parent glossary category metadata
# element for the glossary category with the supplied unique identifier.  If the requested category
# does not have a parent category, null is returned.  The optional request body contain an effective time
# for the query.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/categories/{{glossaryCategoryGUID}}/retrieve
Authorization: Bearer {{token}}
Content-Type: application/json

###
# group: GlossaryTerms
# @name Retrieve ALL the glossary terms in a category
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/categories/{{glossaryCategoryGUID}}/terms/retrieve?
    startFrom=0&pageSize=0
Authorization: Bearer {{token}}
Content-Type: application/json

###
# group: GlossaryTerms
# @name getGlossaryTermByName
# Retrieve the list of glossary metadata elements with an exactly matching qualified or display name.
# There are no wildcards supported on this request.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/terms/by-name?startFrom=0&pageSize=0
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NameRequestBody",
  "name" : "Carbon Dioxide"
}


###
# group: GlossaryTerms
# @name Retrieve a glossary term's relationships
# This call retrieves details of the glossary terms linked to this glossary term.  Notice the original org 1 glossary term is linked via the "SourcedFrom" relationship..
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/terms/{{glossaryTermGUID}}/related-terms?
    startFrom=0&
    pageSize=0
Authorization: Bearer {{token}}
Content-Type: application/json

###
# group: GlossaryTerms
# @name Retrieve the DRAFT glossary terms from a glossary
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/terms/by-search-string?
    startFrom=0&pageSize=0&startsWith=false&endsWith=false&ignoreCase=false
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "class" : "GlossarySearchStringRequestBody",
    "searchString" : "",
    "glossaryGUID" : "{{glossaryGUID}}",
    "limitResultsByStatus" : ["DRAFT"]
}

###
# group: GlossaryTerms
# @name Retrieve the ACTIVE and PREPARED glossary terms from a glossary
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/terms/by-search-string?
    startFrom=0&pageSize=0&startsWith=false&endsWith=false&ignoreCase=false
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "class" : "GlossarySearchStringRequestBody",
    "searchString" : "",
    "glossaryGUID" : "{{glossaryGUID}}",
    "limitResultsByStatus" : ["ACTIVE", "PREPARED"]
}

###
# group: GlossaryTerms
# @name Retrieve a glossary term by GUID
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/terms/{{glossaryTermGUID}}/retrieve
Authorization: Bearer {{token}}
Content-Type: application/json

###
# group: GlossaryTerms
# @name Retrieve the versions of the glossary term
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/glossaries/terms/{{glossaryTermGUID}}/history?
    startFrom=0&pageSize=0
Authorization: Bearer {{token}}
Content-Type: application/json

###
# group: GlossaryTerms
# @name Retrieve the revision log for a glossary term
# Add the returned guid as orgGlossaryTerm1_RevisionLogGUID variable.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/elements/{{glossaryTermGUID}}/note-logs/retrieve?
    startFrom=0&pageSize=0
Authorization: Bearer {{token}}
Content-Type: application/json

###
# group: GlossaryTerms
# @name Retrieve the revision history for a glossary term
# This revision history is created automatically.  The text is supplied on the update request.  If no text is supplied, the value "None" is show.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/glossary-browser/note-logs/{{glossaryTermRevisionLogGUID}}/notes/retrieve?
    startFrom=0&pageSize=0
Authorization: Bearer {{token}}
Content-Type: application/json

###
# group: GlossaryTerms
# @name Search for term by version identifier
POST {{baseURL}}/servers/{{viewServer}}/open-metadata/framework-services/asset-manager/open-metadata-store/users/{{user}}/metadata-elements/by-search-conditions?
    startFrom=0&pageSize=0&
    forLineage=false&
    forDuplicateProcessing=false&
    effectiveTime=0
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "class" : "FindRequestBody",
    "metadataElementTypeName" : "GlossaryTerm",
    "searchProperties" : {
        "class" : "SearchProperties",
        "conditions" : [{
            "class" : "PropertyCondition",
            "property" : "publishVersionIdentifier",
            "operator" : "EQ",
            "value" : {
                "class" : "PrimitiveTypePropertyValue",
                "primitiveTypeCategory" : "OM_PRIMITIVE_TYPE_STRING",
                "primitiveValue" : "V1.0",
                "typeName" : "string"
                }
        }],
        "matchCriteria" : "ALL"
    }
}
