# Egeria-open-integration-service

###
# @name getMetadataSourceGUID
POST {{baseURL}}/servers/{{server}}/open-metadata/framework-services/{{access_service}}/open-integration/users/{{user}}/metadata-sources/by-name
Content-Type: application/json

{
    "class" : "NameRequestBody",
    "name" : "{{metadataSourceQualifiedName}}"
}

###
# @name createMetadataSource
POST {{baseURL}}/servers/{{server}}/open-metadata/framework-services/{{access_service}}/open-integration/users/{{user}}/metadata-sources/new
Content-Type: application/json

{
    "class" : "MetadataSourceRequestBody",
    "typeName" : "{{typeName}}",
    "classificationName" : "{{classificationName}}",
    "qualifiedName" : "{{metadataSourceQualifiedName}}"
}

###
# @name publishIntegrationReport
POST {{baseURL}}/servers/{{server}}/open-metadata/framework-services/{{access_service}}/open-integration/users/{{user}}/integration-reports/{{guid}}/new
Content-Type: application/json

{
    "class" : "IntegrationReportProperties",
    "serverName" : "{{server}}",
    "connectorId" : "{{connectorId}}",
    "connectorName" : "{{connectorName}}",
    "refreshStartDate" : "{{$isoTimestamp}}",
    "refreshCompletionDate" : "{{$isoTimestamp}}",
    "createdElements" : ["guid1", "guid2", "guid3"],
    "updatedElements" : ["guid4", "guid5"],
    "deletedElements" : ["guid6"],
    "additionalProperties" : {
        "prop1" : "value 1",
        "prop2" : "value 2"
    }
}

###
# @name getIntegrationReport
GET {{baseURL}}/servers/{{server}}/open-metadata/framework-services/{{access_service}}/open-integration/users/{{user}}/integration-reports/{{reportGUID}}

###
# @name getIntegrationReportForElement
GET {{baseURL}}/servers/{{server}}/open-metadata/framework-services/{{access_service}}/open-integration/users/{{user}}/integration-reports/for-element/{{guid}}?
    startingFrom=0&
    maximumResults=0

###
# @name getIntegrationReports
GET {{baseURL}}/servers/{{server}}/open-metadata/framework-services/{{access_service}}/open-integration/users/{{user}}/integration-reports?
    startingFrom=0&
    maximumResults=0
