# Egeria-api-metadata-expert
# The Metadata Expert API supports advanced metadata management and search,for open metadata.
# It is an advanced API for users that understand the [Open Metadata Types](https://egeria-project.org/types/).

@baseURL=https://localhost:7443
@viewServer=view-server

# Optional request options not show on the example requests below:
# -------------------------------------------------------------------
# Note: This a generic service which means the URL marker of "metadata-expert" can be replaced with the URL marker
# of any other active view service.
# The URL marker is derived from the name of the requested service - take the short two-word service name, convert to
# lower case and add a hyphen between the two words - so Automated Curation's OMVS's URL Marker is automated-curation.
#

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "peterprofile",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}


###
# =====================================================================================================================
# Maintain the metadata elements thatare passed on the requests

@metadataElementGUID=add guid here
@classificationName=add name here
@relationshipGUID=add guid here

###
# @name createMetadataElementInStore
# Create a new metadata element in the metadata store.  The type name comes from the open metadata types.
# The selected type also controls the names and types of the properties that are allowed.
# This version of the method allows access to advanced features such as multiple states and
# effectivity dates.
     
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewOpenMetadataElementRequestBody",
  "externalSourceGUID" : "",
  "externalSourceName" : "",
  "typeName" : "",
  "initialClassifications" : {},
  "anchorGUID" : "",
  "isOwnAnchor" : false,
  "effectiveFrom" : "{{$isoTimestamp}}",
  "effectiveTo": "{{$isoTimestamp}}",
  "properties" : {},
  "parentGUID" : "",
  "parentRelationshipTypeName" : "",
  "parentRelationshipProperties" : {},
  "parentAtEnd1" : true,
  "effectiveTime" : "{{$isoTimestamp}}"
}


###
# @name createMetadataElementFromTemplate
# Create a new metadata element in the metadata store using a template.  The type name comes from the open metadata types.
# The selected type also controls the names and types of the properties that are allowed.

POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/from-template
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "TemplateRequestBody",
  "externalSourceGUID" :  "",
  "externalSourceName" : "",
  "typeName" : "",
  "templateGUID" : "",
  "anchorGUID" : "",
  "isOwnAnchor" : false,
  "effectiveFrom" : "{{$isoTimestamp}}",
  "effectiveTo": "{{$isoTimestamp}}",
  "replacementProperties" : {
    "class": "ElementProperties",
    "propertyValueMap" : {
      "propertyName" : {
        "class": "PrimitiveTypePropertyValue",
        "typeName": "string",
        "primitiveValue" : "value of property"
      }
    }
  },
  "placeholderPropertyValues" : {
     "placeholderName1" : "placeholderValue1",
     "placeholderName2" : "placeholderValue2"
  },
  "parentGUID" : "",
  "parentRelationshipTypeName" : "",
  "parentRelationshipProperties" : {},
  "parentAtEnd1" : true,
  "effectiveTime" : "{{$isoTimestamp}}"
}


###
# @name updateMetadataElementInStore
# Update the properties of a specific metadata element.  The properties must match the type definition associated with the
# metadata element when it was created.  However, it is possible to update a few properties, or replace all them by
# the value used in the replaceProperties flag.

POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/{{metadataElementGUID}}/update-properties
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "UpdatePropertiesRequestBody",
  "externalSourceGUID" :  "",
  "externalSourceName" : "",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "effectiveTime" : "{{$isoTimestamp}}",
  "properties" : {
    "class": "ElementProperties",
    "propertyValueMap" : {
      "description" : {
        "class": "PrimitiveTypePropertyValue",
        "typeName": "string",
        "primitiveValue" : "New description"
      }
    }
  },
  "replaceProperties" : false
}

###
# @name publishMetadataElement
# Update the zone membership to increase its visibility.  The publishZones are defined in the user directory.

POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/{{metadataElementGUID}}/publish
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "MetadataSourceRequestBody",
  "externalSourceGUID" :  "",
  "externalSourceName" : "",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "effectiveTime" : "{{$isoTimestamp}}"
}


###
# @name withdrawMetadataElement
# Update the zone membership to decrease its visibility.  The defaultZones are defined in the user directory.

POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/{{metadataElementGUID}}/withdraw
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "MetadataSourceRequestBody",
  "externalSourceGUID" :  "",
  "externalSourceName" : "",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "effectiveTime" : "{{$isoTimestamp}}"
}


###
# @name updateMetadataElementEffectivityInStore
# Update the effectivity dates control the visibility of the element through specific APIs.

POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/{{metadataElementGUID}}/update-effectivity
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "UpdateEffectivityDatesRequestBody",
  "externalSourceGUID" :  "",
  "externalSourceName" : "",
  "effectiveFrom" : "{{$isoTimestamp}}",
  "effectiveTo": "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "effectiveTime" : "{{$isoTimestamp}}"
}


###
# @name deleteMetadataElementInStore
# Delete a specific metadata element.

POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/{{metadataElementGUID}}/delete
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "OpenMetadataDeleteRequestBody",
  "externalSourceGUID" :  "",
  "externalSourceName" : "",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "effectiveTime" : "{{$isoTimestamp}}"
}


###
# @name archiveMetadataElementInStore
# Archive a specific metadata element.

POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/{{metadataElementGUID}}/archive
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteElementRequestBody",
  "externalSourceGUID" :  "",
  "externalSourceName" : "",
  "archiveDate" : "{{$isoTimestamp}}",
  "archiveProcess" : "",
  "archiveProperties": {
     "propertyName1" : "propertyValue1",
     "propertyName2" : "propertyValue2"
  },
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "effectiveTime" : "{{$isoTimestamp}}"
}


###
# @name classifyMetadataElementInStore
# Add a new classification to the metadata element.  Note that only one classification with the same name can be attached to
# a metadata element.

 POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/{{metadataElementGUID}}/classifications/{{classificationName}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewClassificationRequestBody",
  "externalSourceGUID" :  "",
  "externalSourceName" : "",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "effectiveTime" : "{{$isoTimestamp}}"
}


###
# @name reclassifyMetadataElementInStore
# Update the properties of a classification that is currently attached to a specific metadata element.

POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/{{metadataElementGUID}}/classifications/{{classificationName}}/update-properties
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "UpdatePropertiesRequestBody",
  "externalSourceGUID" :  "",
  "externalSourceName" : "",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "effectiveTime" : "{{$isoTimestamp}}"
}


###
# @name updateClassificationEffectivityInStore
# Update the effectivity dates of a specific classification attached to a metadata element.
# The effectivity dates control the visibility of the classification through specific APIs.

POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/{{metadataElementGUID}}/classifications/{{classificationName}}/update-effectivity
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "UpdateEffectivityDatesRequestBody",
  "externalSourceGUID" :  "",
  "externalSourceName" : "",
  "effectiveFrom" : "{{$isoTimestamp}}",
  "effectiveTo": "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "effectiveTime" : "{{$isoTimestamp}}"
}


###
# @name declassifyMetadataElementInStore
# Remove the named classification from a specific metadata element.

POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/{{metadataElementGUID}}/classifications/{{classificationName}}/delete
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "MetadataSourceRequestBody",
  "externalSourceGUID" :  "",
  "externalSourceName" : "",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "effectiveTime" : "{{$isoTimestamp}}"
}


###
# @name createRelatedElementsInStore
# Create a relationship between two metadata elements.  It is important to put the right element at each end of the relationship
# according to the type definition since this will affect how the relationship is interpreted.

POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/related-elements
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelatedElementsRequestBody",
  "externalSourceGUID" :  "",
  "externalSourceName" : "",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "effectiveTime" : "{{$isoTimestamp}}"
}


###
# @name updateRelatedElementsInStore
# Update the properties associated with a relationship.

POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/related-elements/{{relationshipGUID}}/update-properties
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "UpdatePropertiesRequestBody",
  "externalSourceGUID" :  "",
  "externalSourceName" : "",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "effectiveTime" : "{{$isoTimestamp}}"
}


###
# @name updateRelatedElementsEffectivityInStore
# Update the effectivity dates of a specific relationship between metadata elements.
# The effectivity dates control the visibility of the classification through specific APIs.

POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/related-elements/{{relationshipGUID}}/update-effectivity
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "UpdateEffectivityDatesRequestBody",
  "externalSourceGUID" :  "",
  "externalSourceName" : "",
  "effectiveFrom" : "{{$isoTimestamp}}",
  "effectiveTo": "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "effectiveTime" : "{{$isoTimestamp}}"
}


###
# @name deleteRelatedElementsInStore
# Delete a relationship between two metadata elements.

POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/related-elements/{{relationshipGUID}}/delete
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "OpenMetadataDeleteRequestBody",
  "externalSourceGUID" :  "",
  "externalSourceName" : "",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "effectiveTime" : "{{$isoTimestamp}}"
}

###
# @name getMetadataElementByGUID
# Retrieve the metadata element using its unique identifier.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/{{metadataElementGUID}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "GetRequestBody",
  "effectiveTime" : "{{$isoTimestamp}}"
}


###
# @name getAnchoredElementsGraph
# Retrieve the metadata element using its unique identifier.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/{{metadataElementGUID}}/with-anchored-elements
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "GetRequestBody",
  "effectiveTime" : "{{$isoTimestamp}}"
}



###
# @name getMetadataElementByUniqueName
# Retrieve the metadata element using its unique name (typically the *qualifiedName* attribute but other attributes can be used if they are unique - such as *pathName* for a file).
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/by-unique-name
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "UniqueNameRequestBody",
  "effectiveTime" : "{{$isoTimestamp}}",
  "name" : "put name here",
  "namePropertyName" : "qualifiedName"
}


###
# @name getMetadataElementGUIDByUniqueName
# Retrieve the metadata element guid using its unique name (typically the qualified name as shown).
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/guid-by-unique-name
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "UniqueNameRequestBody",
  "effectiveTime" : "{{$isoTimestamp}}",
  "name" : "put name here",
  "namePropertyName" : "qualifiedName"
}


###
# @name getMetadataElementHistory
# Retrieve all the versions of an element.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/{{metadataElementGUID}}/history
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "HistoryRequestBody",
  "effectiveTime" : "{{$isoTimestamp}}",
  "oldestFirst": false
}



###
# @name getClassificationHistory
# Retrieve all the versions of an element.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/{{metadataElementGUID}}/classifications/{{classificationName}}/history
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "HistoryRequestBody",
  "effectiveTime" : "{{$isoTimestamp}}",
  "oldestFirst": false
}


###
# @name findMetadataElementsWithString
# Retrieve the metadata elements that contain the requested string.
# If search string is missing, then all elements of the specified type are returned.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/by-search-string
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "SearchStringRequestBody",
  "searchString" : "put search string here",
  "startsWith": false,
  "endsWith": false,
  "ignoreCase": true,
  "metadataElementTypeName" : "put type here (optional)",
  "effectiveTime" : "{{$isoTimestamp}}",
  "limitResultsByStatus" : ["ACTIVE"],
  "asOfTime" : "{{$isoTimestamp}}",
  "sequencingOrder": "CREATION_DATE_RECENT",
  "sequencingProperty": ""
}

###

@anchorGUID=put guid here

###
# @name findElementsForAnchor
# Return a list of elements with the requested search string in their (display, resource)name, qualified name,
# title, text, summary, identifier or description.  The search string is interpreted as a regular expression (RegEx).
# The breadth of the search is determined by the supplied anchorGUID.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/by-search-string/for-anchor/{{anchorGUID}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "SearchStringRequestBody",
  "searchString" : "add search string here",
  "metadataElementTypeName" : "add type name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "limitResultsByStatus" : ["ACTIVE"],
  "asOfTime" : "{{$isoTimestamp}}",
  "sequencingOrder": "CREATION_DATE_RECENT",
  "sequencingProperty": ""
}

###

@anchorDomainName=add type name here

###
# @name findElementsInAnchorDomain
# Return a list of elements with the requested search string in their (display, resource)name, qualified name,
# title, text, summary, identifier or description.  The search string is interpreted as a regular expression (RegEx).
# The breadth of the search is determined by the supplied domain name. The results are organized by anchor element.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/by-search-string/in-anchor-domain/{{anchorDomainName}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "SearchStringRequestBody",
  "searchString" : "Add search string here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "limitResultsByStatus" : ["ACTIVE"],
  "asOfTime" : "{{$isoTimestamp}}",
  "sequencingOrder": "CREATION_DATE_RECENT",
  "sequencingProperty": ""
}

###

@anchorScopeGUID=add guid here

###
# @name findElementsInAnchorScope
# Return a list of elements with the requested search string in their (display, resource)name, qualified name,
# title, text, summary, identifier or description.  The search string is interpreted as a regular expression (RegEx).
# The breadth of the search is determined by the supplied scope guid. The results are organized by anchor element.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/by-search-string/in-anchor-scope/{{anchorScopeGUID}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "SearchStringRequestBody",
  "searchString" : "add search string here",
  "metadataElementTypeName" : "add type name here"
}


###
# @name getAllRelatedMetadataElements
# Retrieve the metadata elements connected to the supplied element.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/related-elements/{{metadataElementGUID}}/any-type?startingAtEnd=0
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ResultsRequestBody",
  "effectiveTime" : "{{$isoTimestamp}}",
  "limitResultsByStatus" : ["ACTIVE"],
  "asOfTime" : "{{$isoTimestamp}}",
  "sequencingOrder": "CREATION_DATE_RECENT",
  "sequencingProperty": ""
}


###
# @name getAllRelatedMetadataElements
# Retrieve the metadata elements connected to the supplied element.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/related-elements/{{metadataElementGUID}}/any-type?startingAtEnd=0
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ResultsRequestBody",
  "effectiveTime" : "{{$isoTimestamp}}",
  "limitResultsByStatus" : ["ACTIVE"],
  "asOfTime" : "{{$isoTimestamp}}",
  "sequencingOrder": "PROPERTY_ASCENDING",
  "sequencingProperty": "preferredValue"
}


###

@metadataElementAtEnd1GUID=add guid here
@metadataElementAtEnd2GUID=add guid here

###
# @name getAllMetadataElementRelationships
# Retrieve the relationships linking the supplied elements.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/{{metadataElementAtEnd1GUID}}/linked-by-any-type/to-elements/{{metadataElementAtEnd2GUID}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ResultsRequestBody",
  "effectiveTime" : "{{$isoTimestamp}}",
  "limitResultsByStatus" : ["ACTIVE"],
  "asOfTime" : "{{$isoTimestamp}}",
  "sequencingOrder": "CREATION_DATE_RECENT",
  "sequencingProperty": ""
}


###
# @name getMetadataElementRelationships
# Retrieve the relationships linking the supplied elements via a specific type of relationship.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/{{metadataElementAtEnd1GUID}}/linked-by-type/{{relationshipTypeName}}/to-elements/{{metadataElementAtEnd2GUID}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ResultsRequestBody",
  "effectiveTime" : "{{$isoTimestamp}}",
  "limitResultsByStatus" : ["ACTIVE"],
  "asOfTime" : "{{$isoTimestamp}}",
  "sequencingOrder": "CREATION_DATE_RECENT",
  "sequencingProperty": ""
}



###
# @name getMatchCriteriaList
# Retrieve all the valid values for MatchCriteria
GET {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-search/match-criteria-values
Authorization: Bearer {{token}}
Content-Type: application/json



###
# @name getPropertyComparisonOperatorList
# Retrieve all the valid values for ProeprtyComparisonOperator
GET {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-search/property-comparison-operator-values
Authorization: Bearer {{token}}
Content-Type: application/json




###
# @name findMetadataElements (nested condition)
# Return a list of metadata elements that match the supplied criteria.  The results can be returned over many pages.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/metadata-elements/by-search-conditions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "FindRequestBody",
  "metadataElementTypeName": "Location",
  "metadataElementSubtypeNames": [],
  "searchProperties": {
     "class" : "SearchProperties",
     "conditions": [ {
         "nestedConditions": {
               "class" : "SearchProperties",
               "conditions": [
               {
                   "property" : "identifier",
                   "operator": "LIKE",
                   "value": {
                      "class" : "PrimitiveTypePropertyValue",
                      "typeName" : "string",
                      "primitiveValue" : "AMS"
                   }
               },
               {
                   "property" : "identifier",
                   "operator": "LIKE",
                   "value": {
                      "class" : "PrimitiveTypePropertyValue",
                      "typeName" : "string",
                      "primitiveValue" : "OFFICE"
                   }
               }],
               "matchCriteria": "ANY"
         }},
         {
             "property" : "displayName",
             "operator": "LIKE",
             "value": {
                      "class" : "PrimitiveTypePropertyValue",
                      "typeName" : "string",
                      "primitiveValue" : "Cancer"
                   }

     }],
     "matchCriteria": "ALL"
  },
  "skipRelationships": [],
  "includeOnlyRelationships": [],
  "relationshipsPageSize": 100,
  "skipClassifiedElements": [],
  "includeOnlyClassifiedElements": [],
  "graphQueryDepth" : 10,
  "effectiveTime" : "{{$isoTimestamp}}",
  "limitResultsByStatus" : ["ACTIVE"],
  "asOfTime" : "{{$isoTimestamp}}",
  "sequencingOrder": "CREATION_DATE_RECENT",
  "sequencingProperty": ""
}



###
# @name findRelationshipsBetweenMetadataElements
# Return a list of relationships that match the requested conditions.  The results can be received as a series of pages.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/relationships/by-search-conditions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "FindRelationshipRequestBody",
  "relationshipTypeName": "ResourceList",
  "searchProperties": {
            "class" : "SearchProperties",
               "conditions": [
               {
                   "property" : "resourceUse",
                   "operator": "EQ",
                   "value": {
                      "class" : "PrimitiveTypePropertyValue",
                      "typeName" : "string",
                      "primitiveValue" : "Survey Resource"
                   }
               }],
               "matchCriteria": "ALL"
         },
  "effectiveTime" : "{{$isoTimestamp}}",
  "limitResultsByStatus" : ["ACTIVE"],
  "asOfTime" : "{{$isoTimestamp}}",
  "sequencingOrder": "CREATION_DATE_RECENT",
  "sequencingProperty": ""
}

###
# @name getRelationshipByGUID
# Retrieve the relationship using its unique identifier.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/relationships/by-guid/{{relationshipGUID}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "GetRequestBody",
  "effectiveTime" : "{{$isoTimestamp}}"
}



###
# @name getRelationshipHistory
# Retrieve all the versions of a relationship.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/metadata-expert/relationships/{{relationshipGUID}}/history?oldestFirst=true
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "HistoryRequestBody",
  "effectiveTime" : "{{$isoTimestamp}}"
}



