# Egeria-reference-data-view-service

@baseURL=https://localhost:9443
@viewServer=view-server

###
# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "peterprofile",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}



