# Egeria-coco-audit-users
# A demonstration on access user identities, user accounts, their definitions and any exceptions.

@baseURL=https://localhost:9443
@viewServer=view-server

###
# =====================================================================================================================
# Manage the authentication token.  Run these requests to create/refresh the token.

# @name Token (log in as Gary Geeke who is a system administrator)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "garygeeke",
  "password" : "secret"
}

> {% client.global.set("garyToken", response.body); %}


###

# @name Token (log in as Ivor Padlock who is a security officer and has access to all of the user information)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "ivorpadlock",
  "password" : "secret"
}

> {% client.global.set("ivorToken", response.body); %}


###

# @name Token (log in as Callie Quartile who is a aata scientist without priviledges to audit users.)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "calliequartile",
  "password" : "secret"
}

> {% client.global.set("callieToken", response.body); %}

###
# =====================================================================================================================
# Retrieve the platform GUID
# https://egeria-project.org/types/0037-Software-Server-Platforms/

###
# @name getPlatformsByName
# Returns the list of platforms with a particular name. The name is specified in the filter.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/runtime-manager/platforms/by-name
Authorization: Bearer {{garyToken}}
Content-Type: application/json

{
  "filter" : "Local OMAG Server Platform"
}

> {% client.global.set("omagServerPlatformGUID", response.body.elements[0].elementHeader.guid); %}



###
# ========================================================================================
# Retrieve Secret Collections
#

###
# @name findAssets (SecretCollections) using gary's token
# Retrieve the list of asset metadata elements that contain the search string.
#
# Request body provides string to find in the properties
#
# Returns list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/assets/by-search-string
Authorization: Bearer {{garyToken}}
Content-Type: application/json

{
  "class" : "SearchStringRequestBody",
  "searchString": "cocoUserDirectory",
  "metadataElementTypeName": "SecretsCollection"
}

###
# @name findAssets (SecretCollections) using ivor's token
# Retrieve the list of asset metadata elements that contain the search string.
#
# Request body provides string to find in the properties
#
# Returns list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/asset-maker/assets/by-search-string
Authorization: Bearer {{ivorToken}}
Content-Type: application/json

{
  "class" : "SearchStringRequestBody",
  "searchString": "cocoUserDirectory",
  "metadataElementTypeName": "SecretsCollection"
}

###
# ========================================================================================
# Retrieve user identities
#

###
# @name findUserIdentities (gary)
# Retrieve the list of user identity metadata elements that contain the search string.
#
# Request body provides string to find in the properties
#
# Returns list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/actor-manager/user-identities/by-search-string
Authorization: Bearer {{garyToken}}
Content-Type: application/json

###
# @name getUserIdentityByGUID (gary)
# Return the properties of a specific user identity.
#
# @param userIdentityGUID    unique identifier of the required element
# Request body provides string to find in the properties
#
# Returns list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/actor-manager/user-identities/1d1d3d60-3808-4bda-94f0-c3792a53bed6/retrieve
Authorization: Bearer {{garyToken}}
Content-Type: application/json


###
# @name findUserIdentities (ivor)
# Retrieve the list of user identity metadata elements that contain the search string.
#
# Request body provides string to find in the properties
#
# Returns list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/actor-manager/user-identities/by-search-string
Authorization: Bearer {{ivorToken}}
Content-Type: application/json


###
# @name getUserIdentityByGUID (ivor)
# Return the properties of a specific user identity.
#
# @param userIdentityGUID    unique identifier of the required element
# Request body provides string to find in the properties
#
# Returns list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/actor-manager/user-identities/1d1d3d60-3808-4bda-94f0-c3792a53bed6/retrieve
Authorization: Bearer {{ivorToken}}
Content-Type: application/json

###
# ========================================================================================
# Retrieve exception types
#

###
# @name findGovernanceDefinitions
# Retrieve the list of governance definition metadata elements that contain the search string.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/governance-officer/governance-definitions/by-search-string
Authorization: Bearer {{ivorToken}}
Content-Type: application/json

{
  "class" : "SearchStringRequestBody",
  "metadataElementTypeName": "ExceptionType"
}




###
# ========================================================================================
# Retrieve governance zone
#

###
# @name findGovernanceDefinitions
# Retrieve the list of governance definition metadata elements that contain the search string.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/governance-officer/governance-definitions/by-search-string
Authorization: Bearer {{ivorToken}}
Content-Type: application/json

{
  "class" : "SearchStringRequestBody",
  "metadataElementTypeName": "GovernanceZone"
}

