/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright Contributors to the ODPi Egeria project. */
package org.odpi.openmetadata.frameworks.integration.openlineage;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

import java.net.URI;
import java.util.Objects;

import static com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility.NONE;
import static com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility.PUBLIC_ONLY;

/**
 * This class represents the gcp_dataproc run facet registered by Google Cloud Dataproc.  It identifies the Dataproc job, batch or session that executed the run.
 * It follows the OpenLineage facet spec https://openlineage.io/spec/facets/1-0-0/GcpDataprocRunFacet.json#/$defs/GcpDataprocRunFacet.
 */
@JsonAutoDetect(getterVisibility=PUBLIC_ONLY, setterVisibility=PUBLIC_ONLY, fieldVisibility=NONE)
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown=true)
public class OpenLineageGcpDataprocRunFacet extends OpenLineageRunFacet
{
    private String appId = null;
    private String appName = null;
    private String batchId = null;
    private String batchUuid = null;
    private String clusterName = null;
    private String clusterUuid = null;
    private String jobId = null;
    private String jobUuid = null;
    private String projectId = null;
    private String queryNodeName = null;
    private String jobType = null;
    private String sessionId = null;
    private String sessionUuid = null;


    /**
     * Default constructor
     */
    public OpenLineageGcpDataprocRunFacet()
    {
        super(URI.create("https://openlineage.io/spec/facets/1-0-0/GcpDataprocRunFacet.json#/$defs/GcpDataprocRunFacet"));
    }


    /**
     * Return the application ID set by the resource manager.  For Spark jobs it is set in the Spark configuration.
     *
     * @return string
     */
    public String getAppId()
    {
        return appId;
    }


    /**
     * Set up the application ID set by the resource manager.  For Spark jobs it is set in the Spark configuration.
     *
     * @param appId string
     */
    public void setAppId(String appId)
    {
        this.appId = appId;
    }


    /**
     * Return the application name, provided by the user or defaulted by the resource manager.
     *
     * @return string
     */
    public String getAppName()
    {
        return appName;
    }


    /**
     * Set up the application name, provided by the user or defaulted by the resource manager.
     *
     * @param appName string
     */
    public void setAppName(String appName)
    {
        this.appName = appName;
    }


    /**
     * Return the resource id of the batch.  Populated only for Dataproc serverless batches.
     *
     * @return string
     */
    public String getBatchId()
    {
        return batchId;
    }


    /**
     * Set up the resource id of the batch.  Populated only for Dataproc serverless batches.
     *
     * @param batchId string
     */
    public void setBatchId(String batchId)
    {
        this.batchId = batchId;
    }


    /**
     * Return the UUID generated by the service when it created the batch.  Populated only for Dataproc serverless batches.
     *
     * @return string
     */
    public String getBatchUuid()
    {
        return batchUuid;
    }


    /**
     * Set up the UUID generated by the service when it created the batch.  Populated only for Dataproc serverless batches.
     *
     * @param batchUuid string
     */
    public void setBatchUuid(String batchUuid)
    {
        this.batchUuid = batchUuid;
    }


    /**
     * Return the cluster name, unique within a GCP project.  Populated only for Dataproc GCE workloads.
     *
     * @return string
     */
    public String getClusterName()
    {
        return clusterName;
    }


    /**
     * Set up the cluster name, unique within a GCP project.  Populated only for Dataproc GCE workloads.
     *
     * @param clusterName string
     */
    public void setClusterName(String clusterName)
    {
        this.clusterName = clusterName;
    }


    /**
     * Return the UUID generated by the service at the time of cluster creation.  Populated only for Dataproc GCE workloads.
     *
     * @return string
     */
    public String getClusterUuid()
    {
        return clusterUuid;
    }


    /**
     * Set up the UUID generated by the service at the time of cluster creation.  Populated only for Dataproc GCE workloads.
     *
     * @param clusterUuid string
     */
    public void setClusterUuid(String clusterUuid)
    {
        this.clusterUuid = clusterUuid;
    }


    /**
     * Return the job ID.  Populated only for Dataproc GCE workloads.
     *
     * @return string
     */
    public String getJobId()
    {
        return jobId;
    }


    /**
     * Set up the job ID.  Populated only for Dataproc GCE workloads.
     *
     * @param jobId string
     */
    public void setJobId(String jobId)
    {
        this.jobId = jobId;
    }


    /**
     * Return the UUID that uniquely identifies the job within the project.  Populated only for Dataproc GCE workloads.
     *
     * @return string
     */
    public String getJobUuid()
    {
        return jobUuid;
    }


    /**
     * Set up the UUID that uniquely identifies the job within the project.  Populated only for Dataproc GCE workloads.
     *
     * @param jobUuid string
     */
    public void setJobUuid(String jobUuid)
    {
        this.jobUuid = jobUuid;
    }


    /**
     * Return the GCP project ID that the resource belongs to.
     *
     * @return string
     */
    public String getProjectId()
    {
        return projectId;
    }


    /**
     * Set up the GCP project ID that the resource belongs to.
     *
     * @param projectId string
     */
    public void setProjectId(String projectId)
    {
        this.projectId = projectId;
    }


    /**
     * Return the name of the query node in the executed Spark plan, often used to describe the command being executed.
     *
     * @return string
     */
    public String getQueryNodeName()
    {
        return queryNodeName;
    }


    /**
     * Set up the name of the query node in the executed Spark plan, often used to describe the command being executed.
     *
     * @param queryNodeName string
     */
    public void setQueryNodeName(String queryNodeName)
    {
        this.queryNodeName = queryNodeName;
    }


    /**
     * Return the whether the process is a job (on a Dataproc cluster), a batch or a session.
     *
     * @return string
     */
    public String getJobType()
    {
        return jobType;
    }


    /**
     * Set up the whether the process is a job (on a Dataproc cluster), a batch or a session.
     *
     * @param jobType string
     */
    public void setJobType(String jobType)
    {
        this.jobType = jobType;
    }


    /**
     * Return the resource id of the session.  Populated only for Dataproc serverless interactive sessions.
     *
     * @return string
     */
    public String getSessionId()
    {
        return sessionId;
    }


    /**
     * Set up the resource id of the session.  Populated only for Dataproc serverless interactive sessions.
     *
     * @param sessionId string
     */
    public void setSessionId(String sessionId)
    {
        this.sessionId = sessionId;
    }


    /**
     * Return the UUID generated by the service when it created the session.  Populated only for Dataproc serverless interactive sessions.
     *
     * @return string
     */
    public String getSessionUuid()
    {
        return sessionUuid;
    }


    /**
     * Set up the UUID generated by the service when it created the session.  Populated only for Dataproc serverless interactive sessions.
     *
     * @param sessionUuid string
     */
    public void setSessionUuid(String sessionUuid)
    {
        this.sessionUuid = sessionUuid;
    }


    /**
     * Standard toString method.
     *
     * @return print out of variables in a JSON-style
     */
    @Override
    public String toString()
    {
        return "OpenLineageGcpDataprocRunFacet{" +
                       "appId='" + appId + '\'' +
                       ", appName='" + appName + '\'' +
                       ", batchId='" + batchId + '\'' +
                       ", batchUuid='" + batchUuid + '\'' +
                       ", clusterName='" + clusterName + '\'' +
                       ", clusterUuid='" + clusterUuid + '\'' +
                       ", jobId='" + jobId + '\'' +
                       ", jobUuid='" + jobUuid + '\'' +
                       ", projectId='" + projectId + '\'' +
                       ", queryNodeName='" + queryNodeName + '\'' +
                       ", jobType='" + jobType + '\'' +
                       ", sessionId='" + sessionId + '\'' +
                       ", sessionUuid='" + sessionUuid + '\'' +
                       ", _producer=" + get_producer() +
                       ", _schemaURL=" + get_schemaURL() +
                       ", additionalProperties=" + getAdditionalProperties() +
                       '}';
    }


    /**
     * Compare the values of the supplied object with those stored in the current object.
     *
     * @param objectToCompare supplied object
     * @return boolean result of comparison
     */
    @Override
    public boolean equals(Object objectToCompare)
    {
        if (this == objectToCompare)
        {
            return true;
        }
        if (objectToCompare == null || getClass() != objectToCompare.getClass())
        {
            return false;
        }
        if (! super.equals(objectToCompare))
        {
            return false;
        }
        OpenLineageGcpDataprocRunFacet that = (OpenLineageGcpDataprocRunFacet) objectToCompare;
        return Objects.equals(appId, that.appId) &&
                       Objects.equals(appName, that.appName) &&
                       Objects.equals(batchId, that.batchId) &&
                       Objects.equals(batchUuid, that.batchUuid) &&
                       Objects.equals(clusterName, that.clusterName) &&
                       Objects.equals(clusterUuid, that.clusterUuid) &&
                       Objects.equals(jobId, that.jobId) &&
                       Objects.equals(jobUuid, that.jobUuid) &&
                       Objects.equals(projectId, that.projectId) &&
                       Objects.equals(queryNodeName, that.queryNodeName) &&
                       Objects.equals(jobType, that.jobType) &&
                       Objects.equals(sessionId, that.sessionId) &&
                       Objects.equals(sessionUuid, that.sessionUuid);
    }


    /**
     * Return hash code based on properties.
     *
     * @return int
     */
    @Override
    public int hashCode()
    {
        return Objects.hash(super.hashCode(), appId, appName, batchId, batchUuid, clusterName, clusterUuid, jobId, jobUuid, projectId, queryNodeName, jobType, sessionId, sessionUuid);
    }
}
