/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright Contributors to the ODPi Egeria project. */
package org.odpi.openmetadata.frameworks.integration.openlineage;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

import java.net.URI;
import java.util.Objects;

import static com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility.NONE;
import static com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility.PUBLIC_ONLY;

/**
 * This class represents the errorMessage run facet.  It captures the error that caused the run to fail.
 * It follows the OpenLineage facet spec https://openlineage.io/spec/facets/1-0-1/ErrorMessageRunFacet.json#/$defs/ErrorMessageRunFacet.
 */
@JsonAutoDetect(getterVisibility=PUBLIC_ONLY, setterVisibility=PUBLIC_ONLY, fieldVisibility=NONE)
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown=true)
public class OpenLineageErrorMessageRunFacet extends OpenLineageRunFacet
{
    private String message = null;
    private String programmingLanguage = null;
    private String stackTrace = null;


    /**
     * Default constructor
     */
    public OpenLineageErrorMessageRunFacet()
    {
        super(URI.create("https://openlineage.io/spec/facets/1-0-1/ErrorMessageRunFacet.json#/$defs/ErrorMessageRunFacet"));
    }


    /**
     * Return the human-readable error message generated by the observed system.
     *
     * @return string
     */
    public String getMessage()
    {
        return message;
    }


    /**
     * Set up the human-readable error message generated by the observed system.
     *
     * @param message string
     */
    public void setMessage(String message)
    {
        this.message = message;
    }


    /**
     * Return the programming language the observed system uses.
     *
     * @return string
     */
    public String getProgrammingLanguage()
    {
        return programmingLanguage;
    }


    /**
     * Set up the programming language the observed system uses.
     *
     * @param programmingLanguage string
     */
    public void setProgrammingLanguage(String programmingLanguage)
    {
        this.programmingLanguage = programmingLanguage;
    }


    /**
     * Return the language-specific stack trace generated by the observed system.
     *
     * @return string
     */
    public String getStackTrace()
    {
        return stackTrace;
    }


    /**
     * Set up the language-specific stack trace generated by the observed system.
     *
     * @param stackTrace string
     */
    public void setStackTrace(String stackTrace)
    {
        this.stackTrace = stackTrace;
    }


    /**
     * Standard toString method.
     *
     * @return print out of variables in a JSON-style
     */
    @Override
    public String toString()
    {
        return "OpenLineageErrorMessageRunFacet{" +
                       "message='" + message + '\'' +
                       ", programmingLanguage='" + programmingLanguage + '\'' +
                       ", stackTrace='" + stackTrace + '\'' +
                       ", _producer=" + get_producer() +
                       ", _schemaURL=" + get_schemaURL() +
                       ", additionalProperties=" + getAdditionalProperties() +
                       '}';
    }


    /**
     * Compare the values of the supplied object with those stored in the current object.
     *
     * @param objectToCompare supplied object
     * @return boolean result of comparison
     */
    @Override
    public boolean equals(Object objectToCompare)
    {
        if (this == objectToCompare)
        {
            return true;
        }
        if (objectToCompare == null || getClass() != objectToCompare.getClass())
        {
            return false;
        }
        if (! super.equals(objectToCompare))
        {
            return false;
        }
        OpenLineageErrorMessageRunFacet that = (OpenLineageErrorMessageRunFacet) objectToCompare;
        return Objects.equals(message, that.message) &&
                       Objects.equals(programmingLanguage, that.programmingLanguage) &&
                       Objects.equals(stackTrace, that.stackTrace);
    }


    /**
     * Return hash code based on properties.
     *
     * @return int
     */
    @Override
    public int hashCode()
    {
        return Objects.hash(super.hashCode(), message, programmingLanguage, stackTrace);
    }
}
