/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright Contributors to the ODPi Egeria project. */

package org.odpi.openmetadata.contentpacks.core;

import org.odpi.openmetadata.adapters.connectors.EgeriaSolutionComponent;
import org.odpi.openmetadata.adapters.connectors.controls.AtlasDeployedImplementationType;
import org.odpi.openmetadata.adapters.connectors.controls.EgeriaDeployedImplementationType;
import org.odpi.openmetadata.adapters.connectors.controls.PostgresDeployedImplementationType;
import org.odpi.openmetadata.adapters.connectors.controls.UnityCatalogDeployedImplementationType;
import org.odpi.openmetadata.frameworks.openmetadata.refdata.DeployedImplementationType;
import org.odpi.openmetadata.frameworks.openmetadata.definitions.DeployedImplementationTypeDefinition;

import java.util.Arrays;
import java.util.List;

/**
 * The solution blueprints that describe the contents of the core content packs.
 */
public enum ContentPackSolutionBlueprint
{
    /**
     * Base Connector Types and Categories for connectors from the Egeria project along with metadata valid values, templates, and connectors for the basic types of technology supported by these connectors.
     */
    CORE_CONTENT_PACK("eb83f1a4-684b-4624-bdc8-6b394ce9cdc8",
                      "Egeria::SolutionBlueprint::CoreContentPack",
                      "Core Content Pack",
                      "CORE-CONTENT-PACK",
                      "Solution blueprint for a default setup.",
                      null,
                      new DeployedImplementationTypeDefinition[]{
                              DeployedImplementationType.JDBC_RELATIONAL_DATABASE,
                              DeployedImplementationType.TABULAR_DATA_SET,
                              DeployedImplementationType.AUDIT_LOG_DESTINATION_CONNECTOR
                      },
                      ContentPackDefinition.CORE_CONTENT_PACK),

    /**
     * Cataloguing and monitoring the Egeria infrastructure.
     */
    EGERIA_CONTENT_PACK("4d033711-0449-4d67-bf98-c7bfcae86b8c",
                        "Egeria::SolutionBlueprint::EgeriaContentPack",
                        "Egeria Content Pack",
                        "EGERIA-CONTENT-PACK",
                        "Solution blueprint containing integration connectors for working with Egeria's infrastructure.",
                        new String[]{
                                EgeriaDeployedImplementationType.OMAG_SERVER_PLATFORM.getSolutionComponentGUID(),
                                EgeriaDeployedImplementationType.METADATA_ACCESS_STORE.getSolutionComponentGUID()
                        },
                        null,
                        ContentPackDefinition.EGERIA_CONTENT_PACK),

    /**
     * Surveying and cataloguing files in the file system.
     */
    FILES_CONTENT_PACK("d89b489d-9661-41ee-838f-37454ebb70bf",
                       "Egeria::SolutionBlueprint::FilesContentPack",
                       "Files Content Pack",
                       "FILES-CONTENT-PACK",
                       "Solution blueprint containing integration connectors for working with files.",
                       new String[]{
                               RequestTypeDefinition.PRINT_SURVEY_REPORT.getSolutionComponentGUID()
                       },
                       new DeployedImplementationTypeDefinition[]{
                               DeployedImplementationType.FILE_SYSTEM_DIRECTORY,
                               DeployedImplementationType.CSV_FILE,
                               DeployedImplementationType.FILE
                       },
                       ContentPackDefinition.FILES_CONTENT_PACK),

    /**
     * Capture open lineage events and harvest assets and relationships from them.  Generate open lineage from running governance action processes. Save and distribute open lineage events both received from third parties and generated by Egeria.
     */
    OPEN_LINEAGE_CONTENT_PACK("368cd66f-1250-491a-9da1-7f70f2963fd1",
                              "Egeria::SolutionBlueprint::OpenLineageContentPack",
                              "Open Lineage Content Pack",
                              "OPEN-LINEAGE-CONTENT-PACK",
                              "Solution blueprint containing integration connectors for working with open lineage events.",
                              new String[]{
                                      EgeriaDeployedImplementationType.METADATA_ACCESS_STORE.getSolutionComponentGUID(),
                                      EgeriaSolutionComponent.OL_KAFKA_TOPIC.getGUID(),
                                      EgeriaSolutionComponent.OPEN_METADATA_TOPIC.getGUID(),
                                      EgeriaSolutionComponent.OL_PROXY.getGUID()
                              },
                              new DeployedImplementationTypeDefinition[]{
                                      DeployedImplementationType.FILE_SYSTEM_DIRECTORY,
                                      DeployedImplementationType.MARQUEZ_SERVER
                              },
                              ContentPackDefinition.OPEN_LINEAGE_CONTENT_PACK),

    /**
     * Reference data, templates, connectors, and governance services for working with Unity Catalog.
     */
    UNITY_CATALOG_CONTENT_PACK("548661f1-e792-4acd-8dc2-0aa41187d6d2",
                               "Egeria::SolutionBlueprint::UnityCatalogContentPack",
                               "Unity Catalog Content Pack",
                               "UNITY-CATALOG-CONTENT-PACK",
                               "Solution blueprint supporting the exchange of metadata between the open metadata ecosystem and Unity Catalog (UC).",
                               new String[]{
                                       RequestTypeDefinition.PRINT_SURVEY_REPORT.getSolutionComponentGUID()
                               },
                               new DeployedImplementationTypeDefinition[]{
                                       UnityCatalogDeployedImplementationType.OSS_UNITY_CATALOG_SERVER,
                                       UnityCatalogDeployedImplementationType.DB_UNITY_CATALOG_SERVER
                               },
                               ContentPackDefinition.UNITY_CATALOG_CONTENT_PACK),

    /**
     * Reference data, templates, connectors, and governance services for working with Apache Atlas.
     */
    APACHE_ATLAS_CONTENT_PACK("819a7239-f1dc-43af-8501-c7a551655373",
                              "Egeria::SolutionBlueprint::ApacheAtlasContentPack",
                              "Apache Atlas Content Pack",
                              "APACHE-ATLAS-CONTENT-PACK",
                              "Solution blueprint supporting integration connectors connecting to Apache Atlas.",
                              new String[]{
                                      RequestTypeDefinition.PRINT_SURVEY_REPORT.getSolutionComponentGUID()
                              },
                              new DeployedImplementationTypeDefinition[]{
                                      AtlasDeployedImplementationType.APACHE_ATLAS_SERVER
                              },
                              ContentPackDefinition.APACHE_ATLAS_CONTENT_PACK),

    /**
     * Reference data, templates, connectors, and governance services for working with a PostgreSQL Server.
     */
    POSTGRES_CONTENT_PACK("9c0e55dc-96b4-42de-8cd8-e4b2e2b92a38",
                          "Egeria::SolutionBlueprint::PostgresContentPack",
                          "PostgreSQL Content Pack",
                          "POSTGRESQL-CONTENT-PACK",
                          "Solution blueprint supporting integration connectors connecting to PostgreSQL Servers.",
                          new String[]{
                                  RequestTypeDefinition.PRINT_SURVEY_REPORT.getSolutionComponentGUID(),
                                  IntegrationConnectorDefinition.JDBC_CATALOGUER.getSolutionComponentGUID()
                          },
                          new DeployedImplementationTypeDefinition[]{
                                  PostgresDeployedImplementationType.POSTGRESQL_SERVER
                          },
                          ContentPackDefinition.POSTGRES_CONTENT_PACK),

    /**
     * Reference data, templates, connectors, and governance services for working with an Apache Kafka Server.
     */
    APACHE_KAFKA_CONTENT_PACK("a3c6e079-3630-46e9-bf90-339c21964a4e",
                              "Egeria::SolutionBlueprint::ApacheKafkaContentPack",
                              "Apache Kafka Content Pack",
                              "APACHE-KAFKA-CONTENT-PACK",
                              "Solution blueprint supporting integration connectors connecting to Apache Kafka.",
                              null,
                              new DeployedImplementationTypeDefinition[]{
                                      DeployedImplementationType.APACHE_KAFKA_TOPIC
                              },
                              ContentPackDefinition.APACHE_KAFKA_CONTENT_PACK),

    /**
     * Reference data, templates, connectors, and governance services for working with REST APIs via the swagger interface.
     */
    APIS_CONTENT_PACK("3a07c1f8-c810-4d53-9d28-4bbca1a6ea97",
                      "Egeria::SolutionBlueprint::APIsContentPack",
                      "Open APIs Content Pack",
                      "OPEN-APIS-CONTENT-PACK",
                      "Solution blueprint supporting integration connectors extracting Open API specifications to Open APIs via swagger.",
                      new String[]{
                              EgeriaDeployedImplementationType.METADATA_ACCESS_STORE.getSolutionComponentGUID()
                      },
                      new DeployedImplementationTypeDefinition[]{
                              DeployedImplementationType.REST_API_ENDPOINT
                      },
                      ContentPackDefinition.APIS_CONTENT_PACK),

    /**
     * Open metadata collections packaged into dynamic digital products.
     */
    PRODUCTS_CONTENT_PACK("ea509f7a-de1f-4864-bbbd-6f373f49e132",
                          "Egeria::SolutionBlueprint::OpenMetadataDigitalProductsContentPack",
                          "Open Metadata Digital Products Content Pack",
                          "OPEN-METADATA-DIGITAL-PRODUCTS-CONTENT-PACK",
                          "Solution blueprint showing the components that manage the Open Metadata Digital Product Catalog.",
                          new String[]{
                                  IntegrationConnectorDefinition.BABBAGE_ANALYTICAL_ENGINE.getSolutionComponentGUID(),
                                  EgeriaDeployedImplementationType.METADATA_ACCESS_STORE.getSolutionComponentGUID()
                          },
                          null,
                          ContentPackDefinition.PRODUCTS_CONTENT_PACK),

    /**
     * Monitoring, analysis, and capture of insight into organization activity and effectiveness.
     */
    ORGANIZATION_INSIGHT_CONTENT_PACK("b36c6cc7-26f2-4b9b-b3e3-496f738c8927",
                                      "Egeria::SolutionBlueprint::OrganizationInsightContentPack",
                                      "Organization Insight Content Pack",
                                      "ORGANIZATION-INSIGHT-CONTENT-PACK",
                                      "Solution blueprint describing the components that deliver organization insight to the open metadata ecosystem.",
                                      new String[]{
                                              IntegrationConnectorDefinition.BABBAGE_ANALYTICAL_ENGINE.getSolutionComponentGUID(),
                                              EgeriaDeployedImplementationType.METADATA_ACCESS_STORE.getSolutionComponentGUID()
                                      },
                                      null,
                                      ContentPackDefinition.ORGANIZATION_INSIGHT_CONTENT_PACK),

    ;

    private final String                                 solutionBlueprintGUID;
    private final String                                 solutionBlueprintQualifiedName;
    private final String                                 solutionBlueprintDisplayName;
    private final String                                 solutionBlueprintIdentifier;
    private final String                                 solutionBlueprintDescription;
    private final String[]                               extraSolutionComponentGUIDs;
    private final DeployedImplementationTypeDefinition[] deployedImplementationTypes;
    private final ContentPackDefinition                  contentPackDefinition;


    ContentPackSolutionBlueprint(String                                 solutionBlueprintGUID,
                                 String                                 solutionBlueprintQualifiedName,
                                 String                                 solutionBlueprintDisplayName,
                                 String                                 solutionBlueprintIdentifier,
                                 String                                 description,
                                 String[]                               extraSolutionComponentGUIDs,
                                 DeployedImplementationTypeDefinition[] deployedImplementationTypes,
                                 ContentPackDefinition                  contentPackDefinition)
    {
        this.solutionBlueprintGUID          = solutionBlueprintGUID;
        this.solutionBlueprintQualifiedName = solutionBlueprintQualifiedName;
        this.solutionBlueprintDisplayName   = solutionBlueprintDisplayName;
        this.solutionBlueprintIdentifier    = solutionBlueprintIdentifier;
        this.solutionBlueprintDescription   = description;
        this.extraSolutionComponentGUIDs    = extraSolutionComponentGUIDs;
        this.deployedImplementationTypes    = deployedImplementationTypes;
        this.contentPackDefinition          = contentPackDefinition;
    }


    /**
     * Return the unique identifier for the solution blueprint.
     *
     * @return string
     */
    public String getSolutionBlueprintGUID()
    {
        return solutionBlueprintGUID;
    }


    /**
     * Return the unique name of the solution blueprint.
     *
     * @return string
     */
    public String getSolutionBlueprintQualifiedName()
    {
        return solutionBlueprintQualifiedName;
    }


    /**
     * Return the name of the solution blueprint.
     *
     * @return string
     */
    public String getSolutionBlueprintDisplayName()
    {
        return solutionBlueprintDisplayName;
    }


    /**
     * Return the identifier of the solution blueprint.
     *
     * @return string
     */
    public String getSolutionBlueprintIdentifier()
    {
        return solutionBlueprintIdentifier;
    }


    /**
     * Return the description of the solution blueprint.
     *
     * @return string
     */
    public String getDescription()
    {
        return solutionBlueprintDescription;
    }


    /**
     * Return the solution components included in the solution blueprint. membershipRationale="related component"
     *
     * @return list of guids or null
     */
    public List<String> getExtraSolutionComponentGUIDs()
    {
        if (extraSolutionComponentGUIDs == null)
        {
            return null;
        }

        return Arrays.asList(extraSolutionComponentGUIDs);
    }


    /**
     * Return the list of technology types integrated into this solution. membershipRationale="interacting with"
     *
     * @return list of definitions or null
     */
    public List<DeployedImplementationTypeDefinition> getDeployedImplementationTypes()
    {
        if (deployedImplementationTypes == null)
        {
            return null;
        }

        return Arrays.asList(deployedImplementationTypes);
    }


    /**
     * Get identifier of content pack where this definition should be located.
     *
     * @return content pack definition
     */
    public ContentPackDefinition getContentPackDefinition()
    {
        return contentPackDefinition;
    }


    /**
     * JSON-style toString
     *
     * @return return string containing the property names and values
     */
    @Override
    public String toString()
    {
        return " SolutionBlueprint{name='" + name() + "'}";
    }
}
