/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright Contributors to the ODPi Egeria project. */

package org.odpi.openmetadata.contentpacks.core;

/**
 * Identifies the content pack containing specific templates, integration connectors and governance services belong to.
 */
public enum ContentPackDefinition
{
    /**
     * Base Connector Types and Categories for connectors from the Egeria project along with metadata valid values, templates and connectors for the basic types of technology supported by these connectors.
     */
    CORE_CONTENT_PACK("09450b83-20ff-4a8b-a8fb-f9b527bbcba6",
                      "CoreContentPack",
                      "Base Connector Types and Categories for connectors from the Egeria project along with metadata valid values, templates and connectors for the basic types of technology supported by these connectors.",
                      "CoreContentPack.omarchive"),

    /**
     * Cataloguing and monitoring the Egeria infrastructure.
     */
    EGERIA_CONTENT_PACK("75e175c7-0dbb-45cc-966b-1f0462420e92",
                        "EgeriaContentPack",
                        "Cataloguing and monitoring the Egeria infrastructure.",
                        "EgeriaContentPack.omarchive"),

    /**
     * Surveying and cataloguing files in the file system.
     */
    FILES_CONTENT_PACK("8047d637-1ad4-4fde-9142-41ad86331da2",
                       "FilesContentPack",
                       "Surveying and cataloguing files in the file system.",
                       "FilesContentPack.omarchive"),

    /**
     * Capture open lineage events and harvest assets and relationships from them.  Generate open lineage from running governance action processes. Save and distribute open lineage events both received from third parties and generated by Egeria.
     */
    OPEN_LINEAGE_CONTENT_PACK("268fa7a8-cbc1-47e4-a1d6-e6f8b6fde234",
                              "OpenLineageContentPack",
                              "Capture open lineage events and harvest assets and relationships from them.  Generate open lineage from running governance action processes. Save and distribute open lineage events both received from third parties and generated by Egeria.",
                              "OpenLineageContentPack.omarchive"),

    /**
     * Reference data, templates, connectors and governance services for working with Unity Catalog.
     */
    UNITY_CATALOG_CONTENT_PACK("e6756296-3fa3-4aa3-9450-0dc44b8beae2",
                               "UnityCatalogContentPack",
                               "Reference data, templates, connectors and governance services for working with Unity Catalog.",
                               "UnityCatalogContentPack.omarchive"),

    /**
     * Reference data, templates, connectors and governance services for working with Apache Atlas.
     */
    APACHE_ATLAS_CONTENT_PACK("59c0beb4-a025-4451-8125-16a853095a50",
                              "ApacheAtlasContentPack",
                              "Reference data, templates, connectors and governance services for working with Apache Atlas.",
                              "ApacheAtlasContentPack.omarchive"),

    /**
     * Reference data, templates, connectors and governance services for working with a PostgreSQL Server.
     */
    POSTGRES_CONTENT_PACK("8be11e8d-3964-40c7-88cd-403526725523",
                          "PostgresContentPack",
                          "Reference data, templates, connectors and governance services for working with a PostgreSQL Server.",
                          "PostgresContentPack.omarchive"),

    /**
     * Reference data, templates, connectors and governance services for working with an Apache Kafka Server.
     */
    APACHE_KAFKA_CONTENT_PACK("b70b4a96-6fed-4411-ad68-1ca48434c5e4",
                              "ApacheKafkaContentPack",
                              "Reference data, templates, connectors and governance services for working with an Apache Kafka Server.",
                              "ApacheKafkaContentPack.omarchive"),

    /**
     * Connectors and governance services used to enable observability functions on Egeria's infrastructure.
     */
    NANNY_CONTENT_PACK("878b2e0f-6867-43b1-880c-8ee30e88bacb",
                       "EgeriaObservabilityContentPack",
                       "Connectors and governance services used to enable observability functions on Egeria's infrastructure.",
                       "ObservabilityContentPack.omarchive"),

    /**
     * Reference data, templates, connectors and governance services for working with REST APIs via the swagger interface.
     */
    APIS_CONTENT_PACK("fc0a295b-9a6c-481a-ac8b-8ee4ce457335",
                      "APIsContentPack",
                      "Reference data, templates, connectors and governance services for working with REST APIs via the swagger interface.",
                      "APIsContentPack.omarchive"),

    /**
     * Open metadata collections packaged into dynamic digital products.
     */
    PRODUCTS_CONTENT_PACK("e8e06304-2eb9-4ebe-bb8c-1ae44635244b",
                          "JacquardHarvesterContentPack",
                          "Open metadata collections packaged into dynamic digital products.",
                          "JacquardHarvesterContentPack.omarchive"),

    /**
     * Monitoring, analysis and capture of insight into organization activity and effectiveness.
     */
    ORGANIZATION_INSIGHT_CONTENT_PACK("17f586b1-27f2-4714-adeb-e0074f379240",
                                      "OrganizationInsightContentPack",
                                      "Monitoring, analysis and capture of insight into organization activity and effectiveness.",
                                      "OrganizationInsightContentPack.omarchive"),
    ;

    private final String archiveGUID;
    private final String archiveName;
    private final String archiveDescription;
    private final String archiveFileName;


    /**
     * Constructor
     *
     * @param archiveFileName name of the archive file
     */
    ContentPackDefinition(String archiveGUID, String archiveName, String archiveDescription, String archiveFileName)
    {
        this.archiveGUID        = archiveGUID;
        this.archiveName        = archiveName;
        this.archiveDescription = archiveDescription;
        this.archiveFileName    = archiveFileName;
    }


    /**
     * Return the unique name of the archive.
     *
     * @return guid
     */
    public String getArchiveGUID()
    {
        return archiveGUID;
    }


    /**
     * Return the display name of the archive.
     *
     * @return name
     */
    public String getArchiveName()
    {
        return archiveName;
    }


    /**
     * Return the description of the contents of the archive.
     *
     * @return text
     */
    public String getArchiveDescription()
    {
        return archiveDescription;
    }


    /**
     * Name of the file name to use.
     *
     * @return string
     */
    public String getArchiveFileName()
    {
        return archiveFileName;
    }


    /**
     * JSON-style toString
     *
     * @return return string containing the property names and values
     */
    @Override
    public String toString()
    {
        return "ContentPackDefinition{fileName='" + archiveFileName + "'}";
    }
}
