/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright Contributors to the ODPi Egeria project. */

package org.odpi.openmetadata.contentpacks.core;

/**
 * Identifies the content pack containing specific templates, integration connectors and governance services belong to.
 */
public enum ContentPackDefinition
{
    /**
     * Base Connector Types and Categories for connectors from the Egeria project along with metadata valid values, templates, and connectors for the basic types of technology supported by these connectors.
     */
    CORE_CONTENT_PACK("09450b83-20ff-4a8b-a8fb-f9b527bbcba6",
                      "CoreContentPack",
                      "Base Connector Types and Categories for connectors from the Egeria project along with metadata valid values, templates, and connectors for the basic types of technology supported by these connectors.",
                      "CoreContentPack.omarchive"),

    /**
     * Cataloguing and monitoring the Egeria infrastructure.
     */
    EGERIA_CONTENT_PACK("75e175c7-0dbb-45cc-966b-1f0462420e92",
                        "EgeriaContentPack",
                        "Cataloguing and monitoring the Egeria infrastructure.",
                        "EgeriaContentPack.omarchive"),

    /**
     * Surveying and cataloguing files in the file system.
     */
    FILES_CONTENT_PACK("8047d637-1ad4-4fde-9142-41ad86331da2",
                       "FilesContentPack",
                       "Surveying and cataloguing files in the file system.",
                       "FilesContentPack.omarchive"),

    /**
     * Capture open lineage events and harvest assets and relationships from them.  Generate open lineage from running governance action processes. Save and distribute open lineage events both received from third parties and generated by Egeria.
     */
    OPEN_LINEAGE_CONTENT_PACK("268fa7a8-cbc1-47e4-a1d6-e6f8b6fde234",
                              "OpenLineageContentPack",
                              "Capture open lineage events and harvest assets and relationships from them.  Generate open lineage from running governance action processes. Save and distribute open lineage events both received from third parties and generated by Egeria.",
                              "OpenLineageContentPack.omarchive"),

    /**
     * Reference data, templates, connectors, and governance services for working with Unity Catalog.
     */
    UNITY_CATALOG_CONTENT_PACK("e6756296-3fa3-4aa3-9450-0dc44b8beae2",
                               "UnityCatalogContentPack",
                               "Reference data, templates, connectors, and governance services for working with Unity Catalog.",
                               "UnityCatalogContentPack.omarchive"),

    /**
     * Reference data, templates, connectors, and governance services for working with Apache Atlas.
     */
    APACHE_ATLAS_CONTENT_PACK("59c0beb4-a025-4451-8125-16a853095a50",
                              "ApacheAtlasContentPack",
                              "Reference data, templates, connectors, and governance services for working with Apache Atlas.",
                              "ApacheAtlasContentPack.omarchive"),

    /**
     * Reference data, templates, connectors, and governance services for working with a PostgreSQL Server.
     */
    POSTGRES_CONTENT_PACK("8be11e8d-3964-40c7-88cd-403526725523",
                          "PostgresContentPack",
                          "Reference data, templates, connectors, and governance services for working with a PostgreSQL Server. PostgreSQL is an advanced open source relational database. Egeria's content pack for PostgreSQL provides templates for PostgreSQL services, databases and tables along with function to survey the contents of PostgreSQL databases and catalog their schemas.",
                          "PostgresContentPack.omarchive"),

    /**
     * Reference data, templates, connectors, and governance services for working with an Apache Kafka Server.
     */
    APACHE_KAFKA_CONTENT_PACK("b70b4a96-6fed-4411-ad68-1ca48434c5e4",
                              "ApacheKafkaContentPack",
                              "Reference data, templates, connectors, and governance services for working with an Apache Kafka Server.",
                              "ApacheKafkaContentPack.omarchive"),

    /**
     * Reference data, templates, connectors, and governance services for working with REST APIs via the swagger interface.
     */
    APIS_CONTENT_PACK("fc0a295b-9a6c-481a-ac8b-8ee4ce457335",
                      "APIsContentPack",
                      "Reference data, templates, connectors, and governance services for working with REST APIs via the swagger interface.",
                      "APIsContentPack.omarchive"),

    /**
     * Open metadata collections packaged into dynamic digital products.
     */
    PRODUCTS_CONTENT_PACK("e8e06304-2eb9-4ebe-bb8c-1ae44635244b",
                          "OpenMetadataDigitalProductsContentPack",
                          "Open metadata collections packaged into dynamic digital products.",
                          "OpenMetadataDigitalProductsContentPack.omarchive"),

    /**
     * Monitoring, analysis, and capture of insight into organization activity and effectiveness.
     */
    ORGANIZATION_INSIGHT_CONTENT_PACK("17f586b1-27f2-4714-adeb-e0074f379240",
                                      "OrganizationInsightContentPack",
                                      "Monitoring, analysis, and capture of insight into organization activity and effectiveness.",
                                      "OrganizationInsightContentPack.omarchive"),

    /**
     * Reference data, templates, connectors, and governance services for working with a Microsoft SQL Server.
     */
    MSSQL_CONTENT_PACK("97c61fb6-01ed-4661-9537-67e3f61b1f48",
                       "MSSQLContentPack",
                       "Reference data, templates, connectors, and governance services for working with a Microsoft SQL Server. Egeria's content pack for Microsoft SQL Server provides templates for Microsoft SQL Server services and databases along with function to survey the contents of Microsoft SQL Server databases and catalog their schemas.",
                       "MSSQLContentPack.omarchive"),

    /**
     * Reference data, templates, connectors, and governance services for working with an Oracle Database Server.
     */
    ORACLE_CONTENT_PACK("259bde48-2363-4463-9477-0a80734668d7",
                        "OracleContentPack",
                        "Reference data, templates, connectors, and governance services for working with an Oracle Database Server. Egeria's content pack for Oracle Database provides templates for Oracle Database servers and pluggable databases along with function to survey the contents of Oracle pluggable databases and catalog their schemas.",
                        "OracleContentPack.omarchive"),

    /**
     * Reference data, templates, connectors, and governance services for working with an IBM Db2 for Linux, UNIX and Windows Server.
     */
    DB2LUW_CONTENT_PACK("e959ce42-46f6-445b-a05f-11cbe15f73e0",
                        "DB2LUWContentPack",
                        "Reference data, templates, connectors, and governance services for working with an IBM Db2 for Linux, UNIX and Windows (LUW / UDB) Server. Egeria's content pack for Db2 for Linux, UNIX and Windows provides templates for Db2 servers and databases along with function to survey the contents of Db2 databases and catalog their schemas.",
                        "DB2LUWContentPack.omarchive"),

    /**
     * Reference data, templates, connectors, and governance services for working with a DuckDB database.
     */
    DUCKDB_CONTENT_PACK("41445a34-7648-4e30-b3df-9e5312a10a50",
                        "DuckDBContentPack",
                        "Reference data, templates, connectors, and governance services for working with a DuckDB database. Egeria's content pack for DuckDB provides a template for DuckDB databases along with function to survey the contents of a DuckDB database - including its attached and federated data sources - and catalog its schemas.",
                        "DuckDBContentPack.omarchive"),
    ;

    private final String   archiveGUID;
    private final String   archiveName;
    private final String   archiveDescription;
    private final String   archiveFileName;



    /**
     * Constructor
     *
     * @param archiveFileName name of the archive file
     */
    ContentPackDefinition(String archiveGUID,
                          String archiveName,
                          String archiveDescription,
                          String archiveFileName)
    {
        this.archiveGUID                     = archiveGUID;
        this.archiveName                     = archiveName;
        this.archiveDescription              = archiveDescription;
        this.archiveFileName                 = archiveFileName;
    }


    /**
     * Return the unique name of the archive.
     *
     * @return guid
     */
    public String getArchiveGUID()
    {
        return archiveGUID;
    }


    /**
     * Return the display name of the archive.
     *
     * @return name
     */
    public String getArchiveName()
    {
        return archiveName;
    }


    /**
     * Return the description of the contents of the archive.
     *
     * @return text
     */
    public String getArchiveDescription()
    {
        return archiveDescription;
    }


    /**
     * Name of the file name to use.
     *
     * @return string
     */
    public String getArchiveFileName()
    {
        return archiveFileName;
    }


    /**
     * JSON-style toString
     *
     * @return return string containing the property names and values
     */
    @Override
    public String toString()
    {
        return "ContentPackDefinition{fileName='" + archiveFileName + "'}";
    }
}
