# Egeria-test-catalog-processes
# Use the Automated Curaiton API to run the cataloging processes

@baseURL=https://localhost:7443
@viewServer=view-server

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "peterprofile",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}

###
# =====================================================================================================================
# Work with Integration daemon.
# https://egeria-project.org/types/00040-Software-Servers/

###
# @name getServersByName
# Returns the list of servers with a particular name.  The name is specified in the filter.

POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/runtime-manager/software-servers/by-name
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "filter" : "integration-daemon"
}

> {% client.global.set("integrationDaemonGUID", response.body.elements[0].elementHeader.guid); %}


###
# =====================================================================================================================
# Catalog Unity Catalog
#

###
# @name initiate Catalog Unity Catalog GovernanceActionProcess
# Catalog a usinty catalog server and all of its internal catalogs.

POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/automated-curation/governance-action-processes/initiate
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "processQualifiedName": "UnityCatalogServer::CreateAsCatalogTargetGovernanceActionProcess",
  "requestParameters" : {
    "hostURL" : "http://localhost",
    "portNumber" : "8087",
    "serverName" : "Coco Unity Catalog",
    "versionIdentifier" : "v0.3.0-SNAPSHOT",
    "description" : "Coco's instance of the Unity Catalog (UC) Server.",
    "serverUserId" : "uc1"
  }
}

> {% client.global.set("ucProcessGUID", response.body.guid); %}

###
# @name getGovernanceActionProcessGraph
# Retrieve the governance action process metadata element with the supplied unique identifier
# along with the flow definition describing its implementation.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/governance-officer/governance-action-processes/{{ucProcessGUID}}/graph
Authorization: Bearer {{token}}

###
# @name getActiveEngineActions
# Retrieve the engine actions that are still in process.
GET {{baseURL}}/servers/{{viewServer}}/api/open-metadata/automated-curation/engine-actions/active?startFrom=0&pageSize=5
Authorization: Bearer {{token}}


###
# @name refreshConnectors
# Issue a refresh() request on all connectors running in the integration daemon, or a specific connector if the connector name is specified.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/runtime-manager/integration-daemons/{{integrationDaemonGUID}}/integration-connectors/refresh
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NameRequestBody",
  "name" : "UnityCatalogServerSynchronizer"
}


###
# @name refreshConnectors
# Issue a refresh() request on all connectors running in the integration daemon, or a specific connector if the connector name is specified.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/runtime-manager/integration-daemons/{{integrationDaemonGUID}}/integration-connectors/refresh
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NameRequestBody",
  "name" : "UnityCatalogInsideCatalogSynchronizer"
}


###
# =====================================================================================================================
# Catalog PostgreSQL Server
#

###
# @name initiate Catalog PostgreSQL Server GovernanceActionProcess
# Catalog a usinty catalog server and all of its internal catalogs.

POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/automated-curation/governance-action-processes/initiate
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "processQualifiedName": "PostgreSQLServer::CreateAsCatalogTargetGovernanceActionProcess",
  "requestParameters" : {
    "serverName" : "LocalPostgreSQL1",
    "hostIdentifier" : "localhost",
    "portNumber" : "5432",
    "secretsStorePathName" : "secrets/integration.omsecrets",
    "secretsCollectionName" : "PostgreSQL Server:LocalPostgreSQL1",
    "versionIdentifier" : "1.0",
    "description" : "PostgreSQL database in egeria-workspaces."
  }
}

> {% client.global.set("psProcessGUID", response.body.guid); %}

###
# @name getGovernanceActionProcessGraph
# Retrieve the governance action process metadata element with the supplied unique identifier
# along with the flow definition describing its implementation.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/governance-officer/governance-action-processes/{{psProcessGUID}}/graph
Authorization: Bearer {{token}}

###
# @name getActiveEngineActions
# Retrieve the engine actions that are still in process.
GET {{baseURL}}/servers/{{viewServer}}/api/open-metadata/automated-curation/engine-actions/active?startFrom=0&pageSize=5
Authorization: Bearer {{token}}


###
# @name refreshConnectors
# Issue a refresh() request on all connectors running in the integration daemon, or a specific connector if the connector name is specified.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/runtime-manager/integration-daemons/{{integrationDaemonGUID}}/integration-connectors/refresh
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NameRequestBody",
  "name" : "PostgreSQLServerCataloguer"
}


###
# @name refreshConnectors
# Issue a refresh() request on all connectors running in the integration daemon, or a specific connector if the connector name is specified.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/runtime-manager/integration-daemons/{{integrationDaemonGUID}}/integration-connectors/refresh
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NameRequestBody",
  "name" : "JDBCDatabaseCatalogue"
}
