# Egeria-create-client-side-secrets
# This file illustrates some different patters for client-side-secrets
# https://egeria-project.org/concepts/client-side-secret

@baseURL=https://localhost:9443
@viewServer=view-server

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "peterprofile",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}


###
#=====================================================================================================================
# If the secrets file does not exist then create a new one.  It is possible to store many cient side secrets in a
# single secrets store.
###
# @name createElementFromTemplate (Secrets Store File)
# Create a new element from a template.
# Further Information: https://egeria-project.org/features/templated-cataloguing/overview/
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/automated-curation/catalog-templates/new-element
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "templateGUID" : "130d819e-e17d-46bf-bfea-d09d862e341f",
  "isOwnAnchor" : true,
  "placeholderPropertyValues" : {
    "fileSystemName" : "",
    "filePathName" : "secrets/mySecrets.omsecrets",
    "fileName" : "Add file name without enclosing directory names, eg mySecrets.omsecrets",
    "description" : "Add description",
    "fileType" : "Open Metadata Secrets Store File",
    "fileExtension" : "omsecrets",
    "fileEncoding" : "YAML",
    "versionIdentifier" : "Add version identifier eg V1.0"
  }
}

> {% client.global.set("secretsStoreGUID", response.body.guid); %}

###


###
#=====================================================================================================================
# A secret that provides the userId and password for the remote server

###
# @name saveClientSideSecret
# Creates or replaces the details of a client-side secret in the requested secret store.
#
# @param serverName       name of called server
# @param secretsStoreGUID unique identifier of secret store asset
# @param urlMarker        view service URL marker
# @param requestBody      details of the secrets collection
# @return a list of projects
# InvalidParameterException  one of the parameters is null or invalid.
# PropertyServerException    a problem retrieving information from the property server(s).
# UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/automated-curation/secrets-stores/{{secretsStoreGUID}}/client-side-secret/save
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class": "SecretsCollectionRequestBody",
  "secretsCollection": {
    "collectionName": "System1Secret",
    "displayName": "Secret For accessing System 1",
    "description": "This secret includes a userId and password.  This is typically added to the HTTP header using Basic Authentication.",
    "refreshTimeInterval": 60,
    "secrets": {
      "userId" : "sys1User",
      "clearPassword" : "secret"
    }
  }
}


###
#=====================================================================================================================
# A secret that passes a hard-coded bearer token for the remote server

###
# @name saveClientSideSecret
# Creates or replaces the details of a client-side secret in the requested secret store.
#
# @param serverName       name of called server
# @param secretsStoreGUID unique identifier of secret store asset
# @param urlMarker        view service URL marker
# @param requestBody      details of the secrets collection
# @return a list of projects
# InvalidParameterException  one of the parameters is null or invalid.
# PropertyServerException    a problem retrieving information from the property server(s).
# UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/automated-curation/secrets-stores/{{secretsStoreGUID}}/client-side-secret/save
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class": "SecretsCollectionRequestBody",
  "secretsCollection": {
    "collectionName": "System2Secret",
    "displayName": "Secret For accessing System 2",
    "description": "This secret sets up a hardcoded token.  The 'accessToken' property is recognized as a bearer token for REST API calls.",
    "refreshTimeInterval": 60,
    "secrets": {
      "accessToken" : "Paste token here"
    }
  }
}


###
#=====================================================================================================================
# A secret that provides the userId and password for a Bearer token service

###
# @name saveClientSideSecret
# Creates or replaces the details of a client-side secret in the requested secret store.
#
# @param serverName       name of called server
# @param secretsStoreGUID unique identifier of secret store asset
# @param urlMarker        view service URL marker
# @param requestBody      details of the secrets collection
# @return a list of projects
# InvalidParameterException  one of the parameters is null or invalid.
# PropertyServerException    a problem retrieving information from the property server(s).
# UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/automated-curation/secrets-stores/{{secretsStoreGUID}}/client-side-secret/save
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class": "SecretsCollectionRequestBody",
  "secretsCollection": {
    "collectionName": "System3Secret",
    "displayName": "Secret For accessing System 3",
    "description": "The properties below describe a REST API call to create a token. This example calls Egeria's token service where the token is the response.",
    "refreshTimeInterval": 60,
    "tokenAPI": {
      "httpRequestType": "POST",
      "url": "https://localhost:9443/api/token",
      "contentType": "application/json",
      "requestBody": {
        "userId" : "sys3User",
        "password" : "secret"
      }
    }
  }
}


###
#=====================================================================================================================
# A secret that provides the userId and password for a Bearer token service with a mapped response

###
# @name saveClientSideSecret
# Creates or replaces the details of a client-side secret in the requested secret store.
#
# @param serverName       name of called server
# @param secretsStoreGUID unique identifier of secret store asset
# @param urlMarker        view service URL marker
# @param requestBody      details of the secrets collection
# @return a list of projects
# InvalidParameterException  one of the parameters is null or invalid.
# PropertyServerException    a problem retrieving information from the property server(s).
# UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/automated-curation/secrets-stores/{{secretsStoreGUID}}/client-side-secret/save
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class": "SecretsCollectionRequestBody",
  "secretsCollection": {
    "collectionName": "System4Secret",
    "displayName": "Secret For accessing System 4",
    "description": "The properties below describe a REST API call to create a token. This example calls a token service where the token is returned as part of a larger response and the 'responseBodyMapping' is used to locate the token in the 'bearerToken' property.",
    "refreshTimeInterval": 60,
    "tokenAPI": {
      "httpRequestType": "GET",
      "url": "https://localhost:4555/api/token",
      "contentType": "application/json",
      "requestBody": {
        "userId" : "sys4User",
        "password" : "secret"
      },
      "responseBodyMapping": {
        "bearerToken" : "accessToken"
      }
    }
  }
}
