
#@ucURL=http://localhost:8080
@ucURL=http://egeria.pdr-associates.com:8070

###
# @name list schemas
GET {{ucURL}}/api/2.1/unity-catalog/schemas?catalog_name=unity&max_results=10

###
# @name create schema
POST {{ucURL}}/api/2.1/unity-catalog/schemas
Content-Type: application/json

{
  "name": "test4schema1",
  "catalog_name" : "clinical_trials",
  "comment": "Test catalog4 schema 1",
  "properties": {
    "egeriaGUID" : "c14d6b99-7202-4f04-a05d-49f0fdd7373d"
  }
}

###
# @name create schema
POST {{ucURL}}/api/2.1/unity-catalog/schemas
Content-Type: application/json

{
  "name": "clinical_trial_drop_foot",
  "catalog_name" : "unity",
  "comment": "Example clinical trail used for education and testing of governance procedures."
}


###
# @name get schema
GET {{ucURL}}/api/2.1/unity-catalog/schemas/test.test4schema1
Content-Type: application/json


###
# @name patch schema
PATCH {{ucURL}}/api/2.1/unity-catalog/schemas/test.test4schema1
Content-Type: application/json

{
  "new_name" : "test4schema2",
  "comment" : "Change name to test4schema2",
  "properties": {
    "egeriaGUID" : "c14d6b99-7202-4f04-a05d-49f0fdd7373d"
  }
}

###
# @name delete schema
DELETE {{ucURL}}/api/2.1/unity-catalog/schemas/clinical_trials.clinical_trial_drop_foot
Content-Type: application/json

