
@ucURL=http://localhost:8080
#ucURL=http://egeria.pdr-associates.com:8070

###
# @name list volumes
GET {{ucURL}}/api/2.1/unity-catalog/volumes?catalog_name=new_catalog&schema_name=new_schema&max_results=10

###
# @name create volume
POST {{ucURL}}/api/2.1/unity-catalog/volumes
Content-Type: application/json

{
  "name": "weekly_measurements",
  "catalog_name" : "unity",
  "schema_name": "clinical_trial_drop_foot",
  "comment": "Weekly measurements for patients on clinical trial",
  "volume_type": "EXTERNAL",
  "storage_location": "/Users/amandachessell/Code/uc/unitycatalog/etc/data/external/unity/clinical_trial_drop_foot/volumes/weekly_measurements/"
}

###
# @name get volume
GET {{ucURL}}/api/2.1/unity-catalog/volumes/test.test4schema1.volume1
Content-Type: application/json


###
# @name patch volume
PATCH {{ucURL}}/api/2.1/unity-catalog/volumes/test.test4schema1.test4volume1
Content-Type: application/json

{
  "new_name" : "volume1",
  "comment" : "This is an updated comment"
}

###
# @name delete volume
DELETE {{ucURL}}/api/2.1/unity-catalog/volumes/new_catalog.new_schema.new_volume
Content-Type: application/json

