
@ucURL=http://localhost:8080

###
# @name list functions
GET {{ucURL}}/api/2.1/unity-catalog/functions?catalog_name=test&schema_name=test4schema1&max_results=10

###
# @name create function
POST {{ucURL}}/api/2.1/unity-catalog/functions
Content-Type: application/json

{
  "function_info" :
  {
    "name": "createWisdom",
    "catalog_name" : "test",
    "schema_name" : "test4schema1",
    "comment": "Test catalog4 function 1",
    "parameter_style" : "S",
    "routine_body" : "EXTERNAL",
    "external_language" : "Java",
    "security_type" : "DEFINER"
  }
}

###
# @name get function
GET {{ucURL}}/api/2.1/unity-catalog/functions/test.test4schema1.createWisdom
Content-Type: application/json


###
# @name delete function
DELETE {{ucURL}}/api/2.1/unity-catalog/functions/test.test4schema1.createWisdom
Content-Type: application/json

