
@ucURL=http://localhost:8087
#@ucURL=http://egeria.pdr-associates.com:8070

@baseURL=https://localhost:9443
@viewServer=qs-view-server

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "peterprofile",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}

###
# =====================================================================================================================
# Set up Unity Catalog ...

###
# @name create catalog
POST {{ucURL}}/api/2.1/unity-catalog/catalogs
Content-Type: application/json

{
  "name": "clinical_trials",
  "comment": "Clinical trials data for personalized medicine research."
}


###
# @name delete volume
DELETE {{ucURL}}/api/2.1/unity-catalog/volumes/clinical_trials.teddy_bear_drop_foot.weekly_measurements
Content-Type: application/json


###
# @name delete schema
DELETE {{ucURL}}/api/2.1/unity-catalog/schemas/clinical_trials.teddy_bear_drop_foot
Content-Type: application/json

###
# Remember to delete files in data lake
###
# =====================================================================================================================
# These commands add the CocoComboArchive to active-metadata-store and a new governance engine for clinical trials
# to engine-host.  They use IntelliJ's HTTP Client.
#

@adminUserId=garygeeke

###
# @name Load CocoComboArchive.omarchive metadata archive file
# Load a file that contains open metadata types and instances.
POST {{baseURL}}/open-metadata/server-operations/users/{{adminUserId}}/servers/qs-metadata-store/instance/open-metadata-archives/file
Content-Type: text/plain

content-packs/CocoComboArchive.omarchive

###
# Add the ClinicalTrials at CocoPharmaceuticals engine to engine-host
POST {{baseURL}}/open-metadata/admin-services/users/{{adminUserId}}/servers/qs-engine-host/engine
Content-Type: application/json

{
  "class": "EngineConfig",
  "engineId": "113c35dc-ea92-40ce-aef2-daf9e08c1b05",
  "engineQualifiedName": "ClinicalTrials@CocoPharmaceuticals",
  "engineUserId": "generalnpa"
}


###
# Add the AssetQuality at CocoPharmaceuticals engine to engine-host
POST {{baseURL}}/open-metadata/admin-services/users/{{adminUserId}}/servers/qs-engine-host/engine
Content-Type: application/json

{
  "class": "EngineConfig",
  "engineId": "76257f18-293f-4e7c-b79f-8b7e5fa44552",
  "engineQualifiedName": "AssetQuality@CocoPharmaceuticals",
  "engineUserId": "generalnpa"
}

###
# Restart the engine-host  server on the OMAG Server Platform.
POST {{baseURL}}/open-metadata/platform-services/users/{{adminUserId}}/server-platform/servers/qs-engine-host/instance

