# Egeria-jacquard-digital-products
# Retrieving details of the digital products in the Open Metadata Digital Product Catalog
# https://egeria-project.org/concepts/digital-product

@baseURL=https://localhost:7443
@viewServer=view-server

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "peterprofile",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}

###
# =====================================================================================================================
# Retrieving Digital Products: https://egeria-project.org/concepts/digital-product
#

###
# @name get details of the open metadata digital product catalog
# See the operall structure of the catalog
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/collection-manager/collections/by-name
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "FilterRequestBody",
  "filter" : "Open Metadata Digital Product Catalog"
}

> {% client.global.set("digitalProductCatalogGUID", response.body.elements[0].elementHeader.guid); %}



###
# @name get a 2 level view of the structure of the open metadata digital product catalog
# Return a hierarchy of nested collections. Request body is optional
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/collection-manager/collections/{{digitalProductCatalogGUID}}/hierarchy
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ResultsRequestBody",
  "graphQueryDepth" : 2
}


###
# @name get a 3 level view of the structure of the open metadata digital product catalog
# Return a hierarchy of nested collections. Request body is optional
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/collection-manager/collections/{{digitalProductCatalogGUID}}/hierarchy
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "ResultsRequestBody",
  "graphQueryDepth" : 3
}



###
# @name get the digital products in the reference data category
# List the products that contain reference data
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/collection-manager/digital-products/by-category
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeploymentStatusFilterRequestBody",
  "filter" : "Reference Data",
  "pageSize" : 10
}


###
# @name find the product families in the open metadata digital product catalog
# Returns the list of the digital product families and their products.
#
# @param serverName name of the service to route the request to
# @param urlMarker  view service URL marker
# @param requestBody string to find in the properties
#
# @return a list of digital products
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/collection-manager/digital-products/by-search-string
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeploymentStatusSearchString",
  "metadataElementTypeName" : "DigitalProductFamily",
  "includeOnlyRelationships": ["CollectionMembership"]
}



###
# @name find the active products in the open metadata digital product catalog
# Returns the list of the digital product families and their products.
#
# @param serverName name of the service to route the request to
# @param urlMarker  view service URL marker
# @param requestBody string to find in the properties
#
# @return a list of digital products
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/collection-manager/digital-products/by-search-string
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeploymentStatusSearchString",
  "metadataElementTypeName" : "DigitalProduct",
  "includeOnlyRelationships": ["CollectionMembership"],
  "deploymentStatusList": ["ACTIVE"]
}


###
# @name find the products still being developed in the open metadata digital product catalog
# Returns the list of the digital product families and their products.
#
# @param serverName name of the service to route the request to
# @param urlMarker  view service URL marker
# @param requestBody string to find in the properties
#
# @return a list of digital products
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/collection-manager/digital-products/by-search-string
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeploymentStatusSearchString",
  "metadataElementTypeName" : "DigitalProduct",
  "includeOnlyRelationships": ["CollectionMembership"],
  "deploymentStatusList": ["UNDER_DEVELOPMENT"]
}



###
# @name get the digital product for contentStatus valid values
# Returns the list of collections with a particular name.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/collection-manager/collections/by-name
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "FilterRequestBody",
  "metadataElementTypeName": "DigitalProduct",
  "filter" : "contentStatus Valid Values"
}

> {% client.global.set("contentStatusDigitalProductGUID", response.body.elements[0].elementHeader.guid); %}

###
# @name get subscription types for the contentStatus valid values digital product
# Retrieve elements linked via the requested relationship type name. It is also possible to limit the results by
# specifying a type name for the elements that should be returned. If no type name is specified then any type of
# element may be returned.
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/classification-explorer/elements/{{contentStatusDigitalProductGUID}}/by-relationship/ResourceList?startAtEnd=1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "class" : "ResultsRequestBody",
    "metadataElementTypeName": "GovernanceActionProcess",
    "includeOnlyRelationships" : ["ResourceList"]
}

