# Egeria-repository-services-audit-log

###
# @name Get supported audit log severities
# Return a list of the severities that are supported in this server.
GET {{baseURL}}/servers/{{server}}/open-metadata/repository-services/users/{{adminUserId}}/audit-log/severity-definitions

###
# @name Get audit log report
# Return the status of the audit log service.  This include dettails of the components and how much they are logging.
GET {{baseURL}}/servers/{{server}}/open-metadata/repository-services/users/{{adminUserId}}/audit-log/report