# Egeria-repository-services-metadata-highway
@baseURL=https://localhost:9443
@adminUserId=garygeeke
@cohort=sampleCohort
@server=active-metadata-store

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId" : "{{adminUserId}}",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}

###
# @name Get cohort details
# Get the details of cohorts that this server is connecting to.
GET {{baseURL}}/servers/{{server}}/open-metadata/repository-services/metadata-highway/cohort-descriptions
Authorization: Bearer {{token}}

###
# @name Get local registration
# Get the details of the registration information that this server is sending to the cohorts it is registering with.
GET {{baseURL}}/servers/{{server}}/open-metadata/repository-services/metadata-highway/local-registration
Authorization: Bearer {{token}}

###
# @name Get local registration with a specific cohort
# Get the details of the registration information that this server sent out to a specific cohort including the time stamp for this registration.  This determines how long this server has been exchanging metadata with this cohort.
GET {{baseURL}}/servers/{{server}}/open-metadata/repository-services/metadata-highway/cohorts/{{cohort}}/local-registration
Authorization: Bearer {{token}}

###
# @name Get remote registrations
# Get the details of the registration information that this server has received from remote members of a cohort. This determines the size of the cohort.
GET {{baseURL}}/servers/{{server}}/open-metadata/repository-services/metadata-highway/cohorts/{{cohort}}/remote-members
Authorization: Bearer {{token}}

###
# @name Connect to cohort
GET {{baseURL}}/servers/{{server}}/open-metadata/repository-services/metadata-highway/cohorts/{{cohort}}/connect
Authorization: Bearer {{token}}

###
# @name Disconnect From Cohort
GET {{baseURL}}/servers/{{server}}/open-metadata/repository-services/metadata-highway/cohorts/{{cohort}}/disconnect
Authorization: Bearer {{token}}

###
# @name Unregister from cohort
GET {{baseURL}}/servers/{{server}}/open-metadata/repository-services/metadata-highway/cohorts/{{cohort}}/unregister
Authorization: Bearer {{token}}
