/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright Contributors to the ODPi Egeria project. */
package org.odpi.openmetadata.contentpacks.core;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.odpi.openmetadata.repositoryservices.connectors.stores.archivestore.properties.OpenMetadataArchive;
import org.odpi.openmetadata.repositoryservices.connectors.stores.archivestore.properties.OpenMetadataArchiveInstanceStore;
import org.odpi.openmetadata.repositoryservices.connectors.stores.metadatacollectionstore.properties.instances.EntityDetail;
import org.odpi.openmetadata.repositoryservices.connectors.stores.metadatacollectionstore.properties.instances.EntityProxy;
import org.odpi.openmetadata.repositoryservices.connectors.stores.metadatacollectionstore.properties.instances.InstanceProperties;
import org.odpi.openmetadata.repositoryservices.connectors.stores.metadatacollectionstore.properties.instances.InstancePropertyValue;
import org.odpi.openmetadata.repositoryservices.connectors.stores.metadatacollectionstore.properties.instances.Relationship;
import org.testng.annotations.Test;

import java.io.File;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Stream;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertNotNull;
import static org.testng.Assert.assertTrue;

/**
 * ContentPackIntegrityTest checks the content packs that this module ships.
 * <br><br>
 * The archives under {@code content-packs} are generated by the writers in this module and then
 * <b>committed</b>, and the GUID maps that keep every element's identity stable from one generation to the
 * next are committed separately, at the top of the repository.  Nothing checked either of them.  That
 * matters more here than for ordinary code, because the failure mode is silent by construction: an archive
 * writer run without its GUID map to hand does not fail, it allocates fresh identities for content that has
 * already shipped and reports success.  A repository that has already loaded the old pack then holds two
 * copies of everything in it.
 * <br><br>
 * These checks are deliberately <b>read-only</b>.  Running the writers would rewrite the committed archives
 * and extend the committed maps as a side effect of testing them, which is not a thing a test may do.  So
 * instead the shipped archives are read and held to the properties a correct generation would give them:
 * <ul>
 *     <li><b>They deserialize.</b>  Into {@link OpenMetadataArchive}, the platform's own bean - so a pack
 *     that the platform could not load fails here rather than at start-up.</li>
 *     <li><b>Their identities are recorded.</b>  Every entity GUID appears in one of the committed GUID
 *     maps.  A GUID that is in a pack but in no map is one the next generation will allocate afresh, so the
 *     element's identity is already lost, whatever the archive currently says.</li>
 *     <li><b>One GUID means one element.</b>  No GUID is used for two different qualified names, within a
 *     pack or across them.  Packs layer deliberately - the same element appears in several - but the same
 *     identity standing for two different things would merge them in any repository that loaded both.</li>
 *     <li><b>Their references resolve.</b>  Every relationship end names an entity that some pack actually
 *     carries.  An end that resolves to nothing leaves a dangling proxy behind in the repository.</li>
 * </ul>
 */
public class ContentPackIntegrityTest
{
    private static final String CONTENT_PACKS    = "content-packs";
    private static final String ARCHIVE_SUFFIX   = ".omarchive";
    private static final String GUID_MAP_SUFFIX  = "GUIDMap.json";

    /**
     * How many packs there should be, near enough.  This is not a count to keep up to date - it is a guard
     * that the test found the archives at all, so that a move of the content-packs directory fails loudly
     * rather than leaving every check below passing over an empty list.
     */
    private static final int FEWEST_EXPECTED_PACKS = 20;

    /**
     * Relationship ends that resolve to no entity in any pack, each with the reason it is tolerated.
     * <br><br>
     * Empty, and worth keeping empty.  It held one entry - the SLF4J audit log destination connector, whose
     * GUID collided with an open metadata type's so the archive builder refused it while the relationship
     * naming it was still written - until the collision was fixed and the pack regenerated.  An entry here
     * is a known gap in shipped content, not a rule being bent.
     */
    private static final Map<String, String> EXPECTED_DANGLING_ENDS = new LinkedHashMap<>();

    private final ObjectMapper objectMapper = new ObjectMapper();


    /**
     * Every shipped archive deserializes into the platform's own archive bean and holds something.
     */
    @Test
    public void everyContentPackDeserializes()
    {
        List<Path> archives = contentPacks();

        for (Path archive : archives)
        {
            OpenMetadataArchive openMetadataArchive = readArchive(archive);

            assertNotNull(openMetadataArchive.getArchiveProperties(),
                          archive.getFileName() + " has no archive properties");
            assertNotNull(openMetadataArchive.getArchiveProperties().getArchiveGUID(),
                          archive.getFileName() + " has no archive GUID");
            assertNotNull(openMetadataArchive.getArchiveProperties().getArchiveName(),
                          archive.getFileName() + " has no archive name");

            boolean holdsTypes     = openMetadataArchive.getArchiveTypeStore() != null;
            boolean holdsInstances = (openMetadataArchive.getArchiveInstanceStore() != null)
                                             && (openMetadataArchive.getArchiveInstanceStore().getEntities() != null);

            assertTrue(holdsTypes || holdsInstances,
                       archive.getFileName() + " holds neither types nor instances - it would load as nothing");
        }
    }


    /**
     * Every entity in a shipped pack has its identity recorded in a committed GUID map.
     */
    @Test
    public void everyShippedIdentityIsRecordedInAGUIDMap()
    {
        Set<String>  mappedGUIDs = guidsInTheCommittedMaps();
        List<String> unrecorded  = new ArrayList<>();

        assertTrue(mappedGUIDs.size() > 10000,
                   "Expected to find the committed GUID maps - found " + mappedGUIDs.size() +
                           " identities. Are they still at the top of the repository?");

        for (Path archive : contentPacks())
        {
            for (EntityDetail entity : entitiesIn(readArchive(archive)))
            {
                if (! mappedGUIDs.contains(entity.getGUID()))
                {
                    unrecorded.add(archive.getFileName() + ": " + qualifiedNameOf(entity.getProperties()) +
                                           " (" + entity.getGUID() + ")");
                }
            }
        }

        assertTrue(unrecorded.isEmpty(),
                   "These elements ship with an identity that no committed GUID map records, so the next" +
                           " generation will give them new ones and any repository holding the current pack" +
                           " will end up with both:\n    " + String.join("\n    ", unrecorded));
    }


    /**
     * No GUID stands for two different elements.
     */
    @Test
    public void oneGUIDMeansOneElement()
    {
        Map<String, String> nameForGUID = new HashMap<>();
        List<String>        clashes     = new ArrayList<>();

        for (Path archive : contentPacks())
        {
            for (EntityDetail entity : entitiesIn(readArchive(archive)))
            {
                String qualifiedName = qualifiedNameOf(entity.getProperties());

                if (qualifiedName == null)
                {
                    continue;
                }

                String alreadySeen = nameForGUID.putIfAbsent(entity.getGUID(), qualifiedName);

                if ((alreadySeen != null) && (! alreadySeen.equals(qualifiedName)))
                {
                    clashes.add(entity.getGUID() + " is used for both '" + alreadySeen + "' and '" +
                                        qualifiedName + "' (" + archive.getFileName() + ")");
                }
            }
        }

        assertTrue(clashes.isEmpty(),
                   "One identity cannot stand for two elements - a repository loading both packs would merge" +
                           " them:\n    " + String.join("\n    ", clashes));
    }


    /**
     * Every relationship end names an entity that some pack carries.
     */
    @Test
    public void everyRelationshipEndResolves()
    {
        List<Path>   archives  = contentPacks();
        Set<String>  allGUIDs  = new HashSet<>();
        List<String> dangling  = new ArrayList<>();

        for (Path archive : archives)
        {
            for (EntityDetail entity : entitiesIn(readArchive(archive)))
            {
                allGUIDs.add(entity.getGUID());
            }
        }

        for (Path archive : archives)
        {
            OpenMetadataArchiveInstanceStore instanceStore = readArchive(archive).getArchiveInstanceStore();

            if ((instanceStore == null) || (instanceStore.getRelationships() == null))
            {
                continue;
            }

            for (Relationship relationship : instanceStore.getRelationships())
            {
                checkEnd(archive, relationship.getEntityOneProxy(), allGUIDs, dangling);
                checkEnd(archive, relationship.getEntityTwoProxy(), allGUIDs, dangling);
            }
        }

        assertTrue(dangling.isEmpty(),
                   "These relationships name an entity that no pack carries, so loading the pack leaves a" +
                           " dangling proxy behind:\n    " + String.join("\n    ", dangling));
    }


    /**
     * Check one end of a relationship, allowing the gaps recorded in {@link #EXPECTED_DANGLING_ENDS}.
     *
     * @param archive the pack the relationship came from
     * @param proxy the end to check
     * @param allGUIDs every entity identity in every pack
     * @param dangling collected findings
     */
    private void checkEnd(Path archive, EntityProxy proxy, Set<String> allGUIDs, List<String> dangling)
    {
        if ((proxy == null) || (proxy.getGUID() == null) || allGUIDs.contains(proxy.getGUID()))
        {
            return;
        }

        String qualifiedName = qualifiedNameOf(proxy.getUniqueProperties());

        if ((qualifiedName != null) && EXPECTED_DANGLING_ENDS.containsKey(qualifiedName))
        {
            return;
        }

        dangling.add(archive.getFileName() + ": " + qualifiedName + " (" + proxy.getGUID() + ")");
    }


    /**
     * Return the qualified name held in the supplied properties, or null when there is none.
     *
     * @param properties instance properties
     * @return qualified name
     */
    private String qualifiedNameOf(InstanceProperties properties)
    {
        if ((properties == null) || (properties.getInstanceProperties() == null))
        {
            return null;
        }

        InstancePropertyValue qualifiedName = properties.getInstanceProperties().get("qualifiedName");

        return (qualifiedName == null) ? null : qualifiedName.valueAsString();
    }


    /**
     * Return the entities in an archive, or an empty list when it holds none.
     *
     * @param openMetadataArchive archive to look in
     * @return entities
     */
    private List<EntityDetail> entitiesIn(OpenMetadataArchive openMetadataArchive)
    {
        OpenMetadataArchiveInstanceStore instanceStore = openMetadataArchive.getArchiveInstanceStore();

        if ((instanceStore == null) || (instanceStore.getEntities() == null))
        {
            return List.of();
        }

        return instanceStore.getEntities();
    }


    /**
     * Read and deserialize one archive.
     *
     * @param archive file to read
     * @return the archive
     */
    private OpenMetadataArchive readArchive(Path archive)
    {
        try
        {
            return objectMapper.readValue(archive.toFile(), OpenMetadataArchive.class);
        }
        catch (IOException error)
        {
            throw new AssertionError(archive.getFileName() + " does not deserialize into an OpenMetadataArchive" +
                                             " - the platform could not load it either: " + error.getMessage(), error);
        }
    }


    /**
     * Return every identity recorded in the committed GUID maps.  The maps live at the top of the
     * repository because that is where the writers look for them; see the {@code run} block in this
     * module's build.
     *
     * @return the recorded GUIDs
     */
    private Set<String> guidsInTheCommittedMaps()
    {
        Set<String> guids = new HashSet<>();

        try (Stream<Path> files = Files.list(repositoryRoot()))
        {
            for (Path candidate : files.filter(path -> path.getFileName().toString().endsWith(GUID_MAP_SUFFIX))
                                       .toList())
            {
                Map<String, String> guidMap = objectMapper.readValue(candidate.toFile(),
                                                                     new TypeReference<>() { });

                guids.addAll(guidMap.values());
            }
        }
        catch (IOException error)
        {
            throw new UncheckedIOException(error);
        }

        return guids;
    }


    /**
     * Return the shipped content packs, with a check that they were found.
     *
     * @return archive files
     */
    private List<Path> contentPacks()
    {
        Path directory = repositoryRoot().resolve(CONTENT_PACKS);

        assertTrue(Files.isDirectory(directory),
                   "The content packs are not at " + directory + " - has the directory moved?");

        File[] archives = directory.toFile()
                                   .listFiles((folder, name) -> name.endsWith(ARCHIVE_SUFFIX));

        assertNotNull(archives, "Unable to list " + directory);
        assertTrue(archives.length >= FEWEST_EXPECTED_PACKS,
                   "Expected at least " + FEWEST_EXPECTED_PACKS + " content packs in " + directory +
                           " - found " + archives.length + ". Have they moved, or is this build incomplete?");

        List<Path> paths = new ArrayList<>();

        for (File archive : archives)
        {
            paths.add(archive.toPath());
        }

        paths.sort(Path::compareTo);

        return paths;
    }


    /**
     * Return the root of the repository.  A test's working directory is its own module, so walk up until the
     * file that marks the root of the build is found.
     *
     * @return repository root
     */
    private Path repositoryRoot()
    {
        Path candidate = Paths.get("").toAbsolutePath();

        while (candidate != null)
        {
            if (Files.exists(candidate.resolve("settings.gradle")))
            {
                return candidate;
            }

            candidate = candidate.getParent();
        }

        throw new AssertionError("Unable to locate the repository root - no settings.gradle found above " +
                                         Paths.get("").toAbsolutePath());
    }


    /**
     * A sanity check on the fixture itself: the packs are there and hold a plausible amount of content.  If
     * this fails, nothing above means anything.
     */
    @Test
    public void theContentPacksAreWhereThisTestExpectsThem()
    {
        List<Path> archives = contentPacks();
        int        entities = 0;

        for (Path archive : archives)
        {
            entities += entitiesIn(readArchive(archive)).size();
        }

        assertTrue(entities > 1000,
                   "The content packs hold only " + entities + " elements between them, which is too few to" +
                           " be the real thing - the checks in this class would pass over almost nothing.");

        assertEquals(archives.size(), archives.stream().distinct().count(), "duplicate archive paths");
    }
}
