# Egeria-data-engineer-view-service

@baseURL=https://localhost:9443
@viewServer=view-server

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "peterprofile",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}


###

@tabularDataSetGUID=add guid here

###
# @name getTabularDataSetReport
# Returns details of a tabular data set including the data rows that match the startFromRow and maxRowCount values.
# If maxRowCount=0 then no data records are returned.
#
# @param serverName     name of called server
# @param tabularDataSetGUID     unique identifier of tabular dat set asset
# @param startFromRow    cursor position in the data set
# @param maxRowCount maximum number of rows to return.  0 means no rows.
#
# @return a list of projects
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    there is a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
GET {{baseURL}}/servers/{{viewServer}}/api/open-metadata/data-engineer/tabular-data-sets/{{tabularDataSetGUID}}/report?startFromRow=0&maxRowCount=5000
Authorization: Bearer {{token}}

###