# Egeria-governance-configuration-service

###
# @name getCatalogTargets
GET {{baseURL}}/servers/{{server}}/open-metadata/access-services/{{access_service}}/open-integration/users/{{user}}/integration-connectors/{{guid}}/catalog-targets?
    startingFrom=0&
    maximumResults=0