# Egeria-engine-host-services
# The Engine Host Services provide the core subsystem for the Engine Host OMAG Server.
# Further Information: https://egeria-project.org/services/engine-host-services/

@baseURL=https://localhost:9443
@server=engine-host
@user=peterprofile
@governanceEngineName=AssetSurvey
@serviceURLMarker=governance-action

###
# @name getGovernanceEngineSummary
# Retrieve the description and status of the requested governance engine.
# Further Information: https://egeria-project.org/concepts/governance-engine/
GET {{baseURL}}/servers/{{server}}/open-metadata/engine-host/users/{{user}}/governance-engines/{{governanceEngineName}}/summary

###
# @name getGovernanceEngineSummaries
# Return a summary of each of the governance engines running in the Engine Host.
# Further Information: https://egeria-project.org/concepts/governance-engine/
 GET {{baseURL}}/servers/{{server}}/open-metadata/engine-host/users/{{user}}/governance-engines/summary

###
# @name getGovernanceServiceSummary
# Retrieve the description and status of each governance engine assigned to a specific Open Metadata Engine Service (OMES).
# Further Information: https://egeria-project.org/concepts/governance-engine/
GET {{baseURL}}/servers/{{server}}/open-metadata/engine-host/users/{{user}}/engine-service/{{serviceURLMarker}}/governance-engines/summary

###
# @name refreshConfig
# Request that the governance engine refresh its configuration by calling the metadata server.
# This request is useful if the metadata server has an outage, particularly while the
# governance server is initializing.  This request just ensures that the latest configuration is in use.
# Further Information: https://egeria-project.org/concepts/governance-engine-definition/
GET {{baseURL}}/servers/{{server}}/open-metadata/engine-host/users/{{user}}/governance-engines/{{governanceEngineName}}/refresh-config


###
# @name refreshConfig (ALL)
# Request that all governance engines refresh their configuration by calling the metadata server.
# This request is useful if the metadata server has an outage, particularly while the
# governance server is initializing.  This request just ensures that the latest configuration is in use.
# Further Information: https://egeria-project.org/concepts/governance-engine-definition/
GET {{baseURL}}/servers/{{server}}/open-metadata/engine-host/users/{{user}}/governance-engines/refresh-config

###