# Egeria-user-authn
@baseURL=https://localhost:7443
@viewServer=view-server

###
# @name Application info
GET {{baseURL}}/api/public/app/info

###
# @name About
GET {{baseURL}}/api/about

###
# @name User Login
POST {{baseURL}}/api/token
Content-Type: application/json

{
    "userId" : "peterprofile",
    "password" : "secret"
}

> {% client.global.set("token", response.body); %}

###
# @name User Login (server)
POST {{baseURL}}/servers/{{viewServer}}/api/token
Content-Type: application/json

{
  "userId" : "peterprofile",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}

###
# @name User Logout
# Invalidate the user's token supplied in the request
# https://egeria-project.org/features/metadata-security/overview
DELETE {{baseURL}}/api/token/logout
Authorization: Bearer {{token}}


###
# @name User Logout (server)
# Invalidate the user's token supplied in the request
# https://egeria-project.org/features/metadata-security/overview
DELETE {{baseURL}}/servers/{{viewServer}}/api/token/logout
Authorization: Bearer {{token}}





