# Egeria-integration-daemon-services

@baseURL=https://localhost:9443
@server=integration-daemon
@user=garygeeke

###
# group: Integration Services
# @name Retrieve the connector type for a connector
# Restarts the requested Integration Service
GET {{baseURL}}/servers/{{server}}/open-metadata/integration-services/files-integrator/users/{{user}}/validate-connector/org.odpi.openmetadata.adapters.connectors.integration.basicfiles.DataFilesMonitorIntegrationProvider

###
# group: Integration Services
# @name Refresh All integration Connectors
# Refreshes all Integration Connectors running in an integration daemon
POST {{baseURL}}/servers/{{server}}/open-metadata/integration-daemon/users/{{user}}/integration-connectors/refresh

###
# group: Integration Connectors
# @name Refresh All integration Connectors
# Refreshes all Integration Connectors running in an integration daemon
POST {{baseURL}}/servers/{{server}}/open-metadata/integration-daemon/users/{{user}}/integration-connectors/refresh

###
# group: Integration Connectors
# @name Refresh Integration Connector
# Refreshes all Integration Connectors running in an integration daemon
POST {{baseURL}}/servers/{{server}}/open-metadata/integration-daemon/users/{{user}}/integration-connectors/refresh
Content-Type: application/json

{
    "class" : "NameRequestBody",
    "name" : "connectorName goes here"
}

###
# group: Integration Connectors
# @name Restart All integration Connectors
# Refreshes all Integration Connectors running in an integration daemon
POST {{baseURL}}/servers/{{server}}/open-metadata/integration-daemon/users/{{user}}/integration-connectors/restart

###
# group: Integration Connectors
# @name Restart Integration Connector
# Refreshes all Integration Connectors running in an integration daemon
POST {{baseURL}}/servers/{{server}}/open-metadata/integration-daemon/users/{{user}}/integration-connectors/restart
Content-Type: application/json

{
    "class" : "NameRequestBody",
    "name" : "connectorName goes here"
}

###
# @name Get Integration Daemon Status
# Retrieves the status of the connectors running in the Integration Daemon
GET {{baseURL}}/servers/{{server}}/open-metadata/integration-daemon/users/{{user}}/status

###

@serviceURLName=asset-owner
@connectorProfileClassName="className"

###
# @name Validate Connector
GET {{baseURL}}/servers/{{server}}/open-metadata/{{serviceURLName}}/users/{{user}}/validate-connector/{{connectorProfileClassName}}