# Egeria-integration-daemon-services

@baseURL=https://localhost:9443
@server=integration-daemon
@user=garygeeke

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "{{user}}",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}


###
# group: Integration Connectors
# @name Refresh All integration Connectors
# Refreshes all Integration Connectors running in an integration daemon
POST {{baseURL}}/servers/{{server}}/open-metadata/integration-daemon/integration-connectors/refresh
Authorization: Bearer {{token}}

###
# group: Integration Connectors
# @name Refresh Integration Connector
# Refreshes all Integration Connectors running in an integration daemon
POST {{baseURL}}/servers/{{server}}/open-metadata/integration-daemon/integration-connectors/refresh
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "class" : "NameRequestBody",
    "name" : "connectorName goes here"
}

###
# group: Integration Connectors
# @name Restart All integration Connectors
# Refreshes all Integration Connectors running in an integration daemon
POST {{baseURL}}/servers/{{server}}/open-metadata/integration-daemon/integration-connectors/restart
Authorization: Bearer {{token}}

###
# group: Integration Connectors
# @name Restart Integration Connector
# Refreshes all Integration Connectors running in an integration daemon
POST {{baseURL}}/servers/{{server}}/open-metadata/integration-daemon/integration-connectors/restart
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "class" : "NameRequestBody",
    "name" : "connectorName goes here"
}

###
# @name Get Integration Daemon Status
# Retrieves the status of the connectors running in the Integration Daemon
GET {{baseURL}}/servers/{{server}}/open-metadata/integration-daemon/status
Authorization: Bearer {{token}}

###

@connectorProfileClassName=className

###
# @name Validate Connector
GET {{baseURL}}/servers/{{server}}/open-metadata/integration-daemon/validate-connector/{{connectorProfileClassName}}
Authorization: Bearer {{token}}


###
# @name Validate Connector example
# Restarts the requested Integration Service
GET {{baseURL}}/servers/{{server}}/open-metadata/integration-daemon/validate-connector/org.odpi.openmetadata.adapters.connectors.integration.basicfiles.DataFilesMonitorIntegrationProvider
Authorization: Bearer {{token}}

