# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
---
trigger:
  batch: true
  branches:
    include:
      - main
pr: none

variables:
  - group: Artifactory
  - group: SonarCloud

stages:
  - stage: Sonar
    jobs:
      - job: Scan
        timeoutInMinutes: 360
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: SonarCloudPrepare@1
            displayName: 'Prepare SonarCloud Analysis'
            inputs:
              SonarCloud: 'odpi-sonarcloud'
              organization: '$(organization)'
              scannerMode: 'Other'
              extraProperties: |
                  sonar.branch.name=$(Build.SourceBranchName)
          - task: Maven@3
            displayName: 'Install Egeria'
            inputs:
              mavenPomFile: 'pom.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '11'
              jdkArchitectureOption: 'x64'
              goals: 'install'
              options: >-
                  --batch-mode
                  --quiet
                  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
              mavenOptions: '-Xmx5500m'
          - task: Maven@3
            displayName: 'Perform SonarScan'
            inputs:
              mavenPomFile: 'pom.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '11'
              jdkArchitectureOption: 'x64'
              goals: 'sonar:sonar'
              options: >-
                  --batch-mode
                  --quiet
                  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
                  -Dsonar
                  -Dsonar.projectKey="$(projectKey)"
                  -Dsonar.organization="$(organization)"
                  -Dsonar.projectName="$(projectName)"
                  -Dsonar.host.url="https://sonarcloud.io"
                  -Dsonar.login="$(apiKey)"
              mavenOptions: '-Xmx5500m'
          - task: SonarCloudPublish@1
            displayName: 'Publish SonarCloud quality gate results'
