# Egeria-time-keeper-view-service
# https://egeria-project.org/concepts/context-event

@baseURL=https://localhost:9443
@viewServer=view-server

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Content-Type: application/json

{
  "userId" : "peterprofile",
  "password" : "secret"
}

> {% client.global.set("token", response.body); %}



###
# @name createContextEvent
# Create a context event.
#
# @param serverName                 name of called server.
# @param urlMarker  view service URL marker
# @param requestBody             properties for the context event.
#
# @return unique identifier of the newly created element
#  InvalidParameterException  one of the parameters is invalid.
#  PropertyServerException    there is a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/time-keeper/context-events
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewElementRequestBody",
  "anchorGUID" : "add guid here",
  "isOwnAnchor": false,
  "parentGUID": "add guid here",
  "parentRelationshipTypeName": "add type name here",
  "parentRelationshipProperties": {
    "class": "RelationshipElementProperties",
    "propertyValueMap" : {
      "description" : {
        "class": "PrimitiveTypePropertyValue",
        "typeName": "string",
        "primitiveValue" : "New description"
      }
    }
  },
  "parentAtEnd1": false,
  "properties": {
    "class" : "ContextEventProperties",
    "qualifiedName": "add unique name here",
    "displayName": "add short name here",
    "description": "add description here",
    "category" : "",
    "url" : "",
    "eventEffect" : "",
    "plannedStartDate" : "{{$isoTimestamp}}",
    "actualStartDate" : "{{$isoTimestamp}}",
    "plannedDuration" : 5,
    "actualDuration" : 6,
    "repeatInterval" : 7,
    "plannedCompletionDate" : "{{$isoTimestamp}}",
    "actualCompletionDate" : "{{$isoTimestamp}}",
    "referenceEffectiveFrom" : "{{$isoTimestamp}}",
    "referenceEffectiveTo" : "{{$isoTimestamp}}",
    "additionalProperties": {
      "property1" : "propertyValue1",
      "property2" : "propertyValue2"
    },
    "extendedProperties": {
      "property1" : "propertyValue1",
      "property2" : "propertyValue2"
    },
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}



###
# @name createContextEventFromTemplate
# Create a new metadata element to represent a context event using an existing metadata element as a template.
# The template defines additional classifications and relationships that should be added to the new element.
#
# @param serverName             calling user
# @param urlMarker  view service URL marker
# @param requestBody properties that override the template
#
# @return unique identifier of the new metadata element
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    there is a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/time-keeper/context-events/from-template
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "TemplateRequestBody",
  "anchorGUID" : "add guid here",
  "isOwnAnchor": false,
  "parentGUID": "add guid here",
  "parentRelationshipTypeName": "add type name here",
  "parentRelationshipProperties": {
    "class": "RelationshipElementProperties",
    "propertyValueMap" : {
      "description" : {
        "class": "PrimitiveTypePropertyValue",
        "typeName": "string",
        "primitiveValue" : "New description"
      }
    }
  },
  "parentAtEnd1": false,
  "templateGUID": "add guid here",
  "replacementProperties": {
    "class": "ElementProperties",
    "propertyValueMap" : {
      "description" : {
        "class": "PrimitiveTypePropertyValue",
        "typeName": "string",
        "primitiveValue" : "New description"
      }
    }
  },
  "placeholderPropertyValues":  {
    "placeholder1" : "propertyValue1",
    "placeholder2" : "propertyValue2"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name updateContextEvent
# Update the properties of a context event.
#
# @param serverName         name of called server.
# @param urlMarker  view service URL marker
# @param contextEventGUID unique identifier of the context event (returned from create)
# @param requestBody     properties for the new element.
#
# @return boolean or
#  InvalidParameterException  one of the parameters is invalid.
#  PropertyServerException    there is a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/time-keeper/context-events/{contextEventGUID}/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "UpdateElementRequestBody",
  "mergeUpdate": true,
  "properties": {
    "class" : "ContextEventProperties",
    "qualifiedName": "add unique name here",
    "displayName": "add short name here",
    "description": "add description here",
    "category" : "",
    "url" : "",
    "eventEffect" : "",
    "plannedStartDate" : "{{$isoTimestamp}}",
    "actualStartDate" : "{{$isoTimestamp}}",
    "plannedDuration" : 5,
    "actualDuration" : 6,
    "repeatInterval" : 7,
    "plannedCompletionDate" : "{{$isoTimestamp}}",
    "actualCompletionDate" : "{{$isoTimestamp}}",
    "referenceEffectiveFrom" : "{{$isoTimestamp}}",
    "referenceEffectiveTo" : "{{$isoTimestamp}}",
    "additionalProperties": {
      "property1" : "propertyValue1",
      "property2" : "propertyValue2"
    },
    "extendedProperties": {
      "property1" : "propertyValue1",
      "property2" : "propertyValue2"
    },
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name linkDependentContextEvents
# Connect two context events to show that one is dependent on another.
#
# @param serverName         name of called server
# @param urlMarker  view service URL marker
# @param parentContextEventGUID    unique identifier of the parent context event
# @param childContextEventGUID     unique identifier of the chile context event
# @param requestBody  description of the relationship.
#
# @return void or
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    there is a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/time-keeper/context-events/{parentContextEventGUID}/dependent-context-events/{childContextEventGUID}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "DependentContextEventProperties",
    "label" : "",
    "description" : "",
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name detachDependentContextEvents
# Detach two dependent context events from one another.
#
# @param serverName         name of called server
# @param urlMarker  view service URL marker
# @param parentContextEventGUID    unique identifier of the parent context event
# @param childContextEventGUID     unique identifier of the child context event
# @param requestBody  description of the relationship.
#
# @return void or
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    there is a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/time-keeper/context-events/{parentContextEventGUID}/dependent-context-events/{childContextEventGUID}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "cascadedDelete" : false,
  "deleteMethod" : "LOOK_FOR_LINEAGE",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name linkRelatedContextEvents
# Connect two context events to show that one is related to the other.
#
# @param serverName         name of called server
# @param urlMarker  view service URL marker
# @param contextEventOneGUID    unique identifier of the  context event at end 1
# @param contextEventTwoGUID     unique identifier of the  context event at end 2
# @param requestBody  description of the relationship.
#
# @return void or
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    there is a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/time-keeper/context-events/{contextEventOneGUID}/related-context-events/{contextEventTwoGUID}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "RelatedContextEventProperties",
    "label" : "",
    "description" : "",
    "statusIdentifier" : 0,
    "confidence" : 100,
    "steward" : "",
    "stewardTypeName" : "",
    "stewardPropertyName" : "",
    "source" : "",
    "notes" : "",
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name detachRelatedContextEvents
# Detach two context events that are related to one another.
#
# @param serverName         name of called server
# @param urlMarker  view service URL marker
# @param contextEventOneGUID    unique identifier of the  context event at end 1
# @param contextEventTwoGUID     unique identifier of the  context event at end 2
# @param requestBody  description of the relationship.
#
# @return void or
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    there is a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/time-keeper/context-events/{contextEventOneGUID}/related-context-events/{contextEventTwoGUID}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "cascadedDelete" : false,
  "deleteMethod" : "LOOK_FOR_LINEAGE",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name linkContextEventEvidence
# Connect a context event to an element that provides evidence that this context event is real.
#
# @param serverName         name of called server
# @param urlMarker  view service URL marker
# @param contextEventGUID    unique identifier of the context event
# @param evidenceGUID     unique identifier of the element representing the evidence
# @param requestBody  description of the relationship.
#
# @return void or
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    there is a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/time-keeper/context-events/{contextEventGUID}/evidence/{evidenceGUID}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "ContextEventEvidenceProperties",
    "label" : "",
    "description" : "",
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name detachContextEventEvidence
# Detach a context event from an element that provides evidence that this context event is real.
#
# @param serverName         name of called server
# @param urlMarker  view service URL marker
# @param contextEventGUID    unique identifier of the context event
# @param evidenceGUID     unique identifier of the element representing the evidence
# @param requestBody  description of the relationship.
#
# @return void or
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    there is a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/time-keeper/context-events/{contextEventGUID}/evidence/{evidenceGUID}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

 {
  "class" : "DeleteRelationshipRequestBody",
  "cascadedDelete" : false,
  "deleteMethod" : "LOOK_FOR_LINEAGE",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name linkContextEventImpact
# Connect a context event to an element that is impacted by this event.
#
# @param serverName         name of called server
# @param urlMarker  view service URL marker
# @param contextEventGUID    unique identifier of the context event
# @param impactedElementGUID     unique identifier of the element that is impacted by the event
# @param requestBody  description of the relationship.
#
# @return void or
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    there is a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/time-keeper/context-events/{contextEventGUID}/impacts/{impactedElementGUID}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "ContextEventImpactProperties",
    "label" : "",
    "description" : "",
    "statusIdentifier" : 0,
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name detachContextEventImpact
# Detach a context event from an element that is impacted by the event.
#
# @param serverName         name of called server
# @param urlMarker  view service URL marker
# @param contextEventGUID    unique identifier of the context event
# @param impactedElementGUID     unique identifier of the element that is impacted by the event
# @param requestBody  description of the relationship.
#
# @return void or
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    there is a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/time-keeper/context-events/{contextEventGUID}/impacts/{impactedElementGUID}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "cascadedDelete" : false,
  "deleteMethod" : "LOOK_FOR_LINEAGE",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name linkContextEventTimelineEffect
# Connect a context event to an element whose data is impacted by this event.
#
# @param serverName         name of called server
# @param urlMarker  view service URL marker
# @param timelineAffectedElementGUID     unique identifier of the element whose data is impacted by the context event
# @param contextEventGUID    unique identifier of the context event
# @param requestBody  description of the relationship.
#
# @return void or
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    there is a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/time-keeper/elements/{timelineAffectedElementGUID}/context-events-describing-timeline-effects/{contextEventGUID}/attach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "NewRelationshipRequestBody",
  "properties": {
    "class": "ContextEventForTimelineEffectsProperties",
    "label" : "",
    "description" : "",
    "statusIdentifier" : 0,
    "effectiveFrom": "{{$isoTimestamp}}",
    "effectiveTo": "{{$isoTimestamp}}"
  },
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name detachContextEventTimelineEffect
# Detach a context event from an element whose data is impacted by the event.
#
# @param serverName         name of called server
# @param urlMarker  view service URL marker
# @param timelineAffectedElementGUID     unique identifier of the element whose data is impacted by the context event
# @param contextEventGUID    unique identifier of the context event
# @param requestBody  description of the relationship.
#
# @return void or
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    there is a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/time-keeper/elements/{timelineAffectedElementGUID}/context-events-describing-timeline-effect/{contextEventGUID}/detach
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteRelationshipRequestBody",
  "cascadedDelete" : false,
  "deleteMethod" : "LOOK_FOR_LINEAGE",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

###
# @name deleteContextEvent
# Delete a context event.
#
# @param serverName         name of called server
# @param urlMarker  view service URL marker
# @param contextEventGUID  unique identifier of the element to delete
# @param requestBody  description of the relationship.
#
# @return void or
#  InvalidParameterException  one of the parameters is null or invalid.
#  PropertyServerException    there is a problem retrieving information from the property server(s).
#  UserNotAuthorizedException the requesting user is not authorized to issue this request.
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/time-keeper/context-events/{contextEventGUID}/delete
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "DeleteElementRequestBody",
  "cascadedDelete" : false,
  "deleteMethod" : "LOOK_FOR_LINEAGE",
  "externalSourceGUID": "add guid here",
  "externalSourceName": "add qualified name here",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}


###
# @name getContextEventsByName
# Returns the list of context events with a particular name.
#
# @param serverName name of the service to route the request to
# @param urlMarker  view service URL marker
# @param requestBody string to find in the properties
#
# @return list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    there is a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/time-keeper/context-events/by-name
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "FilterRequestBody",
  "filter" : "Add name here",
  "startFrom": 0,
  "pageSize": 10,
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "limitResultsByStatus" : ["ACTIVE"],
  "sequencingOrder" : "PROPERTY_ASCENDING",
  "sequencingProperty" : "qualifiedName"
}

###
# @name findContextEvents
# Retrieve the list of context event metadata elements that contain the search string.
#
# @param serverName name of the service to route the request to
# @param urlMarker  view service URL marker
# @param requestBody string to find in the properties
#
# @return list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    there is a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/time-keeper/context-events/by-search-string
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "class" : "SearchStringRequestBody",
  "searchString": "xxx",
  "startsWith" : false,
  "endsWith" : false,
  "ignoreCase" : true,
  "startFrom" : 0,
  "pageSize": 0,
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false,
  "limitResultsByStatus" : ["ACTIVE"],
  "sequencingOrder" : "PROPERTY_ASCENDING",
  "sequencingProperty" : "qualifiedName"
}


###
# @name getContextEventByGUID
# Return the properties of a specific context event.
#
# @param serverName name of the service to route the request to
# @param urlMarker  view service URL marker
# @param contextEventGUID    unique identifier of the required element
# @param requestBody string to find in the properties
#
# @return list of matching metadata elements or
#  InvalidParameterException  one of the parameters is invalid
#  UserNotAuthorizedException the user is not authorized to issue this request
#  PropertyServerException    there is a problem reported in the open metadata server(s)
#
POST {{baseURL}}/servers/{{viewServer}}/api/open-metadata/time-keeper/context-events/{contextEventGUID}/retrieve
Authorization: Bearer {{token}}
Content-Type: application/json

 {
  "class" : "GetRequestBody",
  "asOfTime" : "{{$isoTimestamp}}",
  "effectiveTime" : "{{$isoTimestamp}}",
  "forLineage" : false,
  "forDuplicateProcessing" : false
}

