# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
---
name: "Check documentation links"

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    if: startsWith(github.repository,'odpi/')
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # tag=v7.0.1
      - name: Link Checker
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # tag=v2.9.0
        with:
          # Can switch to true once we run clean
          fail: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
