# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "Maven"

on:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Maven"
    if: startsWith(github.repository,'odpi/')
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Cache Maven packages
        uses: actions/cache@v3.0.11
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-java11-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-java11
      - name: Build with Maven
        run: mvn -B -DargLine="-XX:+TieredCompilation -XX:TieredStopAtLevel=1" clean verify --file pom.xml
      - name: Upload assemblies
        uses: actions/upload-artifact@v3
        with:
          name: Assemblies
          path: open-metadata-distribution/open-metadata-assemblies/target/*.gz
