# Egeria-asset-consumer-omas

###
# @name getConnectionByGUID
# Return the requested connection.
GET {{baseURL}}/servers/{{server}}/open-metadata/common-services/asset-consumer/connected-asset/users/{{user}}/connections/{{guid}}

###
# @name getOutTopicConnection
# Return the connection object for connecting to the Asset Consumer's OMAS's out topic.
GET {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}//topics/out-topic-connection/{{callerId}}

###
# @name getConnectionByName
# Return the requested connection.
GET {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/connections/by-name/{{connectionName}}

###
# @name getAssetForConnectionGUID
# Return the Asset linked to the identified connection.
GET {{baseURL}}/servers/{{server}}/open-metadata/common-services/asset-consumer/connected-asset/users/{{user}}/assets/by-connection/{{guid}}

###
# @name getAssetForConnectionName
# Return the Asset linked to the identified connection.
GET {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/assets/by-connection-name/{{connectionName}}

###
# @name getConnectionForAssetGUID
# Return the Connection attached to the Asset identified by the GUID.
# An exception occurs if there are more than one connections attached to the asset that the user is able to access.
GET {{baseURL}}/servers/{{server}}/open-metadata/common-services/asset-consumer/connected-asset/users/{{user}}/assets/{{assetGUID}}/connection

###
# @name getConnectedAssetSummary
# Return the Asset identified by the GUID and the attached Connection GUID
GET {{baseURL}}/servers/{{server}}/open-metadata/common-services/asset-consumer/connected-asset/users/{{user}}/assets/{{assetGUID}}/via-connection/{{guid}}

###
# @name getAssetByGUID
# Return the Asset identified by the GUID.
GET {{baseURL}}/servers/{{server}}/open-metadata/common-services/asset-consumer/connected-asset/users/{{user}}/assets/{{assetGUID}}

###
# @name getAssetsByMeaning
# Return the Asset linked to the identified connection.
GET {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/assets/by-meaning/{{guid}}

###
# @name getAssetsByTag
# Return the Asset linked to the identified connection.
GET {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/assets/by-tag/{{guid}}

###
# @name getAssetsByName
# Return the Asset identified by the GUID and the attached Connection GUID
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/assets/by-name?
    startFrom=0&
    pageSize=50
Content-Type: application/json

{
    "class" : "NameRequestBody",
    "name" : "DropFoot"
}

###
# @name findAssets
# Return the Asset identified by the GUID and the attached Connection GUID
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/assets/by-search-string?
    startFrom=0&
    pageSize=50
Content-Type: application/json

{
    "class" : "SearchStringRequestBody",
    "searchString" : ".*."
}

###
# @name addCommentToAsset
# Adds a comment directly to an asset
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/assets/{{assetGUID}}/comments
Content-Type: application/json

{
	"class" : "CommentRequestBody",
	"isPublic" : "true",
	"commentType" : "STANDARD_COMMENT",
	"commentText" : "This is the comment on the asset"
}

###
# @name updateCommentOnAsset
# Adds a comment directly to an asset
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/assets/{{assetGUID}}/comments/{{guid}}/update
Content-Type: application/json

{
	"class" : "CommentRequestBody",
	"isPublic" : "true",
	"commentType" : "STANDARD_COMMENT",
	"commentText" : "This is the comment on the asset"
}

###
# @name removeCommentFromAsset
# Adds a comment directly to an asset
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/assets/{{assetGUID}}/comments/{{guid}}/delete
Content-Type: application/json

###
# @name addCommentReply
# Adds a reply to a comment
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/assets/{{assetGUID}}/comments/{{guid}}/replies
Content-Type: application/json

{
	"class" : "CommentRequestBody",
	"isPublic" : "true",
	"commentType" : "ANSWER",
	"commentText" : "This is the response to your comment"
}

###
# @name addRatingToAsset
# Adds a rating and optional review to an asset.
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/assets/{{assetGUID}}/ratings
Content-Type: application/json

{
	"class" : "RatingRequestBody",
	"isPublic" : "true",
	"starRating" : "ONE_STAR",
	"review" : "This is the optional review text."
}

###
# @name removeRatingFromAsset
# Adds a rating and optional review to an asset.
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/assets/{{assetGUID}}/ratings/delete
Content-Type: application/json

###
# @name addLikeToAsset
# Adds a "like" to an asset.
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/assets/{{assetGUID}}/likes
Content-Type: application/json

{
	"class" : "FeedbackRequestBody",
	"isPublic" : "true"
}

###
# @name removeLikeFromAsset
# Adds a "like" to an asset.
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/assets/{{assetGUID}}/likes/delete
Content-Type: application/json

###
# @name addTagToAsset
# Links a tag to an asset.
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/assets/{{assetGUID}}/tags/{{guid}}
Content-Type: application/json

{
	"class" : "FeedbackRequestBody",
	"isPublic" : "true"
}

###
# @name removeTagFromAsset
# Links a tag to an asset.
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/assets/{{assetGUID}}/tags/{{guid}}/delete
Content-Type: application/json

###
# @name addTagToElement
# Links a tag to an asset.
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/assets/elements/{{elementGUID}}/tags/{{guid}}
Content-Type: application/json

{
	"class" : "FeedbackRequestBody",
	"isPublic" : "true"
}

###
# @name removeTagFromElement
# Links a tag to an asset.
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/assets/elements/{{elementGUID}}/tags/{{guid}}/delete
Content-Type: application/json

###
# @name createTag
# Creates a new informal tag and returns the unique identifier for it.
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/tags
Content-Type: application/json

{
	"class" : "TagRequestBody",
	"isPrivateTag" : "true",
	"name" : "clinical-measurements",
	"description" : "Data collected from patients, medical staff and equipment that measure an aspect of the treatment."
}

###
# @name updateTag
# Updates the description of an existing tag (either private or public).
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/tags/{{guid}}/update
Content-Type: application/json

{
	"class" : "InformalTagProperties",
	"tagDescription" : "Data collected from patients, medical staff and equipment that measure an aspect of the treatment and its potential effects."
}

###
# @name deleteTag
# Removes a tag an all of its links to assets and other items.
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/tags/{{guid}}/delete
Content-Type: application/json

{
	"class" : "NullRequestBody"
}

###
# @name getTag
# Return the tag for the supplied unique identifier (guid).
GET {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/tags/{{guid}}
Content-Type: application/json

###
# @name getTagsByName
# Return the list of tags matching the supplied name.
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/tags/by-name?
    startFrom=0&
    pageSize=50
Content-Type: application/json

clinical-measurements

###
# @name getMyTagsByName
# Return the list of tags matching the supplied name.
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/tags/private/by-name?
    startFrom=0&
    pageSize=50
Content-Type: application/json

clinical-measurements

###
# @name findTags
# Return the Asset identified by the GUID and the attached Connection GUID
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/tags/by-search-string?
    startFrom=0&
    pageSize=50
Content-Type: application/json

{
    "class" : "SearchStringRequestBody",
    "searchString" : ".*."
}

###
# @name findMyTags
# Return the Asset identified by the GUID and the attached Connection GUID
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/tags/private/by-search-string?
    startFrom=0&
    pageSize=50
Content-Type: application/json

{
    "class" : "SearchStringRequestBody",
    "searchString" : ".*."
}

###
# @name getMeaningByGUID
# Return the Asset identified by the GUID.
GET {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumerusers/{{user}}/meanings/{{guid}}

###
# @name getMeaningByName
# Return the Asset identified by the GUID and the attached Connection GUID
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/meanings/by-name?
    startFrom=0&
    pageSize=50
Content-Type: application/json

{
    "class" : "NameRequestBody",
    "name" : "DropFoot"
}

###
# @name findMeanings
# Return the Asset identified by the GUID and the attached Connection GUID
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/meanings/by-search-string?
    startFrom=0&
    pageSize=50
Content-Type: application/json

{
    "class" : "SearchStringRequestBody",
    "searchString" : ".*."
}

###
# @name addAuditLogMessageForAsset
# Adds an audit log message about an asset.
POST {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-consumer/users/{{user}}/assets/{{assetGUID}}/log-records
Content-Type: application/json

{
	"class" : "LogRecordRequestBody",
	"connectorInstanceId" : "iiiiii",
	"connectionName" : "nnnnn",
	"connectorType" : "ttttt",
    "contextId" : "cccccc",
    "message" : "This is the log message text."
}